export const gymnastOfDayEn = {
  marquee: "FIVE ICONS · TEN TRIES · ONE DAILY MISSION", mysteryArt: "Partially hidden silhouette of the mystery athlete", missionOver: "THE TEN TRIES ARE GONE", pointsShort: "PTS", noPoints: "REVEALED · 0 PTS", editorialPower: "A PRFCT10 editorial interpretation, not a scientific assessment.", countries: { USA:"United States", BRA:"Brazil", ALG:"Algeria", CHN:"China", MEX:"Mexico", ROU:"Romania", RUS:"Russia" },
  back: "Back to PLAY", eyebrow: "PRFCT10 DAILY MISSION / 004", title: "GYMNAST OF THE DAY", locked: "IDENTITY LOCKED", intro: "Three clues. Four names. One legendary gymnast.", introFive: "Discover five gymnasts before your ten guesses run out.", files: "SECRET FILES", tries: "TOTAL TRIES", found: "FOUND {count}/5", attempts: "TRIES {count}/10", attemptsLeft: "{count} GUESSES LEFT", fileProgress: "FILE {current} OF 5", missionComplete: "DAILY MISSION COMPLETE", finalTitle: "YOU FOUND {count} OF 5", nextGymnast: "OPEN NEXT FILE", seeResults: "SEE MY RESULTS", start: "START THE 5-FILE MISSION", clue: "CLUE {number} OF 3", nextClue: "REVEAL NEXT CLUE", guessNow: "GUESS NOW", score: "{score} PTS", choose: "WHO IS SHE?", correct: "YOU CRACKED THE FILE!", wrong: "Not this one — another clue just unlocked.", finish: "SHOW ME THE ANSWER", reveal: "IDENTITY UNLOCKED", signature: "SIGNATURE MOMENT", story: "THE VERIFIED STORY", source: "OPEN OFFICIAL SOURCE", relationship: "EDITORIAL NOTE", choosePower: "CHOOSE YOUR POWER", choosePowerHelp: "Take one energy card from today’s story.", collected: "POWER COLLECTED", hall: "HALL OF POWER", hallEmpty: "Your first collectible is waiting.", streak: "DAY STREAK", best: "BEST", playAgain: "VIEW TODAY’S FILE", share: "SHARE WITHOUT SPOILERS", copied: "Spoiler-free result copied.", collection: "OPEN MY COLLECTION", closeCollection: "CLOSE COLLECTION", settings: "GAME SETTINGS", sound: "Sound", vibration: "Vibration", timer: "Timer", optional: "Optional · off by default", unavailable: "Today’s files are still being verified. Please return soon.", rights: "Original PRFCT10 abstract artwork · no athlete photo used", progress: "Progress", answers: "Answer choices", saved: "Saved to your Hall of Power.", powers: {
    focus: { name: "LASER FOCUS", line: "One clue. One breath. One move." }, courage: { name: "BRAVE TAKEOFF", line: "Start before perfect arrives." }, rhythm: { name: "RHYTHM FINDER", line: "Reconnect and keep moving." }, sparkle: { name: "SPOTLIGHT ENERGY", line: "Let your style take up space." }, patience: { name: "LONG GAME", line: "Progress is still progress." }, comeback: { name: "COMEBACK MAGIC", line: "A return can become a rise." }, team: { name: "TEAM GLOW", line: "Your power grows beside others." }
  }
};

export const gymnastOfDayEs = {
  marquee: "CINCO ÍCONOS · DIEZ INTENTOS · UNA MISIÓN DIARIA", mysteryArt: "Silueta parcialmente oculta de la atleta misteriosa", missionOver: "SE AGOTARON LOS DIEZ INTENTOS", pointsShort: "PTS", noPoints: "REVELADA · 0 PTS", editorialPower: "Una interpretación editorial de PRFCT10, no una evaluación científica.", countries: { USA:"Estados Unidos", BRA:"Brasil", ALG:"Argelia", CHN:"China", MEX:"México", ROU:"Rumania", RUS:"Rusia" },
  back: "Volver a PLAY", eyebrow: "MISIÓN DIARIA PRFCT10 / 004", title: "GIMNASTA DEL DÍA", locked: "IDENTIDAD BLOQUEADA", intro: "Tres pistas. Cuatro nombres. Una gimnasta legendaria.", introFive: "Descubre cinco gimnastas antes de agotar tus diez intentos.", files: "EXPEDIENTES SECRETOS", tries: "INTENTOS TOTALES", found: "DESCUBIERTAS {count}/5", attempts: "INTENTOS {count}/10", attemptsLeft: "QUEDAN {count} INTENTOS", fileProgress: "EXPEDIENTE {current} DE 5", missionComplete: "MISIÓN DIARIA COMPLETADA", finalTitle: "DESCUBRISTE {count} DE 5", nextGymnast: "ABRIR SIGUIENTE EXPEDIENTE", seeResults: "VER MIS RESULTADOS", start: "INICIAR LA MISIÓN DE 5", clue: "PISTA {number} DE 3", nextClue: "REVELAR LA SIGUIENTE PISTA", guessNow: "ADIVINAR AHORA", score: "{score} PTS", choose: "¿QUIÉN ES?", correct: "¡DESCIFRASTE EL EXPEDIENTE!", wrong: "No es ella: se acaba de revelar otra pista.", finish: "MOSTRARME LA RESPUESTA", reveal: "IDENTIDAD REVELADA", signature: "MOMENTO EMBLEMÁTICO", story: "LA HISTORIA VERIFICADA", source: "ABRIR FUENTE OFICIAL", relationship: "NOTA EDITORIAL", choosePower: "ELIGE TU PODER", choosePowerHelp: "Guarda una carta de energía inspirada en la historia de hoy.", collected: "PODER COLECCIONADO", hall: "SALÓN DEL PODER", hallEmpty: "Tu primer coleccionable te está esperando.", streak: "DÍAS DE RACHA", best: "MEJOR", playAgain: "VER EL EXPEDIENTE DE HOY", share: "COMPARTIR SIN SPOILERS", copied: "Resultado sin spoilers copiado.", collection: "ABRIR MI COLECCIÓN", closeCollection: "CERRAR COLECCIÓN", settings: "AJUSTES DEL JUEGO", sound: "Sonido", vibration: "Vibración", timer: "Cronómetro", optional: "Opcional · apagado inicialmente", unavailable: "Los expedientes de hoy todavía están en verificación. Vuelve pronto.", rights: "Arte abstracto original de PRFCT10 · no se utilizó una foto de la atleta", progress: "Progreso", answers: "Opciones de respuesta", saved: "Guardado en tu Salón del Poder.", powers: {
    focus: { name: "ENFOQUE LÁSER", line: "Una pista. Una respiración. Un movimiento." }, courage: { name: "DESPEGUE VALIENTE", line: "Empieza antes de que llegue lo perfecto." }, rhythm: { name: "RITMO PROPIO", line: "Reconecta y sigue avanzando." }, sparkle: { name: "ENERGÍA DE SPOTLIGHT", line: "Deja que tu estilo ocupe espacio." }, patience: { name: "JUEGO LARGO", line: "El progreso sigue siendo progreso." }, comeback: { name: "MAGIA DEL REGRESO", line: "Un regreso puede convertirse en un ascenso." }, team: { name: "BRILLO DE EQUIPO", line: "Tu poder crece junto a otras personas." }
  }
};
