const en = {
  language: { label: "Language", english: "EN", spanish: "ES" },
  navigation: {
    home: "Home", menu: "Menu", main: "Main navigation", shop: "Shop", shopAll: "Shop All",
    featured: "Featured", trainingGear: "Training Gear", accessories: "Accessories", mindGym: "Mind Gym",
    apparel: "Apparel", team: "Team", search: "Search", searchPlaceholder: "Products", account: "Account",
    greeting: "Hi, {name}", bag: "Bag", bagLabel: "View bag with {count} items"
  },
  product: {
    shopItem: "Shop item", viewDetails: "View details", viewDetailsFor: "View details for {name}",
    badges: "Product badges", noProducts: "No products found",
    noProductsHelp: "Try another filter or search term. PRFCT10 support can also help you find the right item.",
    priceOnRequest: "Price on request", fromPrice: "From {price}"
  },
  badges: { bestseller: "Bestseller", sale: "Sale", new: "New", limited: "Limited" },
  availability: {
    unavailable: "Unavailable", arrivingSoon: "Arriving soon", comingSoon: "Coming soon", inStock: "In stock",
    confirmedBeforePayment: "Availability confirmed before payment"
  },
  categories: {
    grip: "Grip", support: "Support", flexibility: "Flexibility", strength: "Strength", recovery: "Recovery",
    competition: "Competition", hairAccessories: "Hair Accessories", jewelry: "Jewelry", gymBags: "Gym Bags",
    gifts: "Gifts", sensory: "Sensory", puzzles: "Puzzles", tees: "Tees", croppedTees: "Cropped Tees",
    tanks: "Tanks", hoodiesSweaters: "Hoodies & Sweaters", shorts: "Shorts", periodUnderwear: "Period Underwear"
  },
  filters: {
    all: "All", allDepartments: "All Departments", necklaces: "Necklaces", bracelets: "Bracelets",
    hairAccessories: "Hair Accessories", competition: "Competition", organization: "Organization",
    giftsDetails: "Gifts & Details", grip: "Grip", support: "Support", strengthFlexibility: "Strength & Flexibility",
    recovery: "Recovery", puzzles: "Puzzles", sensory: "Sensory", fidget: "Fidget", challengeSets: "Challenge Sets",
    tops: "Tops", hoodiesSweaters: "Hoodies & Sweaters", shorts: "Shorts", periodBriefs: "Period Briefs", findFast: "Find it fast",
    sort: "Sort", featured: "Featured", priceLow: "Price: Low to High", priceHigh: "Price: High to Low",
    name: "Name A-Z", category: "Category", quickFinder: "Quick product finder",
    defaultHelp: "Filter by what you're looking for, then sort your favorites your way."
  },
  departments: {
    trainingHelp: "Filter by training need, then sort your essentials your way.",
    accessoriesHelp: "Filter by what you're looking for, then sort your favorites your way.",
    mindHelp: "Filter by the kind of challenge, then sort your favorites your way.",
    apparelHelp: "Filter by style, then sort your favorites your way."
  },
  assurances: {
    label: "Shopping assurances", shipping: "Tracked U.S. shipping", availability: "Availability confirmed before payment",
    returns: "Return and product support"
  },
  store: {
    hero: {
      boutique: { eyebrow: "PRFCT10 SHOP", title1: "SHOP", title2: "PRFCT10", text: "Grip, support, resistance, and control: everything for strong training with style." },
      training: { eyebrow: "PRFCT10 PERFORMANCE", title1: "GYMNASTICS", title2: "TRAINING GEAR", text: "Grip, support, strength, flexibility, and recovery essentials built for every training day.", cta: "Shop training gear" },
      coquette: { eyebrow: "PRFCT10 DETAILS", title1: "GYMNASTICS", title2: "ACCESSORIES", text: "Bows, jewelry, bags, sparkle, and finishing touches for every gym day.", cta: "Shop accessories" },
      mind: { eyebrow: "PRFCT10 MIND GYM", title1: "GYMNASTICS", title2: "MIND GYM", text: "Puzzles, sensory play, and clever little challenges made for curious minds.", cta: "Shop Mind Gym" },
      wear: { eyebrow: "PRFCT10 STYLE", title1: "GYMNASTICS", title2: "APPAREL", text: "Gymnastics-inspired pieces made for practice days, off days, and everywhere in between.", cta: "Shop apparel" },
      all: { eyebrow: "PRFCT10 SHOP", title1: "SHOP ALL", title2: "PRFCT10", text: "Browse training gear, accessories, Mind Gym favorites, and apparel in one place." },
      search: { eyebrow: "PRFCT10 SEARCH", title1: "SEARCH", title2: "RESULTS", empty: "Type a product to find it fast.", results: "Showing products related to “{query}”." }
    },
    intro: {
      training: { eyebrow: "PRFCT10 Performance", title1: "Grip it right.", title2: "Train with might.", text: "From grips and support to strength, flexibility, and recovery, find the essentials that keep training moving." },
      coquette: { eyebrow: "PRFCT10 Details", title1: "Add the spark.", title2: "Make your mark.", text: "Discover bows, bags, jewelry, sparkle, and everyday extras that bring personality to every routine." },
      mind: { eyebrow: "PRFCT10 Mind Gym", title1: "Play it smart.", title2: "Train every part.", text: "Explore puzzles, tactile challenges, sensory favorites, and colorful ways to keep curious minds engaged." },
      wear: { eyebrow: "Style in Motion", title1: "Dress to move.", title2: "Find your groove.", text: "Discover sporty, playful pieces that bring gymnastics energy, personality, and effortless style beyond the gym." },
      all: { eyebrow: "The full collection", title1: "Everything PRFCT10.", title2: "One easy shop.", text: "Browse every department, filter your options, and open any product for full details." }
    },
    shopAll: { browse: "Browse by department", title: "Shop the full consumer collection", filterLabel: "Filter Shop All by department" },
    sections: {
      trainingEyebrow: "PRFCT10 Performance", trainingTitle: "Training Gear", trainingText: "Grip, support, flexibility, strength, and recovery essentials for every training day.",
      accessoriesEyebrow: "PRFCT10 Details", accessoriesTitle: "Accessories", accessoriesText: "Bows, jewelry, bags, sparkle, and thoughtful details for practice, competition, and gifting.",
      mindEyebrow: "Play and focus", mindTitle: "Mind Gym", mindText: "Fidgets, puzzles, and sensory favorites for focus, patience, coordination, and play.",
      apparelEyebrow: "Style in Motion", apparelTitle: "Apparel", apparelText: "Sporty, playful pieces that bring gymnastics energy and effortless style beyond the gym."
    },
    departmentCards: {
      training: "Grip, support, and tools for practicing with more confidence.", cute: "Bows, jewelry, bags, and details to complete her look.",
      mind: "Fidgets, puzzles, and sensory favorites for thinking, focusing, and playing.", wear: "Comfortable lifestyle pieces for practice days and off days.", enter: "Enter"
    },
    shipping: { eyebrow: "U.S. Shipping", title1: "PRFCT10 SHIPS", title2: "ACROSS THE U.S.", text: "Tracked shipping across the United States, delivered straight to your door.", note: "Availability, delivery timing, and return support are confirmed before payment.", cta: "Keep shopping" }
  },
  home: {
    hero: { label: "PRFCT10 campaign gallery", eyebrow: "MADE FOR GYMNASTS", title1: "TRAIN WITH CONFIDENCE.", title2: "SHINE WITH STYLE.", text: "Accessories, training gear, and thoughtful details designed to support every practice with safety, style, and confidence.", shop: "SHOP NOW", standard: "THE STANDARD", images: "Campaign images", imageLabel: "Show {name} campaign", pause: "Pause campaign carousel", resume: "Resume campaign carousel", play: "Play", paused: "Pause", scroll: "SCROLL" },
    discovery: { label: "Help choosing PRFCT10 products", eyebrow: "A little help from PRFCT10", title1: "Pick it quick.", title2: "Make it chic.", text: "Find your way through training essentials, accessories, Mind Gym favorites, and apparel.", finder: "Help me choose", browse: "Or browse by department" },
    departments: { eyebrow: "Explore the collection", title: "Shop by Department", text: "Start with what you need today, then discover the rest of PRFCT10.", training: "Grip, support, flexibility, strength, and recovery essentials.", accessories: "Bows, bags, jewelry, sparkle, and thoughtful finishing details.", mind: "Puzzles, sensory favorites, and playful tools for calm and focus.", apparel: "Gymnastics-inspired pieces for practice days and everywhere after.", cta: "Shop department" },
    featured: { eyebrow: "Featured", title: "Most-Loved PRFCT10", text: "Eight featured picks across training, accessories, and Mind Gym—an easy first stop for discovering the collection.", cta: "Shop all products" }
  },
  newsletter: { eyebrow: "PRFCT10 CLUB", footerTitle: "STAY IN THE LOOP.", footerText: "New drops, restocks, meet-day favorites, and everything new at PRFCT10.", modalTitle1: "GOOD THINGS", modalTitle2: "LAND HERE FIRST.", modalText: "New drops, restocks, gym-day favorites, and a little PRFCT10 magic.", privacy: "No spam. Just really good gymnastics stuff.", email: "Email address", join: "JOIN", joinClub: "JOIN THE CLUB", joining: "JOINING…", invalid: "Enter a valid email address.", success: "Welcome to PRFCT10 CLUB.", notConfigured: "Newsletter integration not configured.", error: "We couldn’t add you right now. Please try again.", close: "Close PRFCT10 CLUB signup" },
  footer: { tagline: "The power is in your hands.", description: "A shop of smart, pretty essentials for gymnasts who train, recover, and celebrate every milestone.", partnership: "Available in partnership with", explore: "Explore", shop: "Shop", standard: "The Standard", about: "About", shipping: "U.S. shipping available", support: "Support & Social", whatsapp: "WhatsApp support", shopPrfct10: "Shop PRFCT10", rights: "2026 PRFCT10. All rights reserved.", backHome: "Back to Home" },
  modal: { close: "Close product details", images: "Images of {name}", gallery: "Product gallery", image: "View image {number} of {name}", previous: "Previous image", next: "Next image", shop: "PRFCT10 Shop", quickBenefits: "Quick benefits", options: "Product options", delivery: "Delivery options", quantity: "Quantity {quantity}", addBag: "Add to bag", shipping: "U.S. shipping", returnSupport: "Friendly return and product support", noPayment: "No payment is collected until availability is confirmed", whatsapp: "Ask about this item on WhatsApp", availability: "Availability", exactOptions: "Exact colors, sizes, and fulfillment are confirmed before payment.", assisted: "Assisted ordering", about: "About this item", colors: "Colors and options", basedAvailability: "Based on availability", bestFor: "Best for", bestForDefault: "Gifts, competitions, team details, and practice looks.", ordering: "Ordering and delivery", addInstruction: "Add the item to your bag.", supportInstruction: "PRFCT10 support confirms availability and U.S. shipping.", paymentInstruction: "Payment follows through assisted ordering; online checkout can be added later.", howUse: "How to use", specifications: "Specifications", faq: "Frequently asked questions", uses: "Recommended sports and uses", faqFallback: "Frequently asked question", ship: "Ship", tracked: "Tracked U.S. delivery", calculated: "Calculated after confirmation", pickup: "Store pickup", requestPickup: "Request pickup", confirmedSupport: "Confirmed with support", local: "Local delivery", zip: "Request by ZIP code" },
  story: {
    brandTitle: "STRONG, PRETTY, READY", brandText: "For every practice, every competition, and every milestone ahead.",
    standardEyebrow: "THE PRFCT10 STANDARD", standardTitle1: "PREPARE WITH STYLE.", standardTitle2: "TRAIN WITH CONFIDENCE.", standardText: "PRFCT10 supports gymnasts who care for themselves, prepare with intention, and come back stronger every day.",
    principles: [
      { title: "Train with intention", text: "Every practice matters more when you know what you are building." },
      { title: "Care for what supports you", text: "Hands, wrists, knees, heels, and energy deserve attention too." },
      { title: "Looking polished counts", text: "Feeling good can help athletes train with more confidence and joy." },
      { title: "Technique comes first", text: "The beautiful parts shine brighter when they are built with control, patience, and care." },
      { title: "Confidence is practiced", text: "It is repeated, protected, and celebrated." },
      { title: "Details matter", text: "Grip, support, style, and preparation are all part of the standard." }
    ],
    aboutEyebrow: "ABOUT", aboutTitle1: "MADE FOR GYMNASTS", aboutTitle2: "WHO LOVE TO CARE FOR THEMSELVES.", aboutText1: "PRFCT10 was created to support gymnasts inside and outside the gym: practice days, competition days, and every milestone between.", aboutText2: "Every detail matters: the grip that builds confidence, the support that protects, and the accessory that makes the moment feel special.", aboutMotto: "Train to win",
    socialLabel: "PRFCT10 social media", socialEyebrow: "PRFCT10 SOCIAL", socialTitle: "FOLLOW THE SPARKLE", socialText: "Ideas, new arrivals, and sweet details for every practice, competition, and milestone.",
    finalTitle1: "READY TO RAISE", finalTitle2: "YOUR STANDARD?", finalCta: "Keep shopping"
  },
  team: { kicker: "PRFCT10 TEAM", title1: "Train together.", title2: "Shine together.", summary: "Custom training and competition looks designed around your team, your colors, and your season.", quote: "Start a Team Quote", how: "How It Works", highlights: "PRFCT10 Team service highlights", custom: "Custom direction", sizing: "Team sizing", assisted: "Assisted quote", mediaLabel: "PRFCT10 LEOTARDS", heroNote: "Custom quote service · No online payment", servicesEyebrow: "Custom team looks", servicesTitle: "Built around your program.", servicesText: "PRFCT10 TEAM is a guided design and quote service—not a standard Apparel product collection.", competition: "Competition Leotards", competitionText: "Custom competition looks developed around your program, colors, season, and design direction.", training: "Training Leotards", trainingText: "Custom practice looks created for team identity, repeat training, and coordinated presentation.", request: "Request this service", processEyebrow: "How it works", processTitle: "A clear path from idea to team look.", steps: [{ title: "Tell Us About Your Team", text: "Share your colors, athlete count, age range, style, budget, and season." }, { title: "We Build the Direction", text: "We shape the fabrics, colors, embellishment level, and visual concept." }, { title: "Approve the Look", text: "Confirm sizing and design, request adjustments, and give final approval." }, { title: "Your Team Shines", text: "Your approved look moves into production and delivery." }], start: "Start the conversation", needs: "Tell us what your team needs.", intro: "Share the essentials now. PRFCT10 will help confirm design direction, timing, sizing, and quote details with you directly.", guided: "Guided, not automated", noClaims: "No inventory claims, checkout, or payment are attached to this inquiry.", form: { name: "Contact name", email: "Email", phone: "Phone", team: "Gym / team name", count: "Estimated athlete count", service: "Service", competition: "Competition Leotards", training: "Training Leotards", both: "Competition + Training Leotards", colors: "Desired colors", colorsPlaceholder: "Team colors or open to direction", budget: "Approximate budget", budgetPlaceholder: "Per athlete or total range", date: "Target delivery date", notes: "Notes", notesPlaceholder: "Age range, season, style, embellishment ideas, sizing questions, or anything else we should know", handoff: "Your answers open as a prefilled WhatsApp message. Nothing is submitted or paid for on this site." } },
  auth: { signTitle: "Sign in to your account", createTitle: "Create your account", signText: "Save your cart, review orders, and check out faster.", createText: "Register your email to save orders, favorites, and PRFCT10 perks.", closeSign: "Close sign in", options: "Account options", sign: "Sign in", create: "Create account", google: "Continue with Google", emailDivider: "or use your email", name: "Name", email: "Email", password: "Password", passwordPlaceholder: "Minimum 6 characters", note: "This account flow is ready to connect with Google, Firebase, Auth0, Shopify customer accounts, or your preferred backend.", googleAccount: "Google Account" },
  cart: { assisted: "Assisted ordering", title: "Cart ({count})", intro: "Review your items, then continue with PRFCT10 support. No payment is collected on this site yet.", active: "PRFCT10 account active", have: "Have an account?", create: "Create your account", shoppingAs: "Shopping as {email}.", accountText: "Use your email to save orders, shipping details, and PRFCT10 perks.", connectedGoogle: "Connected with Google", connectedEmail: "Connected with email", join: "Join now", namePlaceholder: "Gymnast or parent name", openAccount: "Open account modal", items: "Cart items", emptyTitle: "There are no items in your cart.", emptyText: "Add your PRFCT10 favorites, then return here to review your bag and request ordering support.", suggestions: "Purchase suggestions", goes: "Goes well with", smart: "Smart add-ons based on what is in your cart.", addCart: "Add to Cart", policies: "Purchase policies", returnTitle: "Return Policy", returnText: "Contact PRFCT10 support for return or exchange guidance. Eligibility is confirmed before the order is finalized.", guaranteeTitle: "PRFCT10 Guarantee", guaranteeText: "We review every order before shipping to protect quality, packaging, and presentation.", summary: "Order summary", phone: "Phone", phonePlaceholder: "Contact phone", zip: "ZIP code", zipPlaceholder: "Shipping ZIP code", delivery: "Delivery", standard: "Standard shipping", pickup: "Store pickup", local: "Local delivery", note: "Order note", notePlaceholder: "Color, size, ZIP code, delivery notes, or special request", promo: "Use a Promocode", apply: "Apply", subtotal: "Subtotal ({count} items)", knownSubtotal: "Known-price subtotal", discount: "Discount", shipping: "Shipping", confirmSupport: "Confirm with support", free: "Free", tax: "Estimated tax", later: "Calculated later", estimate: "Estimated total", knownEstimate: "Known-price estimate", priceNotice: "One or more items need price confirmation. No placeholder price has been added to the estimate.", whatsapp: "Continue on WhatsApp", opened: "WhatsApp opened with your order request. PRFCT10 will confirm availability before payment.", quick: "Quick cart", closeQuick: "Close quick cart", added: "Added to cart", prfct10: "PRFCT10 cart", oneItem: "{count} item", manyItems: "{count} items", close: "Close cart", mayLike: "You may also like", subtotalShort: "Subtotal", review: "Review bag & order support", shippingPending: "U.S. shipping and final pricing are confirmed by PRFCT10 support before payment.", shippingAvailable: "Tracked U.S. shipping is available. Continue to review your bag and request support.", freeUnlocked: "Free U.S. shipping unlocked", freeMore: "Spend {amount} more for free U.S. shipping", trackedCalculated: "Tracked U.S. shipping is calculated after price and availability confirmation." },
  finder: { title: "PRFCT10 Product Finder", note: "Shopping guidance, not medical advice", close: "Close product finder", step: "Step {current} of {total}", questions: { shoppingFor: "What are you shopping for?", trainingNeed: "What does she need help with?", level: "What level best fits?", levelHelp: "This only helps us order the suggestions. It does not assess skill or readiness." }, options: { training: "Training", competition: "Competition Day", cute: "Something Cute", mind: "Mind Gym", apparel: "Apparel", gift: "A Gift", barsGrip: "Bars & Grip", wristSupport: "Wrist Support", strengthFlexibility: "Strength & Flexibility", recoveryComfort: "Recovery & Comfort", notSure: "Not Sure", beginner: "Beginner", developmental: "Xcel / Developmental", competitive: "Competitive" }, resultsEyebrow: "Your PRFCT10 edit", resultsTitle: "A few thoughtful matches.", resultsText: "Based on your answers, these are useful places to start. Check fit, use, and availability in each product.", view: "View item", back: "Back", reset: "Start over", all: "View all products", reasons: { "bar-grips": "A bar-focused essential for grip feel and palm coverage during repeated practice.", chalk: "A simple gym-bag staple for keeping hands dry and supporting grip feel.", "sweat-wristbands": "A comfortable choice for sweat control during longer practice sessions.", "hand-balm": "A practical post-practice option for dry hands after chalk, bars, and friction.", "coquet-lazos-tul": "A polished finishing detail for competition hair, photos, or a coordinated gym look.", "coquet-glitter-spray": "A quick finishing touch for competition-day hair, photos, and special moments.", "mental-squishy-dumpling": "A soft sensory pick for busy hands and calm breaks around practice.", "mental-bolita-puzzle": "A portable puzzle for focused play, patience, and hand coordination." } },
  common: { close: "Close", add: "Add", remove: "Remove", keepShopping: "Keep shopping" }
};

const es = {
  language: { label: "Idioma", english: "EN", spanish: "ES" },
  navigation: {
    home: "Inicio", menu: "Menú", main: "Navegación principal", shop: "Comprar", shopAll: "Ver todo",
    featured: "Destacados", trainingGear: "Entrenamiento", accessories: "Accesorios", mindGym: "Gimnasia mental",
    apparel: "Ropa", team: "Equipos", search: "Buscar", searchPlaceholder: "Productos", account: "Cuenta",
    greeting: "Hola, {name}", bag: "Bolsa", bagLabel: "Ver bolsa con {count} artículos"
  },
  product: {
    shopItem: "Comprar", viewDetails: "Ver detalles", viewDetailsFor: "Ver detalles de {name}",
    badges: "Etiquetas del producto", noProducts: "No se encontraron productos",
    noProductsHelp: "Prueba otro filtro o término de búsqueda. El equipo PRFCT10 también puede ayudarte.",
    priceOnRequest: "Precio a consultar", fromPrice: "Desde {price}"
  },
  badges: { bestseller: "Más vendido", sale: "Oferta", new: "Nuevo", limited: "Limitado" },
  availability: {
    unavailable: "No disponible", arrivingSoon: "Próximamente", comingSoon: "Próximamente", inStock: "Disponible",
    confirmedBeforePayment: "Disponibilidad confirmada antes del pago"
  },
  categories: {
    grip: "Agarre", support: "Soporte", flexibility: "Flexibilidad", strength: "Fuerza", recovery: "Recuperación",
    competition: "Competencia", hairAccessories: "Accesorios para el cabello", jewelry: "Joyería", gymBags: "Bolsos de gimnasio",
    gifts: "Regalos", sensory: "Sensorial", puzzles: "Puzzles", tees: "Camisetas", croppedTees: "Camisetas cortas",
    tanks: "Camisetas sin mangas", hoodiesSweaters: "Sudaderas y suéteres", shorts: "Shorts", periodUnderwear: "Ropa interior menstrual"
  },
  filters: {
    all: "Todo", allDepartments: "Todos los departamentos", necklaces: "Collares", bracelets: "Pulseras",
    hairAccessories: "Accesorios para el cabello", competition: "Competencia", organization: "Organización",
    giftsDetails: "Regalos y detalles", grip: "Agarre", support: "Soporte", strengthFlexibility: "Fuerza y flexibilidad",
    recovery: "Recuperación", puzzles: "Puzzles", sensory: "Sensorial", fidget: "Fidget", challengeSets: "Sets de retos",
    tops: "Camisetas", hoodiesSweaters: "Sudaderas y suéteres", shorts: "Shorts", periodBriefs: "Braguitas menstruales", findFast: "Encuéntralo rápido",
    sort: "Ordenar", featured: "Destacados", priceLow: "Precio: menor a mayor", priceHigh: "Precio: mayor a menor",
    name: "Nombre A-Z", category: "Categoría", quickFinder: "Buscador rápido de productos",
    defaultHelp: "Filtra lo que buscas y luego ordena tus favoritos."
  },
  departments: {
    trainingHelp: "Filtra por necesidad de entrenamiento y ordena tus esenciales.",
    accessoriesHelp: "Filtra por lo que buscas y ordena tus favoritos.",
    mindHelp: "Filtra por tipo de reto y ordena tus favoritos.",
    apparelHelp: "Filtra por estilo y ordena tus favoritos."
  },
  assurances: {
    label: "Confianza al comprar", shipping: "Envíos con seguimiento en EE. UU.",
    availability: "Disponibilidad confirmada antes del pago", returns: "Soporte de devoluciones y productos"
  },
  store: {
    hero: {
      boutique: { eyebrow: "TIENDA PRFCT10", title1: "COMPRA", title2: "PRFCT10", text: "Agarre, soporte, resistencia y control: todo para entrenar fuerte con estilo." },
      training: { eyebrow: "RENDIMIENTO PRFCT10", title1: "GIMNASIA", title2: "ENTRENAMIENTO", text: "Esenciales de agarre, soporte, fuerza, flexibilidad y recuperación para cada práctica.", cta: "Comprar entrenamiento" },
      coquette: { eyebrow: "DETALLES PRFCT10", title1: "GIMNASIA", title2: "ACCESORIOS", text: "Lazos, joyería, bolsos, brillo y detalles para cada día de gimnasio.", cta: "Comprar accesorios" },
      mind: { eyebrow: "GIMNASIA MENTAL PRFCT10", title1: "GIMNASIA", title2: "MENTAL", text: "Puzzles, juego sensorial y pequeños retos para mentes curiosas.", cta: "Comprar gimnasia mental" },
      wear: { eyebrow: "ESTILO PRFCT10", title1: "GIMNASIA", title2: "ROPA", text: "Piezas inspiradas en gimnasia para días de práctica, descanso y todo lo demás.", cta: "Comprar ropa" },
      all: { eyebrow: "TIENDA PRFCT10", title1: "VER TODO", title2: "PRFCT10", text: "Explora entrenamiento, accesorios, gimnasia mental y ropa en un solo lugar." },
      search: { eyebrow: "BÚSQUEDA PRFCT10", title1: "RESULTADOS", title2: "DE BÚSQUEDA", empty: "Escribe un producto para encontrarlo rápido.", results: "Mostrando productos relacionados con “{query}”." }
    },
    intro: {
      training: { eyebrow: "Rendimiento PRFCT10", title1: "Agarra mejor.", title2: "Entrena con fuerza.", text: "Encuentra agarre, soporte, fuerza, flexibilidad y recuperación para mantener cada práctica en movimiento." },
      coquette: { eyebrow: "Detalles PRFCT10", title1: "Suma el brillo.", title2: "Deja tu marca.", text: "Descubre lazos, bolsos, joyería y detalles que aportan personalidad a cada rutina." },
      mind: { eyebrow: "Gimnasia mental PRFCT10", title1: "Juega con intención.", title2: "Entrena cada parte.", text: "Explora puzzles, retos táctiles y favoritos sensoriales para mantener la mente activa." },
      wear: { eyebrow: "Estilo en movimiento", title1: "Vístete para moverte.", title2: "Encuentra tu ritmo.", text: "Descubre piezas deportivas y alegres con energía de gimnasia y estilo más allá del gimnasio." },
      all: { eyebrow: "La colección completa", title1: "Todo PRFCT10.", title2: "Una tienda fácil.", text: "Explora cada departamento, filtra tus opciones y abre cualquier producto para ver detalles." }
    },
    shopAll: { browse: "Explora por departamento", title: "Compra toda la colección", filterLabel: "Filtrar todos los productos por departamento" },
    sections: {
      trainingEyebrow: "Rendimiento PRFCT10", trainingTitle: "Entrenamiento", trainingText: "Esenciales de agarre, soporte, flexibilidad, fuerza y recuperación.",
      accessoriesEyebrow: "Detalles PRFCT10", accessoriesTitle: "Accesorios", accessoriesText: "Lazos, joyería, bolsos, brillo y detalles para práctica, competencia y regalos.",
      mindEyebrow: "Juego y enfoque", mindTitle: "Gimnasia mental", mindText: "Fidgets, puzzles y favoritos sensoriales para enfoque, paciencia, coordinación y juego.",
      apparelEyebrow: "Estilo en movimiento", apparelTitle: "Ropa", apparelText: "Piezas deportivas y alegres con energía de gimnasia y estilo sencillo fuera del gimnasio."
    },
    departmentCards: {
      training: "Agarre, soporte y herramientas para practicar con más confianza.", cute: "Lazos, joyería, bolsos y detalles para completar su look.",
      mind: "Fidgets, puzzles y favoritos sensoriales para pensar, enfocarse y jugar.", wear: "Piezas cómodas para días de práctica y descanso.", enter: "Entrar"
    },
    shipping: { eyebrow: "Envíos en EE. UU.", title1: "PRFCT10 ENVÍA", title2: "EN TODO EE. UU.", text: "Envíos con seguimiento a todo Estados Unidos, directo a tu puerta.", note: "La disponibilidad, el tiempo de entrega y el soporte de devoluciones se confirman antes del pago.", cta: "Seguir comprando" }
  },
  home: {
    hero: { label: "Galería de campañas PRFCT10", eyebrow: "HECHO PARA GIMNASTAS", title1: "ENTRENA CON CONFIANZA.", title2: "BRILLA CON ESTILO.", text: "Accesorios, entrenamiento y detalles pensados para acompañar cada práctica con seguridad, estilo y confianza.", shop: "COMPRAR AHORA", standard: "EL ESTÁNDAR", images: "Imágenes de campaña", imageLabel: "Mostrar campaña de {name}", pause: "Pausar carrusel", resume: "Reanudar carrusel", play: "Reproducir", paused: "Pausar", scroll: "DESLIZA" },
    discovery: { label: "Ayuda para elegir productos PRFCT10", eyebrow: "Una pequeña ayuda de PRFCT10", title1: "Elige rápido.", title2: "Hazlo con estilo.", text: "Encuentra entrenamiento, accesorios, favoritos de gimnasia mental y ropa.", finder: "Ayúdame a elegir", browse: "O explora por departamento" },
    departments: { eyebrow: "Explora la colección", title: "Compra por departamento", text: "Comienza con lo que necesitas hoy y luego descubre el resto de PRFCT10.", training: "Esenciales de agarre, soporte, flexibilidad, fuerza y recuperación.", accessories: "Lazos, bolsos, joyería, brillo y detalles especiales.", mind: "Puzzles, favoritos sensoriales y herramientas de juego para enfoque.", apparel: "Piezas inspiradas en gimnasia para práctica y días de descanso.", cta: "Ver departamento" },
    featured: { eyebrow: "Destacados", title: "Los más queridos de PRFCT10", text: "Ocho favoritos de entrenamiento, accesorios y gimnasia mental para descubrir la colección.", cta: "Ver todos los productos" }
  },
  newsletter: { eyebrow: "CLUB PRFCT10", footerTitle: "NO TE PIERDAS NADA.", footerText: "Nuevos lanzamientos, reposiciones, favoritos de competencia y todo lo nuevo en PRFCT10.", modalTitle1: "LO BUENO", modalTitle2: "LLEGA AQUÍ PRIMERO.", modalText: "Nuevos lanzamientos, reposiciones, favoritos del gimnasio y un poco de magia PRFCT10.", privacy: "Sin spam. Solo cosas de gimnasia que valen la pena.", email: "Correo electrónico", join: "UNIRME", joinClub: "UNIRME AL CLUB", joining: "UNIENDO…", invalid: "Ingresa un correo electrónico válido.", success: "Bienvenida al CLUB PRFCT10.", notConfigured: "La integración del boletín no está configurada.", error: "No pudimos agregarte ahora. Inténtalo de nuevo.", close: "Cerrar registro del CLUB PRFCT10" },
  footer: { tagline: "El poder está en tus manos.", description: "Una tienda de esenciales inteligentes y bonitos para gimnastas que entrenan, se recuperan y celebran cada logro.", partnership: "Disponible en alianza con", explore: "Explorar", shop: "Comprar", standard: "El estándar", about: "Nosotros", shipping: "Envíos disponibles en EE. UU.", support: "Soporte y redes", whatsapp: "Soporte por WhatsApp", shopPrfct10: "Comprar PRFCT10", rights: "2026 PRFCT10. Todos los derechos reservados.", backHome: "Volver al inicio" },
  modal: { close: "Cerrar detalles del producto", images: "Imágenes de {name}", gallery: "Galería del producto", image: "Ver imagen {number} de {name}", previous: "Imagen anterior", next: "Imagen siguiente", shop: "Tienda PRFCT10", quickBenefits: "Beneficios principales", options: "Opciones del producto", delivery: "Opciones de entrega", quantity: "Cantidad {quantity}", addBag: "Agregar a la bolsa", shipping: "Envíos en EE. UU.", returnSupport: "Soporte amable para productos y devoluciones", noPayment: "No se cobra ningún pago hasta confirmar disponibilidad", whatsapp: "Consultar este producto por WhatsApp", availability: "Disponibilidad", exactOptions: "Los colores, tallas y entrega se confirman antes del pago.", assisted: "Pedido asistido", about: "Sobre este producto", colors: "Colores y opciones", basedAvailability: "Según disponibilidad", bestFor: "Ideal para", bestForDefault: "Regalos, competencias, detalles de equipo y looks de práctica.", ordering: "Pedido y entrega", addInstruction: "Agrega el producto a tu bolsa.", supportInstruction: "El equipo PRFCT10 confirma disponibilidad y envío.", paymentInstruction: "El pago se completa mediante pedido asistido; el checkout en línea puede añadirse después.", howUse: "Cómo usar", specifications: "Especificaciones", faq: "Preguntas frecuentes", uses: "Deportes y usos recomendados", faqFallback: "Pregunta frecuente", ship: "Envío", tracked: "Entrega con seguimiento en EE. UU.", calculated: "Calculado después de la confirmación", pickup: "Retiro en tienda", requestPickup: "Solicitar retiro", confirmedSupport: "Confirmado con soporte", local: "Entrega local", zip: "Solicitar por código postal" },
  story: {
    brandTitle: "FUERTE, LINDA, LISTA", brandText: "Para cada práctica, cada competencia y cada logro por venir.",
    standardEyebrow: "EL ESTÁNDAR PRFCT10", standardTitle1: "PREPÁRATE CON ESTILO.", standardTitle2: "ENTRENA CON CONFIANZA.", standardText: "PRFCT10 acompaña a gimnastas que se cuidan, se preparan con intención y vuelven más fuertes cada día.",
    principles: [
      { title: "Entrena con intención", text: "Cada práctica importa más cuando sabes lo que estás construyendo." },
      { title: "Cuida lo que te sostiene", text: "Manos, muñecas, rodillas, talones y energía también merecen atención." },
      { title: "Verse bien también cuenta", text: "Sentirse bien ayuda a entrenar con más confianza y alegría." },
      { title: "La técnica va primero", text: "Lo bonito brilla más cuando se construye con control, paciencia y cuidado." },
      { title: "La confianza se practica", text: "Se repite, se protege y se celebra." },
      { title: "Los detalles importan", text: "Agarre, soporte, estilo y preparación forman parte del estándar." }
    ],
    aboutEyebrow: "NOSOTROS", aboutTitle1: "HECHO PARA GIMNASTAS", aboutTitle2: "QUE AMAN CUIDARSE.", aboutText1: "PRFCT10 fue creado para acompañar a gimnastas dentro y fuera del gimnasio: en prácticas, competencias y cada logro intermedio.", aboutText2: "Cada detalle importa: el agarre que da confianza, el soporte que protege y el accesorio que hace especial el momento.", aboutMotto: "Entrena para ganar",
    socialLabel: "Redes sociales PRFCT10", socialEyebrow: "PRFCT10 SOCIAL", socialTitle: "SIGUE EL BRILLO", socialText: "Ideas, novedades y detalles lindos para cada práctica, competencia y logro.",
    finalTitle1: "¿LISTA PARA ELEVAR", finalTitle2: "TU ESTÁNDAR?", finalCta: "Seguir comprando"
  },
  team: { kicker: "EQUIPOS PRFCT10", title1: "Entrenen juntas.", title2: "Brillen juntas.", summary: "Looks personalizados de entrenamiento y competencia diseñados para tu equipo, tus colores y tu temporada.", quote: "Iniciar cotización de equipo", how: "Cómo funciona", highlights: "Aspectos del servicio para equipos PRFCT10", custom: "Dirección personalizada", sizing: "Tallas de equipo", assisted: "Cotización asistida", mediaLabel: "Brillo de Equipo", heroNote: "Servicio de cotización personalizada · Sin pago en línea", servicesEyebrow: "Looks personalizados de equipo", servicesTitle: "Creado alrededor de tu programa.", servicesText: "PRFCT10 TEAM es un servicio guiado de diseño y cotización, no una colección normal de ropa.", competition: "Mallas de competencia", competitionText: "Looks de competencia personalizados según tu programa, colores, temporada y dirección de diseño.", training: "Mallas de entrenamiento", trainingText: "Looks de práctica personalizados para identidad de equipo, entrenamiento y presentación coordinada.", request: "Solicitar este servicio", processEyebrow: "Cómo funciona", processTitle: "Un camino claro desde la idea hasta el look del equipo.", steps: [{ title: "Cuéntanos sobre tu equipo", text: "Comparte colores, cantidad de atletas, edades, estilo, presupuesto y temporada." }, { title: "Creamos la dirección", text: "Definimos telas, colores, nivel de brillo y concepto visual." }, { title: "Aprueba el look", text: "Confirma tallas y diseño, solicita ajustes y da la aprobación final." }, { title: "Tu equipo brilla", text: "El look aprobado pasa a producción y entrega." }], start: "Comienza la conversación", needs: "Cuéntanos qué necesita tu equipo.", intro: "Comparte lo esencial ahora. PRFCT10 te ayudará a confirmar diseño, tiempos, tallas y detalles de cotización.", guided: "Guiado, no automatizado", noClaims: "Esta consulta no incluye inventario, checkout ni pago.", form: { name: "Nombre de contacto", email: "Correo electrónico", phone: "Teléfono", team: "Gimnasio / equipo", count: "Cantidad estimada de atletas", service: "Servicio", competition: "Mallas de competencia", training: "Mallas de entrenamiento", both: "Mallas de competencia + entrenamiento", colors: "Colores deseados", colorsPlaceholder: "Colores del equipo o abierto a dirección", budget: "Presupuesto aproximado", budgetPlaceholder: "Por atleta o rango total", date: "Fecha de entrega deseada", notes: "Notas", notesPlaceholder: "Edades, temporada, estilo, ideas de brillo, tallas o cualquier otro detalle", handoff: "Tus respuestas se abren como mensaje de WhatsApp. No se envía ni cobra nada en este sitio." } },
  auth: { signTitle: "Inicia sesión en tu cuenta", createTitle: "Crea tu cuenta", signText: "Guarda tu bolsa, revisa pedidos y compra más rápido.", createText: "Registra tu correo para guardar pedidos, favoritos y beneficios PRFCT10.", closeSign: "Cerrar inicio de sesión", options: "Opciones de cuenta", sign: "Iniciar sesión", create: "Crear cuenta", google: "Continuar con Google", emailDivider: "o usa tu correo", name: "Nombre", email: "Correo electrónico", password: "Contraseña", passwordPlaceholder: "Mínimo 6 caracteres", note: "Este flujo está listo para conectarse con Google, Firebase, Auth0, cuentas de Shopify o tu backend preferido.", googleAccount: "Cuenta de Google" },
  cart: { assisted: "Pedido asistido", title: "Bolsa ({count})", intro: "Revisa tus productos y continúa con el equipo PRFCT10. Este sitio todavía no cobra pagos.", active: "Cuenta PRFCT10 activa", have: "¿Ya tienes cuenta?", create: "Crea tu cuenta", shoppingAs: "Comprando como {email}.", accountText: "Usa tu correo para guardar pedidos, datos de envío y beneficios PRFCT10.", connectedGoogle: "Conectado con Google", connectedEmail: "Conectado con correo", join: "Únete", namePlaceholder: "Nombre de gimnasta o representante", openAccount: "Abrir cuenta", items: "Productos en la bolsa", emptyTitle: "No hay productos en tu bolsa.", emptyText: "Agrega tus favoritos PRFCT10 y vuelve aquí para revisar la bolsa y solicitar ayuda con el pedido.", suggestions: "Sugerencias de compra", goes: "Combina bien con", smart: "Complementos según lo que tienes en tu bolsa.", addCart: "Agregar a la bolsa", policies: "Políticas de compra", returnTitle: "Política de devoluciones", returnText: "Contacta al equipo PRFCT10 para recibir orientación sobre cambios o devoluciones. La elegibilidad se confirma antes de finalizar el pedido.", guaranteeTitle: "Garantía PRFCT10", guaranteeText: "Revisamos cada pedido antes del envío para cuidar la calidad, el empaque y la presentación.", summary: "Resumen del pedido", phone: "Teléfono", phonePlaceholder: "Teléfono de contacto", zip: "Código postal", zipPlaceholder: "Código postal de envío", delivery: "Entrega", standard: "Envío estándar", pickup: "Retiro en tienda", local: "Entrega local", note: "Nota del pedido", notePlaceholder: "Color, talla, código postal, entrega o solicitud especial", promo: "Usar código promocional", apply: "Aplicar", subtotal: "Subtotal ({count} artículos)", knownSubtotal: "Subtotal con precios conocidos", discount: "Descuento", shipping: "Envío", confirmSupport: "Confirmar con soporte", free: "Gratis", tax: "Impuesto estimado", later: "Calculado después", estimate: "Total estimado", knownEstimate: "Estimado con precios conocidos", priceNotice: "Uno o más productos requieren confirmar precio. No se añadió un precio provisional.", whatsapp: "Continuar por WhatsApp", opened: "WhatsApp abrió tu solicitud. PRFCT10 confirmará disponibilidad antes del pago.", quick: "Bolsa rápida", closeQuick: "Cerrar bolsa rápida", added: "Agregado a la bolsa", prfct10: "Bolsa PRFCT10", oneItem: "{count} artículo", manyItems: "{count} artículos", close: "Cerrar bolsa", mayLike: "También te puede gustar", subtotalShort: "Subtotal", review: "Revisar bolsa y pedir ayuda", shippingPending: "El envío en EE. UU. y el precio final se confirman con PRFCT10 antes del pago.", shippingAvailable: "Hay envíos con seguimiento en EE. UU. Revisa tu bolsa y solicita ayuda.", freeUnlocked: "Envío gratis en EE. UU. desbloqueado", freeMore: "Agrega {amount} para envío gratis en EE. UU.", trackedCalculated: "El envío con seguimiento se calcula después de confirmar precio y disponibilidad." },
  finder: { title: "Buscador de productos PRFCT10", note: "Orientación de compra, no consejo médico", close: "Cerrar buscador", step: "Paso {current} de {total}", questions: { shoppingFor: "¿Qué estás buscando?", trainingNeed: "¿Con qué necesita ayuda?", level: "¿Qué nivel le queda mejor?", levelHelp: "Esto solo ordena las sugerencias. No evalúa habilidad ni preparación." }, options: { training: "Entrenamiento", competition: "Día de competencia", cute: "Algo lindo", mind: "Gimnasia mental", apparel: "Ropa", gift: "Un regalo", barsGrip: "Barras y agarre", wristSupport: "Soporte de muñeca", strengthFlexibility: "Fuerza y flexibilidad", recoveryComfort: "Recuperación y comodidad", notSure: "No estoy segura", beginner: "Principiante", developmental: "Xcel / Desarrollo", competitive: "Competitiva" }, resultsEyebrow: "Tu selección PRFCT10", resultsTitle: "Algunas opciones pensadas para ti.", resultsText: "Según tus respuestas, estos son buenos puntos de partida. Revisa ajuste, uso y disponibilidad en cada producto.", view: "Ver producto", back: "Atrás", reset: "Empezar de nuevo", all: "Ver todos los productos", reasons: { "bar-grips": "Un esencial para barras que aporta agarre y cobertura de las palmas durante la práctica repetida.", chalk: "Un básico para mantener las manos secas y apoyar la sensación de agarre.", "sweat-wristbands": "Una opción cómoda para controlar el sudor durante sesiones largas.", "hand-balm": "Una opción práctica para manos resecas después del magnesio, barras y fricción.", "coquet-lazos-tul": "Un detalle pulido para peinados de competencia, fotos o looks coordinados.", "coquet-glitter-spray": "Un toque final rápido para cabello de competencia, fotos y momentos especiales.", "mental-squishy-dumpling": "Una opción sensorial suave para manos inquietas y pausas tranquilas.", "mental-bolita-puzzle": "Un puzzle portátil para juego enfocado, paciencia y coordinación." } },
  common: { close: "Cerrar", add: "Agregar", remove: "Eliminar", keepShopping: "Seguir comprando" }
};

export const translations = { en, es };
