import test from "node:test";
import assert from "node:assert/strict";
import { gymnastEditorialRegistry } from "../src/components/GymnastOfDay/gymnastData.js";
import { addToHall, buildShareText, createSessionSnapshot, DAILY_ATTEMPT_LIMIT, DAILY_MISSIONS, getEasternDateKey, getPublishableGymnasts, resolveGuess, restoreSessionSnapshot, scoreForClue, selectDailyGymnasts, validateCatalog, validateGymnast } from "../src/components/GymnastOfDay/gymnastEngine.js";

test("master catalog contains exactly GYM-001 through GYM-100",()=>{const result=validateCatalog(gymnastEditorialRegistry.records);assert.equal(result.valid,true,result.errors.join("\n"));});
test("batch 01 is verified and remaining 90 stay unpublished",()=>{assert.equal(getPublishableGymnasts(gymnastEditorialRegistry.records).length,10);assert.equal(gymnastEditorialRegistry.records.filter(r=>!r.review.publishable).length,90);});
test("every publishable file passes its publication gates",()=>{const ids=new Set(gymnastEditorialRegistry.records.map(r=>r.id));getPublishableGymnasts(gymnastEditorialRegistry.records).forEach(r=>assert.deepEqual(validateGymnast(r,ids),{valid:true,errors:[]}));});
test("daily mission deterministically selects five unique cleared gymnasts",()=>{const a=selectDailyGymnasts(gymnastEditorialRegistry.records,new Date("2026-09-02T16:00:00Z"));const b=selectDailyGymnasts(gymnastEditorialRegistry.records,new Date("2026-09-02T23:00:00Z"));assert.deepEqual(a.map(r=>r.id),b.map(r=>r.id));assert.equal(a.length,5);assert.equal(new Set(a.map(r=>r.id)).size,5);assert.ok(a.every(r=>r.review.publishable));});
test("New York date changes at the correct UTC boundary",()=>{assert.equal(getEasternDateKey(new Date("2026-09-02T03:30:00Z")),"2026-09-01");assert.equal(getEasternDateKey(new Date("2026-09-02T05:30:00Z")),"2026-09-02");});
test("scores are 300, 200 and 100",()=>{assert.deepEqual([1,2,3].map(scoreForClue),[300,200,100]);assert.equal(DAILY_ATTEMPT_LIMIT,10);});
test("every answer consumes one try; errors unlock clues and ten tries end the mission",()=>{let state={attempts:0,clueNumber:1};state=resolveGuess({...state,isCorrect:false});assert.deepEqual(state,{attempts:1,clueNumber:2,correct:false,score:0,exhausted:false});state=resolveGuess({...state,isCorrect:true});assert.equal(state.attempts,2);assert.equal(state.score,200);let capped={attempts:9,clueNumber:3};capped=resolveGuess({...capped,isCorrect:false});assert.equal(capped.attempts,10);assert.equal(capped.exhausted,true);});
test("two balanced five-file missions are defined without duplicate order",()=>{assert.equal(DAILY_MISSIONS.length,2);DAILY_MISSIONS.forEach(ids=>{assert.equal(ids.length,5);assert.equal(new Set(ids).size,5);const records=ids.map(id=>gymnastEditorialRegistry.records.find(r=>r.id===id));assert.ok(records.some(r=>r.game.difficulty==="ACCESSIBLE"));assert.ok(records.some(r=>r.game.difficulty==="EXPERT"));assert.ok(new Set(records.flatMap(r=>r.classification.featuredEvents)).size>=3);});assert.notDeepEqual(DAILY_MISSIONS[0],DAILY_MISSIONS[1]);});
test("discarded answer state and mid-mission progress survive JSON reload",()=>{const athlete=getPublishableGymnasts(gymnastEditorialRegistry.records)[0];const snapshot=createSessionSnapshot({dateKey:"2026-09-02",phase:"clues",round:2,clueNumber:2,attempts:4,wrongIds:["GYM-002"],elapsed:9,solved:[{gymnast:athlete,score:300,clues:1}]});const parsed=JSON.parse(JSON.stringify(snapshot));const byId=Object.fromEntries(gymnastEditorialRegistry.records.map(r=>[r.id,r]));const restored=restoreSessionSnapshot(parsed,byId,"2026-09-02");assert.equal(restored.attempts,4);assert.deepEqual(restored.wrongIds,["GYM-002"]);assert.equal(restored.solved[0].gymnast.id,athlete.id);assert.equal(restoreSessionSnapshot(parsed,byId,"2026-09-03"),null);});
test("published clues have direct evidence and do not open with country giveaways",()=>{const forbidden=/\b(represent|represento|country|país|united states|estados unidos|brazil|brasil|china|mexico|méxico|romania|rumania|russia|rusia|algeria|argelia)\b/i;getPublishableGymnasts(gymnastEditorialRegistry.records).forEach(r=>{assert.equal(forbidden.test(r.game.clues.en[0]),false,`${r.id} EN clue 1`);assert.equal(forbidden.test(r.game.clues.es[0]),false,`${r.id} ES clue 1`);assert.equal(r.game.clueSourceUrls.length,3);r.game.clueSourceUrls.forEach(url=>assert.ok(r.sources.some(source=>source.url===url)));});});
test("distractors are unique, real and frequency-controlled",()=>{const published=getPublishableGymnasts(gymnastEditorialRegistry.records);const ids=new Set(gymnastEditorialRegistry.records.map(r=>r.id));const counts={};published.forEach(r=>{assert.equal(new Set(r.game.distractorGymnastIds).size,3);assert.equal(r.game.distractorGymnastIds.includes(r.id),false);assert.ok(r.game.distractorRationale.length>40);r.game.distractorGymnastIds.forEach(id=>{assert.ok(ids.has(id));counts[id]=(counts[id]||0)+1;});});assert.ok(Math.max(...Object.values(counts))<=5);});
test("Hall keeps one record and the best score",()=>{const athlete=getPublishableGymnasts(gymnastEditorialRegistry.records)[0];const once=addToHall([],athlete,200,"focus","2026-09-01");const twice=addToHall(once,athlete,100,"team","2026-09-02");assert.equal(twice.length,1);assert.equal(twice[0].bestScore,200);});
test("share result is spoiler free",()=>{const share=buildShareText({score:900,solvedCount:5,attemptsUsed:8,streak:2,locale:"en"});getPublishableGymnasts(gymnastEditorialRegistry.records).forEach(r=>assert.equal(share.includes(r.identity.visibleName),false));});
test("beam element 6.805 never contains a piked alternative",()=>{gymnastEditorialRegistry.records.forEach(r=>{if(r.element.figElementNumber==="6.805"){const value=JSON.stringify(r.element.officialDescription).toLowerCase();assert.equal(value.includes("piked"),false);assert.equal(value.includes("carpado"),false);}});});
