// Generated from the owner-supplied V1 content brief. Edit the source brief and rerun the generator for bulk changes.
export const TRUTHS = [
  {
    "id": "t001",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which skill do you say you “just don’t like”… but actually scares you?"
  },
  {
    "id": "t002",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What correction does your coach say so often you hear it in your sleep?"
  },
  {
    "id": "t003",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever pretended not to hear the word “conditioning”?"
  },
  {
    "id": "t004",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What skill have you avoided doing just because you were having a bad day?"
  },
  {
    "id": "t005",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever blamed your grips when it was definitely not your grips?"
  },
  {
    "id": "t006",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What skill looked easy until you actually tried it?"
  },
  {
    "id": "t007",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something in gymnastics you thought you’d NEVER be able to do?"
  },
  {
    "id": "t008",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever said “I’m fine” when you were absolutely not fine?"
  },
  {
    "id": "t009",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the longest you’ve ever stared at an apparatus before finally going?"
  },
  {
    "id": "t010",
    "type": "truth",
    "category": "gym_confessions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever secretly hoped practice would get canceled?"
  },
  {
    "id": "t011",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If one apparatus disappeared for a week, which one would you choose?"
  },
  {
    "id": "t012",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which apparatus do you trust the least?"
  },
  {
    "id": "t013",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which apparatus makes you feel the coolest?"
  },
  {
    "id": "t014",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which apparatus has personally offended you the most?"
  },
  {
    "id": "t015",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could only train one event for a month, which would you pick?"
  },
  {
    "id": "t016",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which event is the most dramatic?"
  },
  {
    "id": "t017",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which event has the best feeling when everything goes right?"
  },
  {
    "id": "t018",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which event has the worst warm-ups?"
  },
  {
    "id": "t019",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which event would you choose if Olympic gold depended on one routine?"
  },
  {
    "id": "t020",
    "type": "truth",
    "category": "apparatus_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What apparatus do you think understands you the least?"
  },
  {
    "id": "t021",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Do you look at your score immediately or pretend you don’t care?"
  },
  {
    "id": "t022",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What event do you want first in a meet rotation?"
  },
  {
    "id": "t023",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What event do you want last?"
  },
  {
    "id": "t024",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s your weirdest meet-day habit?"
  },
  {
    "id": "t025",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever forgotten choreography during a competition?"
  },
  {
    "id": "t026",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the most random thing you’ve thought about while waiting to compete?"
  },
  {
    "id": "t027",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What part of meet day makes you the most nervous?"
  },
  {
    "id": "t028",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the best snack after a meet?"
  },
  {
    "id": "t029",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever smiled at a judge while internally panicking?"
  },
  {
    "id": "t030",
    "type": "truth",
    "category": "meet_day",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Would you rather compete first or last?"
  },
  {
    "id": "t031",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who on your team always knows what rotation you’re on?"
  },
  {
    "id": "t032",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who would survive the longest if the team got stuck in an airport?"
  },
  {
    "id": "t033",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who is most likely to have extra tape?"
  },
  {
    "id": "t034",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who is most likely to know everyone’s scores before anyone else?"
  },
  {
    "id": "t035",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who gives the best pep talks?"
  },
  {
    "id": "t036",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who is most likely to make everyone laugh during stretching?"
  },
  {
    "id": "t037",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who would make the best gymnastics commentator?"
  },
  {
    "id": "t038",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who would accidentally become the team spokesperson?"
  },
  {
    "id": "t039",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Who is most likely to pack snacks for everyone?"
  },
  {
    "id": "t040",
    "type": "truth",
    "category": "team_tea",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something your team says that makes zero sense to outsiders?"
  },
  {
    "id": "t041",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What is your coach’s most-used phrase?"
  },
  {
    "id": "t042",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What correction makes you instantly know exactly what they mean?"
  },
  {
    "id": "t043",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the funniest thing a coach has ever said at practice?"
  },
  {
    "id": "t044",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which is scarier: “one more” or “come here for a second”?"
  },
  {
    "id": "t045",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What does your coach say right before something difficult?"
  },
  {
    "id": "t046",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s one correction you used to hate but now understand?"
  },
  {
    "id": "t047",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever heard your coach say “last one” and not believed them?"
  },
  {
    "id": "t048",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the most coach-like phrase you’ve caught yourself saying?"
  },
  {
    "id": "t049",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you coached for one day, what would your first rule be?"
  },
  {
    "id": "t050",
    "type": "truth",
    "category": "coach_moments",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Would you rather have a super quiet coach or a super loud coach?"
  },
  {
    "id": "t051",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which is more satisfying: a huge skill or a perfect stick?"
  },
  {
    "id": "t052",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics skill is overrated?"
  },
  {
    "id": "t053",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics skill deserves more respect?"
  },
  {
    "id": "t054",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which is worse: a beam wobble or a floor step out of bounds?"
  },
  {
    "id": "t055",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Would you rather have amazing flexibility or ridiculous power?"
  },
  {
    "id": "t056",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Would you rather have beautiful lines or huge difficulty?"
  },
  {
    "id": "t057",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics trend should disappear forever?"
  },
  {
    "id": "t058",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics trend needs to come back?"
  },
  {
    "id": "t059",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What makes a routine unforgettable?"
  },
  {
    "id": "t060",
    "type": "truth",
    "category": "gym_opinions",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Which matters more to you: competing well or placing well?"
  },
  {
    "id": "t061",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could instantly learn one skill, what would it be?"
  },
  {
    "id": "t062",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What skill would you want named after you?"
  },
  {
    "id": "t063",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could train with any gymnast for one day, who would it be?"
  },
  {
    "id": "t064",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could compete at any Olympics in history, which one would you choose?"
  },
  {
    "id": "t065",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What would your dream floor music be?"
  },
  {
    "id": "t066",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What colors would your dream competition leo use?"
  },
  {
    "id": "t067",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could design a fifth women’s event, what would it be?"
  },
  {
    "id": "t068",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If you could compete in any arena in the world, where would you choose?"
  },
  {
    "id": "t069",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Would you rather invent a skill or win a major title?"
  },
  {
    "id": "t070",
    "type": "truth",
    "category": "dream_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What would your signature finishing pose look like?"
  },
  {
    "id": "t071",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What is the most gymnast thing you do outside the gym?"
  },
  {
    "id": "t072",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever tested whether you could handstand somewhere you absolutely did not need to?"
  },
  {
    "id": "t073",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "How many hair ties is “too many” hair ties?"
  },
  {
    "id": "t074",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What item in your gym bag could you absolutely not live without?"
  },
  {
    "id": "t075",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the weirdest place you’ve ever found chalk?"
  },
  {
    "id": "t076",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s the first thing you notice when you walk into a new gym?"
  },
  {
    "id": "t077",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics word do non-gymnasts never understand?"
  },
  {
    "id": "t078",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something normal people think is impressive that gymnasts think is completely normal?"
  },
  {
    "id": "t079",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something gymnasts think is normal that sounds insane to everyone else?"
  },
  {
    "id": "t080",
    "type": "truth",
    "category": "gym_culture",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s your strongest “you know you’re a gymnast when…” moment?"
  },
  {
    "id": "t081",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever practiced your salute in a mirror?"
  },
  {
    "id": "t082",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever celebrated a stick before remembering the rest of the routine?"
  },
  {
    "id": "t083",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever forgotten which turn it was at practice?"
  },
  {
    "id": "t084",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever waited for someone else to go first because you were nervous?"
  },
  {
    "id": "t085",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever secretly loved a conditioning station everyone else hated?"
  },
  {
    "id": "t086",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever pretended a correction wasn’t for you?"
  },
  {
    "id": "t087",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever watched your own routine more than ten times?"
  },
  {
    "id": "t088",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever argued with a score in your head for way too long?"
  },
  {
    "id": "t089",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever packed your gym bag and still forgotten the most important thing?"
  },
  {
    "id": "t090",
    "type": "truth",
    "category": "wait_be_honest",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Have you ever made eye contact with a teammate mid-routine and almost laughed?"
  },
  {
    "id": "t091",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics moment are you most proud of?"
  },
  {
    "id": "t092",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What skill taught you the most patience?"
  },
  {
    "id": "t093",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What part of gymnastics has made you mentally stronger?"
  },
  {
    "id": "t094",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something younger-you would be shocked you can do now?"
  },
  {
    "id": "t095",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What gymnastics goal matters most to you right now?"
  },
  {
    "id": "t096",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s something you want to be remembered for as a teammate?"
  },
  {
    "id": "t097",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s one thing gymnastics taught you that has nothing to do with gymnastics?"
  },
  {
    "id": "t098",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "What’s one skill you wish you could learn again for the first time?"
  },
  {
    "id": "t099",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "If your gymnastics life had a movie title, what would it be?"
  },
  {
    "id": "t100",
    "type": "truth",
    "category": "big_questions_still_fun",
    "intensity": "spicy",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Finish the sentence: Gymnastics would be easier if ________."
  }
];
export const DARES = [
  {
    "id": "d001",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out your coach saying “one more” without using the words “one more.”"
  },
  {
    "id": "d002",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Show your most dramatic “I definitely meant to do that” landing face."
  },
  {
    "id": "d003",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out waiting for a beam score like it’s the final scene of a movie."
  },
  {
    "id": "d004",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Pretend your floor music stopped halfway through your routine."
  },
  {
    "id": "d005",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out discovering a rip on bars."
  },
  {
    "id": "d006",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out a giant beam wobble without standing on anything."
  },
  {
    "id": "d007",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Pretend you just stuck the hardest routine of your life."
  },
  {
    "id": "d008",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out realizing conditioning is not over."
  },
  {
    "id": "d009",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Act out a gymnast who forgot where she is in her floor routine."
  },
  {
    "id": "d010",
    "type": "dare",
    "category": "act_it_out",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Pretend you just heard your coach say, “We need to talk.”"
  },
  {
    "id": "d011",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": 15,
    "prompt": "You just won Olympic gold for putting your hair in a bun. Give your 15-second victory interview."
  },
  {
    "id": "d012",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You just won Worlds for Best Cartwheel in the Living Room. Thank your supporters."
  },
  {
    "id": "d013",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Reporters want to know why you used so much chalk. Defend yourself."
  },
  {
    "id": "d014",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You just scored a perfect 10 for opening a snack. Explain your technique."
  },
  {
    "id": "d015",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You have been accused of excessive saluting. Respond to the media."
  },
  {
    "id": "d016",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You just became world champion in finding lost hair ties. Give your speech."
  },
  {
    "id": "d017",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You won gold after the longest warm-up ever. Describe the journey."
  },
  {
    "id": "d018",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You just retired from beam forever. Announce your decision."
  },
  {
    "id": "d019",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You are making a comeback to beam 30 seconds later. Explain why."
  },
  {
    "id": "d020",
    "type": "dare",
    "category": "press_conference",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "You have just been named Captain of the Couch Gymnastics Team. Address the nation."
  },
  {
    "id": "d021",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Coach someone through sitting on the couch like it’s an elite gymnastics skill."
  },
  {
    "id": "d022",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Teach someone how to open a bag of chips using full gymnastics-coach vocabulary."
  },
  {
    "id": "d023",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Give someone three corrections on how they walked across the room."
  },
  {
    "id": "d024",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Say “point your toes” in your best coach voice."
  },
  {
    "id": "d025",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Coach someone through picking up a water bottle."
  },
  {
    "id": "d026",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Give a motivational speech before someone eats a snack."
  },
  {
    "id": "d027",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain how to stand still like you are coaching an Olympic final."
  },
  {
    "id": "d028",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Give a correction using only hand gestures."
  },
  {
    "id": "d029",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Coach the entire group through one perfect salute."
  },
  {
    "id": "d030",
    "type": "dare",
    "category": "coach_mode",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent the most coach-like sentence possible."
  },
  {
    "id": "d031",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Announce someone walking across the room like it’s an Olympic beam final."
  },
  {
    "id": "d032",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Commentate someone tying their shoe like it’s the final rotation."
  },
  {
    "id": "d033",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Give dramatic play-by-play while someone drinks water."
  },
  {
    "id": "d034",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Announce someone sitting down as if they just stuck a vault."
  },
  {
    "id": "d035",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": 10,
    "prompt": "Give a 10-second gymnastics commentary about absolutely nothing."
  },
  {
    "id": "d036",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Describe a teammate’s hairstyle using elite gymnastics terminology."
  },
  {
    "id": "d037",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Announce someone entering the room like they are the reigning world champion."
  },
  {
    "id": "d038",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Commentate someone passing the phone."
  },
  {
    "id": "d039",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Give an imaginary score for someone’s best salute and explain the deductions."
  },
  {
    "id": "d040",
    "type": "dare",
    "category": "commentator_mode",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": 10,
    "prompt": "Call the final ten seconds of an imaginary Olympic floor routine."
  },
  {
    "id": "d041",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": 10,
    "prompt": "Hold your most dramatic finishing pose for 10 seconds."
  },
  {
    "id": "d042",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Stand on one foot while naming five gymnastics skills."
  },
  {
    "id": "d043",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Walk heel-to-toe across a safe clear section of floor."
  },
  {
    "id": "d044",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Hold a passé while someone asks you three random questions."
  },
  {
    "id": "d045",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Create a three-pose floor routine with no tumbling."
  },
  {
    "id": "d046",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": 15,
    "prompt": "Balance a scrunchie on your head for 15 seconds."
  },
  {
    "id": "d047",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Do your best slow-motion salute."
  },
  {
    "id": "d048",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Create the most dramatic starting pose you can."
  },
  {
    "id": "d049",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Freeze in a gymnastics pose until your next turn."
  },
  {
    "id": "d050",
    "type": "dare",
    "category": "safe_movement",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "low",
    "timer": null,
    "prompt": "Take five normal steps across the room but make them look like floor choreography."
  },
  {
    "id": "d051",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime chalking up. The group has to guess what you’re doing."
  },
  {
    "id": "d052",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime waiting for your score."
  },
  {
    "id": "d053",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime a stuck landing."
  },
  {
    "id": "d054",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime putting on grips."
  },
  {
    "id": "d055",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime a gymnast hearing “conditioning.”"
  },
  {
    "id": "d056",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime forgetting floor choreography."
  },
  {
    "id": "d057",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime a coach spotting a skill without touching anyone."
  },
  {
    "id": "d058",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime a gymnast walking onto beam for the first time."
  },
  {
    "id": "d059",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime trying to remove tape after practice."
  },
  {
    "id": "d060",
    "type": "dare",
    "category": "gym_charades",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Mime realizing your floor music is about to start."
  },
  {
    "id": "d061",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a Yurchenko without saying: vault, round-off, handspring."
  },
  {
    "id": "d062",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a giant without saying: bars, circle, swing."
  },
  {
    "id": "d063",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a beam routine without saying: beam, balance, routine."
  },
  {
    "id": "d064",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a kip without saying: bars, glide, pull."
  },
  {
    "id": "d065",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain chalk without saying: white, powder, hands."
  },
  {
    "id": "d066",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a wolf turn without saying: turn, leg, floor."
  },
  {
    "id": "d067",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a stuck landing without saying: feet, move, landing."
  },
  {
    "id": "d068",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a leo without saying: gymnastics, outfit, wear."
  },
  {
    "id": "d069",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain grips without saying: bars, hands, leather."
  },
  {
    "id": "d070",
    "type": "dare",
    "category": "explain_it_badly",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Explain a judge without saying: score, deduction, routine."
  },
  {
    "id": "d071",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": 5,
    "prompt": "Name three beam skills in five seconds."
  },
  {
    "id": "d072",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three things coaches say."
  },
  {
    "id": "d073",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three things inside a gym bag."
  },
  {
    "id": "d074",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three gymnastics deductions."
  },
  {
    "id": "d075",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three famous gymnasts."
  },
  {
    "id": "d076",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three things covered in chalk."
  },
  {
    "id": "d077",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three floor skills."
  },
  {
    "id": "d078",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three things that happen on meet day."
  },
  {
    "id": "d079",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three reasons a gymnast says “I’m fine.”"
  },
  {
    "id": "d080",
    "type": "dare",
    "category": "5_second_gym",
    "intensity": "chill",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Name three things you absolutely do not want to forget at a competition."
  },
  {
    "id": "d081",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent a new gymnastics skill and give it a ridiculous name."
  },
  {
    "id": "d082",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent a new apparatus for women’s gymnastics."
  },
  {
    "id": "d083",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Create a brand-new deduction that should exist."
  },
  {
    "id": "d084",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent a gymnastics-themed perfume and describe its scent."
  },
  {
    "id": "d085",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Create the worst floor-music title imaginable."
  },
  {
    "id": "d086",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent a new meet award nobody asked for."
  },
  {
    "id": "d087",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Design a fake Olympic event using two gymnastics apparatuses."
  },
  {
    "id": "d088",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent a gymnastics holiday and explain how it is celebrated."
  },
  {
    "id": "d089",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Create a fake gymnastics movie title."
  },
  {
    "id": "d090",
    "type": "dare",
    "category": "creative_chaos",
    "intensity": "chaos",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Invent the most ridiculous team motto possible."
  },
  {
    "id": "d091",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Everyone gives their best salute. Pick the most dramatic one."
  },
  {
    "id": "d092",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Everyone freezes in a gymnastics pose. Last person to move loses."
  },
  {
    "id": "d093",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": 10,
    "prompt": "Create a team photo pose in 10 seconds."
  },
  {
    "id": "d094",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Everyone says “STICK!” at exactly the same time."
  },
  {
    "id": "d095",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Everyone takes turns saying one thing a coach says. First person who repeats one loses."
  },
  {
    "id": "d096",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Create a four-count floor choreography together."
  },
  {
    "id": "d097",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": 10,
    "prompt": "Everyone chooses an apparatus. No two players can pick the same one. Solve it in 10 seconds."
  },
  {
    "id": "d098",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "The group must invent one new gymnastics skill together."
  },
  {
    "id": "d099",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": null,
    "prompt": "Everyone gives their best fake Olympic reaction. Vote for the winner."
  },
  {
    "id": "d100",
    "type": "dare",
    "category": "team_dares",
    "intensity": "team",
    "minPlayers": 2,
    "physical": "none",
    "timer": 20,
    "prompt": "Create your team’s official locker-room handshake in 20 seconds."
  }
];
export const CHAOS_CARDS = [
  {
    "id": "c001",
    "type": "chaos",
    "category": "group",
    "title": "COACH MODE",
    "prompt": "For the next round, everyone must talk like a gymnastics coach.",
    "completionText": "Chest up. Obviously.",
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c002",
    "type": "chaos",
    "category": "group",
    "title": "TEAM FINAL",
    "prompt": "Everyone answers the next Truth.",
    "completionText": "Three up. Three count. Emotionally.",
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c003",
    "type": "chaos",
    "category": "group",
    "title": "SALUTE CHECK",
    "prompt": "Everyone salute. The group has five seconds to pick the winner.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c004",
    "type": "chaos",
    "category": "group",
    "title": "ROTATION CHANGE",
    "prompt": "Everyone switches seats. Continue the game from the new order.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c005",
    "type": "chaos",
    "category": "group",
    "title": "INQUIRY!",
    "prompt": "Choose one player. They may replace the next card they receive.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c006",
    "type": "chaos",
    "category": "group",
    "title": "STICK IT",
    "prompt": "Everyone freezes in their best finish position. Last person to move loses one swap.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c007",
    "type": "chaos",
    "category": "group",
    "title": "NO GYM WORDS",
    "prompt": "For the next round nobody may say: gymnastics coach beam",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c008",
    "type": "chaos",
    "category": "group",
    "title": "JUDGE MODE",
    "prompt": "For the next dare, the group must give the performance a completely fake score.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c009",
    "type": "chaos",
    "category": "group",
    "title": "TEAM CAPTAIN",
    "prompt": "Choose a captain. The captain decides who plays next.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c010",
    "type": "chaos",
    "category": "group",
    "title": "WRONG EVENT",
    "prompt": "For the next card, every answer must somehow include the wrong apparatus.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c011",
    "type": "chaos",
    "category": "group",
    "title": "COMMENTATOR MODE",
    "prompt": "One player must commentate the entire next turn.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c012",
    "type": "chaos",
    "category": "group",
    "title": "MIRROR MODE",
    "prompt": "For the next 20 seconds, everyone must copy the player to their left.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c013",
    "type": "chaos",
    "category": "group",
    "title": "ONE MORE",
    "prompt": "The previous player gets another turn immediately.",
    "completionText": "Your coach taught us this.",
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c014",
    "type": "chaos",
    "category": "group",
    "title": "FLOOR FACE",
    "prompt": "Everyone gives their best competition floor expression. No laughing. Good luck.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c015",
    "type": "chaos",
    "category": "group",
    "title": "CHALK CLOUD",
    "prompt": "Everyone points to the person most likely to get chalk somewhere impossible. 3… 2… 1… POINT.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c016",
    "type": "chaos",
    "category": "group",
    "title": "BEAM SILENCE",
    "prompt": "Nobody may speak during the next player’s card reveal.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c017",
    "type": "chaos",
    "category": "group",
    "title": "SWITCH EVENTS",
    "prompt": "Everyone announces the apparatus they would compete right now. Anyone who picks the same event must negotiate.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c018",
    "type": "chaos",
    "category": "group",
    "title": "TEAM HUDDLE",
    "prompt": "You have 15 seconds to create the worst motivational chant ever.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c019",
    "type": "chaos",
    "category": "group",
    "title": "SCOREBOARD",
    "prompt": "The group gives the previous performance a score between: 0.000 and 10.000 Drama encouraged.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c020",
    "type": "chaos",
    "category": "group",
    "title": "NO NAMES",
    "prompt": "For one full round, nobody can call another player by their name.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c021",
    "type": "chaos",
    "category": "group",
    "title": "GYM MOM MODE",
    "prompt": "For the next turn, one player must react like an extremely excited gym parent.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c022",
    "type": "chaos",
    "category": "group",
    "title": "THE FLOOR IS WATCHING",
    "prompt": "Everyone must sit in their best “waiting for awards” posture until the next turn ends.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c023",
    "type": "chaos",
    "category": "group",
    "title": "PASS IT BACK",
    "prompt": "Reverse the player order.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c024",
    "type": "chaos",
    "category": "group",
    "title": "LOCKER SECRET",
    "prompt": "Everyone answers: What item is ALWAYS in your gym bag? Quick answers only.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c025",
    "type": "chaos",
    "category": "group",
    "title": "FIVE SECOND WARNING",
    "prompt": "The next Truth must be answered in five seconds. No overthinking.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c026",
    "type": "chaos",
    "category": "group",
    "title": "NO DEDUCTIONS",
    "prompt": "The next dare automatically receives a perfect score. Regardless of what happens.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c027",
    "type": "chaos",
    "category": "group",
    "title": "TEAMMATE SAVE",
    "prompt": "Choose another player. They receive one extra swap.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c028",
    "type": "chaos",
    "category": "group",
    "title": "APPARATUS WAR",
    "prompt": "Everyone points to the best apparatus. Anyone in the minority has 10 seconds to defend their choice.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c029",
    "type": "chaos",
    "category": "group",
    "title": "OLYMPIC FACE",
    "prompt": "Everyone react as if they just won Olympic gold. Most believable wins absolutely nothing.",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  },
  {
    "id": "c030",
    "type": "chaos",
    "category": "group",
    "title": "LOCKER ROOM RULE",
    "prompt": "The entire group says together: “What happens in the locker room…” Then the app finishes: “…becomes a PRFCT10 story.”",
    "completionText": null,
    "minPlayers": 2,
    "physical": "low",
    "timer": null
  }
];
export const MICRO_REACTIONS = [
  "The beam already knew.",
  "That stays in the locker room.",
  "No judges were consulted.",
  "Your coach has entered the chat.",
  "We heard absolutely nothing.",
  "No names were mentioned.",
  "Bold choice.",
  "The locker room approves.",
  "Historic performance.",
  "No deductions. Somehow.",
  "That deserved a salute.",
  "The judges are outside. Relax.",
  "Gymnasts know.",
  "Your teammate will remember this forever.",
  "We said what we said.",
  "That got suspiciously specific.",
  "Interesting. Very interesting.",
  "The group chat would explode.",
  "Beam denies everything.",
  "Your grips have requested legal counsel.",
  "Respectfully… accurate.",
  "That answer had floor energy.",
  "Vault girls understood immediately.",
  "Bars would like a rebuttal.",
  "We’re not writing that on the score sheet.",
  "The inquiry has been denied.",
  "The inquiry has been accepted. Emotionally.",
  "Someone had to say it.",
  "That felt personal.",
  "No further questions.",
  "The locker door is closing now.",
  "Your coach definitely felt that somehow.",
  "Team secret unlocked.",
  "Well… that happened.",
  "Excellent form. Questionable judgment.",
  "The judges gave it vibes.",
  "We support this level of chaos.",
  "Noted for your future documentary.",
  "The team has spoken.",
  "PASS. THE. PHONE."
];
