import {useRef,useState} from 'react';
import {resolveBowracleSecretCode} from './secretCodes.js';
import {createSecretReading} from './readingEngine.js';

export function NameField({value,onChange,t,id='bt-first-name',hint,placeholder=''}){return <div className="bt-name"><label htmlFor={id}>{t('bowracle.tarot.optionalName')}</label><input id={id} value={value} onChange={e=>onChange(e.target.value)} maxLength={30} autoComplete="off" aria-describedby={id+'-hint'} placeholder={placeholder}/><p id={id+'-hint'}>{hint||t('bowracle.tarot.nameHint')}</p></div>;}

function localDate(){const d=new Date(),two=value=>String(value).padStart(2,'0');return `${d.getFullYear()}-${two(d.getMonth()+1)}-${two(d.getDate())}`;}

function GroveSigil(){return <svg className="bt-grove-sigil" viewBox="0 0 360 430" aria-hidden="true"><defs><linearGradient id="groveGlow" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#ffe9bd"/><stop offset=".48" stopColor="#f4b8d1"/><stop offset="1" stopColor="#9de1de"/></linearGradient></defs><path className="bt-grove-arch" d="M54 398V188C54 90 107 35 180 35s126 55 126 153v210"/><path className="bt-grove-vine" d="M58 357C24 319 38 273 74 257C30 235 43 184 87 172C50 128 88 79 129 99M302 357c34-38 20-84-16-100c44-22 31-73-13-85c37-44-1-93-42-73"/><g fill="url(#groveGlow)" stroke="#fff6e8" strokeWidth="2"><path d="M180 154c-34-38-84-28-91 17c-8 50 52 68 91 101c39-33 99-51 91-101c-7-45-57-55-91-17Z"/><path d="M180 190c-18-20-44-15-48 9c-4 26 28 36 48 53c20-17 52-27 48-53c-4-24-30-29-48-9Z"/></g><path className="bt-grove-ribbon" d="M95 214c-41 17-55 52-49 92c39-5 74-20 98-49M265 214c41 17 55 52 49 92c-39-5-74-20-98-49"/><circle cx="180" cy="225" r="23" fill="#f8e7a6" stroke="#fff8ed" strokeWidth="4"/><g className="bt-grove-stars" fill="#fff3c7"><circle cx="98" cy="135" r="3"/><circle cx="270" cy="146" r="4"/><circle cx="78" cy="300" r="3"/><circle cx="286" cy="286" r="2"/><path d="M180 73l4 10l10 4l-10 4l-4 10l-4-10l-10-4l10-4Z"/></g><g className="bt-grove-butterflies" fill="none" stroke="#f6d8ee" strokeWidth="3"><path d="M92 220c-14-19-31-9-24 7c-14 10 3 25 24 3c21 22 38 7 24-3c7-16-10-26-24-7Z"/><path d="M274 210c-11-15-25-7-19 6c-12 8 2 20 19 2c17 18 31 6 19-2c6-13-8-21-19-6Z"/></g></svg>}

export default function SecretCodeForm({t,name,onName,onReveal}){
 const [code,setCode]=useState(''),[date,setDate]=useState(localDate),[demo,setDemo]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 async function submit(e){e.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{const resolved=await resolveBowracleSecretCode(code,{demo});if(!resolved.valid){setError(resolved.reason);return;}const result=createSecretReading(resolved);if(!result){setError('invalid');return;}onReveal({...result,secretDate:date});}finally{lock.current=false;setBusy(false);}}
 return <section className="bt-secret-grove" aria-labelledby="bt-grove-title"><div className="bt-grove-world" aria-hidden="true"><span className="bt-grove-moon"/><span className="bt-grove-mist bt-grove-mist--one"/><span className="bt-grove-mist bt-grove-mist--two"/>{Array.from({length:16},(_,i)=><i className="bt-firefly" style={{'--i':i,left:`${3+(i*37)%94}%`,top:`${8+(i*53)%84}%`}} key={i}/>)}<b className="bt-butterfly bt-butterfly--one">⋈</b><b className="bt-butterfly bt-butterfly--two">⋈</b><b className="bt-dragonfly">✣</b></div>
  <header className="bt-grove-hero"><div className="bt-grove-copy"><p className="br-kicker">{t('bowracle.tarot.groveEyebrow')}</p><h1 id="bt-grove-title">{t('bowracle.tarot.groveTitle')}</h1><p>{t('bowracle.tarot.groveIntro')}</p><blockquote>{t('bowracle.tarot.groveWhisper')}</blockquote></div><div className="bt-grove-gate"><GroveSigil/><span>{t('bowracle.tarot.groveGate')}</span></div></header>
  <form className="bt-grove-registry" onSubmit={submit}><div className="bt-grove-registry__heading"><span>01 / {t('bowracle.tarot.groveRegistry')}</span><h2>{t('bowracle.tarot.groveFormTitle')}</h2><p>{t('bowracle.tarot.groveFormIntro')}</p></div><div className="bt-grove-fields"><NameField value={name} onChange={onName} t={t} hint={t('bowracle.tarot.groveNameHint')} placeholder={t('bowracle.tarot.groveNamePlaceholder')}/><div className="bt-grove-field"><label htmlFor="bt-secret-date">{t('bowracle.tarot.groveDate')}</label><input id="bt-secret-date" type="date" value={date} onChange={e=>setDate(e.target.value)} required/><p>{t('bowracle.tarot.groveDateHint')}</p></div><div className="bt-grove-field bt-grove-field--code"><label htmlFor="bt-code">{t('bowracle.tarot.secretCode')}</label><input id="bt-code" required maxLength={40} value={code} onChange={e=>{setCode(e.target.value);setError('');}} autoComplete="off" autoCapitalize="characters" spellCheck={false} placeholder="BWR-·····" aria-invalid={!!error} aria-describedby="bt-code-status bt-demo-note"/><p>{t('bowracle.tarot.groveCodeHint')}</p></div></div>
  <div className="bt-grove-demo"><label className="bt-demo-toggle"><input type="checkbox" checked={demo} onChange={e=>{setDemo(e.target.checked);setError('');}}/><span><b>{t('bowracle.tarot.demo')}</b><small>{t('bowracle.tarot.groveDemoHint')}</small></span></label><p id="bt-demo-note" className="bt-footnote">{t('bowracle.tarot.demoNote')}{demo&&<span className="bt-demo-example">{t('bowracle.tarot.demoExample')}</span>}</p></div>
  <div className="bt-grove-invocation"><p id="bt-code-status" role="alert">{error&&t('bowracle.tarot.'+error)}</p><button className="br-button bt-grove-cta" disabled={busy} type="submit"><span>{t('bowracle.tarot.'+(busy?'checking':'groveUnlock'))}</span><b aria-hidden="true">✦</b></button><small>{t('bowracle.tarot.groveClosing')}</small></div></form>
 </section>;
}
