const make = (index, category, en, es, format = "observation") => ({
  id: `gym-lol-${String(index + 1).padStart(3, "0")}`,
  category,
  format,
  lines: {
    en: en.split("|").map((text, line) => ({ text: text.replace(/^\*/, ""), emphasis: text.startsWith("*") || line === en.split("|").length - 1 })),
    es: es.split("|").map((text, line) => ({ text: text.replace(/^\*/, ""), emphasis: text.startsWith("*") || line === es.split("|").length - 1 }))
  }
});

const rawJokes = [
  ["coaches", 'Coach: “One more.”|Gymnast:|*“You said that four one-mores ago.”', 'Entrenadora: «Una más».|Gimnasta:|*«Dijiste eso hace cuatro “una más”».', "dialogue"],
  ["beam", "My beam routine and I are currently|*NOT ON SPEAKING TERMS.", "Mi rutina de viga y yo actualmente|*NO NOS HABLAMOS."],
  ["gymnast_brain", 'Coach: “Don’t overthink it.”|My brain on beam:|*EXCELLENT. HERE ARE 47 THOUGHTS.', 'Entrenadora: «No lo pienses tanto».|Mi cerebro en la viga:|*EXCELENTE. AQUÍ TIENES 47 PENSAMIENTOS.', "dialogue"],
  ["beam", "Why did the gymnast break up with beam?|*TOO MANY TRUST ISSUES.", "¿Por qué la gimnasta terminó con la viga?|*DEMASIADOS PROBLEMAS DE CONFIANZA.", "question"],
  ["beam", "I don’t fall off beam.|I simply make|*UNEXPECTED TRAVEL ARRANGEMENTS.", "Yo no me caigo de la viga.|Simplemente hago|*PLANES DE VIAJE INESPERADOS.", "deadpan"],
  ["beam", 'Beam said, “Trust me.”|*THAT WAS THE FIRST RED FLAG.', 'La viga dijo: «Confía en mí».|*ESA FUE LA PRIMERA SEÑAL DE ALERTA.', "deadpan"],
  ["beam", "My confidence before beam: 10/10.|My confidence after mounting:|*WHO AUTHORIZED THIS?", "Mi confianza antes de viga: 10/10.|Mi confianza después de subir:|*¿QUIÉN AUTORIZÓ ESTO?"],
  ["gym_life", 'Gymnastics is 10% talent|and 90% saying:|*“I’M FINE.”', 'La gimnasia es 10% talento|y 90% decir:|*«ESTOY BIEN».', "definition"],
  ["coaches", 'Coach: “Take the mat away.”|*AND SUDDENLY EVERYONE DISCOVERS RELIGION.', 'Entrenadora: «Quita la colchoneta».|*Y DE REPENTE TODAS DESCUBREN LA RELIGIÓN.', "dialogue"],
  ["coaches", "What’s the scariest sentence in gymnastics?|*“OKAY. NOW WITHOUT THE SPOT.”", "¿Cuál es la frase más aterradora de la gimnasia?|*«BIEN. AHORA SIN AYUDA»." , "question"],
  ["coaches", 'Coach: “Easy practice today.”|Gymnasts:|*SOMETHING TERRIBLE IS ABOUT TO HAPPEN.', 'Entrenadora: «Hoy será suave».|Gimnastas:|*ALGO TERRIBLE ESTÁ POR PASAR.', "dialogue"],
  ["coaches", "Gymnastics math:|*ONE MORE × 7|= GOING HOME LATE", "Matemática gimnástica:|*UNA MÁS × 7|= SALIR TARDE", "definition"],
  ["coaches", "My coach says I need more confidence.|I say I need|*A BIGGER MAT.", "Mi entrenadora dice que necesito más confianza.|Yo digo que necesito|*UNA COLCHONETA MÁS GRANDE."],
  ["chalk", "I came.|I saw.|*I CHALKED EVERYTHING.", "Llegué.|Vi.|*LLENÉ TODO DE MAGNESIA.", "deadpan"],
  ["chalk", "Chalk is not a mess.|It’s an|*ENVIRONMENT.", "La magnesia no es un desastre.|Es un|*ECOSISTEMA.", "definition"],
  ["gym_life", "Gymnast starter pack:|2 grips. 14 hair ties. 900 pieces of tape.|*ZERO SKIN.", "Kit inicial de gimnasta:|2 calleras. 14 ligas. 900 pedazos de cinta.|*CERO PIEL.", "definition"],
  ["grips", "Bars routine: beautiful.|My hands afterward:|*CRIME SCENE.", "Rutina de barras: preciosa.|Mis manos después:|*ESCENA DEL CRIMEN."],
  ["grips", "My grips have two moods:|TOO NEW|and|*ABOUT TO BREAK.", "Mis calleras tienen dos estados:|DEMASIADO NUEVAS|y|*A PUNTO DE ROMPERSE."],
  ["chalk", "Why do gymnasts use so much chalk?|Because apparently|*HAVING SKIN WAS OPTIONAL.", "¿Por qué usamos tanta magnesia?|Porque al parecer|*TENER PIEL ERA OPCIONAL.", "question"],
  ["bars", "Bars are so supportive.|Until suddenly|*THEY’RE NOT.", "Las barras te apoyan muchísimo.|Hasta que de repente|*DEJAN DE HACERLO."],
  ["grips", "I trust my grips.|Which is funny, because I’ve seen|*WHAT THEY’VE DONE BEFORE.", "Confío en mis calleras.|Lo cual es gracioso porque ya vi|*LO QUE HICIERON ANTES."],
  ["grips", "Gymnastics teaches important life skills.|Like taping a hand|*USING ONE HAND.", "La gimnasia enseña habilidades importantes.|Como vendar una mano|*USANDO UNA SOLA MANO."],
  ["grips", "Rips build character.|Unfortunately,|*I ALREADY HAD ENOUGH CHARACTER.", "Las heridas forman el carácter.|Lamentablemente,|*YA TENÍA SUFICIENTE CARÁCTER."],
  ["grips", "If you see a gymnast staring silently at her palm…|Don’t ask.|*SHE’S GRIEVING.", "Si ves a una gimnasta mirando su palma en silencio…|No preguntes.|*ESTÁ DE LUTO."],
  ["chalk", "I didn’t choose chalk life.|Chalk life got into|*EVERY SINGLE THING I OWN.", "Yo no elegí la vida con magnesia.|La magnesia entró en|*TODO LO QUE TENGO."],
  ["vault", "Vault is basically:|Run toward a solid object|and|*TRUST THE PROCESS.", "El salto es básicamente:|Corre hacia un objeto sólido|y|*CONFÍA EN EL PROCESO.", "definition"],
  ["vault", "I trusted the springboard once.|*ONCE.", "Confié en el trampolín una vez.|*UNA VEZ.", "deadpan"],
  ["vault", 'Vault warm-up: “Looks great!”|Vault competition:|*WHO REPLACED MY LEGS?', 'Calentamiento de salto: «¡Se ve genial!»|Competencia:|*¿QUIÉN CAMBIÓ MIS PIERNAS?'],
  ["vault", "My vault run looked amazing.|We will not be discussing|*WHAT HAPPENED AFTERWARD.", "Mi carrera de salto se veía increíble.|No hablaremos de|*LO QUE PASÓ DESPUÉS."],
  ["vault", "Why was the gymnast nervous about vault?|Because running toward the problem|*IS USUALLY BAD ADVICE.", "¿Por qué estaba nerviosa con el salto?|Porque correr hacia el problema|*SUELE SER UN MAL CONSEJO.", "question"],
  ["coaches", 'Coach: “More power!”|Gymnast:|*“I’M ALREADY MOVING AT THE SPEED OF FEAR.”', 'Entrenadora: «¡Más potencia!»|Gimnasta:|*«YA VOY A LA VELOCIDAD DEL MIEDO».', "dialogue"],
  ["vault", "Vault philosophy:|Run fast. Block hard. Land.|*ASK QUESTIONS LATER.", "Filosofía de salto:|Corre. Bloquea. Aterriza.|*PREGUNTA DESPUÉS.", "definition"],
  ["vault", "Nothing makes you appreciate the vault table|like|*MISSING IT SLIGHTLY.", "Nada te hace apreciar la mesa de salto|como|*FALLARLA POR POCO."],
  ["coaches", 'Favorite vault correction: “Just block more.”|*WOW. WHY DIDN’T I THINK OF THAT?', 'Corrección favorita: «Solo bloquea más».|*VAYA. ¿CÓMO NO SE ME OCURRIÓ?'],
  ["vault", 'Only in gymnastics does “Run faster toward it!”|count as|*HELPFUL ADVICE.', 'Solo en gimnasia «¡Corre más rápido hacia eso!»|se considera|*UN CONSEJO ÚTIL.'],
  ["floor", "Floor music starts.|Suddenly I remember|*NONE OF MY CHOREOGRAPHY.", "Empieza la música de suelo.|De repente no recuerdo|*NADA DE MI COREOGRAFÍA."],
  ["competition", "My routine is 90 seconds long.|My anxiety has performed for|*THREE BUSINESS DAYS.", "Mi rutina dura 90 segundos.|Mi ansiedad lleva actuando|*TRES DÍAS LABORABLES."],
  ["floor", "I don’t forget choreography.|I create|*LIMITED-EDITION CHOREOGRAPHY.", "Yo no olvido la coreografía.|Creo|*COREOGRAFÍA DE EDICIÓN LIMITADA."],
  ["judges", 'Judge: “That wasn’t in the routine.”|Me:|*“IT IS NOW.”', 'Juez: «Eso no estaba en la rutina».|Yo:|*«AHORA SÍ».', "dialogue"],
  ["floor", "I landed out of bounds.|Personally, I think|*THE FLOOR SHOULD’VE BEEN BIGGER.", "Aterricé fuera del área.|Personalmente creo que|*EL SUELO DEBIÓ SER MÁS GRANDE."],
  ["floor", "Floor is my favorite event.|If I fall, at least|*I’M ALREADY ON THE FLOOR.", "Suelo es mi aparato favorito.|Si caigo, al menos|*YA ESTOY EN EL SUELO."],
  ["floor", "Tumbling pass: beautiful.|Dance section:|*WHAT DO I DO WITH MY ARMS?!", "Diagonal: preciosa.|Parte de danza:|*¿QUÉ HAGO CON MIS BRAZOS?!"],
  ["floor", "Nothing humbles a gymnast faster than|*FORGETTING WHICH CORNER COMES NEXT.", "Nada baja el ego más rápido que|*OLVIDAR QUÉ ESQUINA SIGUE."],
  ["floor", "Why did the gymnast love floor?|It let her dramatically|*WALK AWAY FROM HER PROBLEMS.", "¿Por qué amaba el suelo?|Le permitía alejarse dramáticamente|*DE SUS PROBLEMAS.", "question"],
  ["gymnast_brain", "My floor expression: confidence.|My actual thoughts:|*BREATHE. CORNER. BREATHE. CORNER.", "Mi expresión en suelo: confianza.|Mis pensamientos:|*RESPIRA. ESQUINA. RESPIRA. ESQUINA."],
  ["judges", 'Judge: “Small step.”|Me:|*“THAT WAS CHOREOGRAPHY.”', 'Juez: «Pequeño paso».|Yo:|*«ESO ERA COREOGRAFÍA».', "dialogue"],
  ["judges", 'Judge: “Bent knees.”|Gymnast:|*“EMOTIONAL SUPPORT KNEES.”', 'Juez: «Rodillas flexionadas».|Gimnasta:|*«RODILLAS DE APOYO EMOCIONAL».', "dialogue"],
  ["judges", 'Judge: “Flexed feet.”|Me:|*“THEY WERE RESTING.”', 'Juez: «Pies flexionados».|Yo:|*«ESTABAN DESCANSANDO».', "dialogue"],
  ["judges", "My routine got a 9.475.|I gave the judges|*4.2 FOR EMOTIONAL SUPPORT.", "Mi rutina obtuvo 9.475.|Yo les di a los jueces|*4.2 POR APOYO EMOCIONAL."],
  ["judges", "Judges see everything.|Except apparently|*HOW HARD I WORKED.", "Los jueces ven todo.|Excepto, al parecer,|*CUÁNTO TRABAJÉ."],
  ["competition", "I stuck the landing.|Please ignore|*EVERYTHING BEFORE IT.", "Clavé el aterrizaje.|Por favor ignoren|*TODO LO ANTERIOR."],
  ["judges", "When the score takes too long:|They’re either impressed|*OR WRITING A NOVEL.", "Cuando la nota tarda demasiado:|Están impresionados|*O ESCRIBIENDO UNA NOVELA."],
  ["judges", 'Gymnast: “That felt good!”|Scoreboard:|*INTERESTING.', 'Gimnasta: «¡Se sintió bien!»|Marcador:|*INTERESANTE.', "dialogue"],
  ["judges", "The judge smiled at me.|I don’t know if it meant “Great routine”|*OR “OH, HONEY.”", "La juez me sonrió.|No sé si significaba «Gran rutina»|*O «AY, CARIÑO»."],
  ["coaches", 'Coach: “Don’t look at the score.”|So naturally I look|*BEFORE I FINISH SALUTING.', 'Entrenadora: «No mires la nota».|Así que naturalmente la miro|*ANTES DE TERMINAR EL SALUDO.', "dialogue"],
  ["competition", "What does a gymnast call a relaxing weekend?|*COMPETITION SEASON.", "¿Cómo llama una gimnasta a un fin de semana relajante?|*TEMPORADA DE COMPETENCIA.", "question"],
  ["gym_moms", 'Meet starts at 8:00 AM.|Gym mom:|*“SO WE’RE LEAVING AT 4:15.”', 'La competencia empieza a las 8:00.|Mamá del gym:|*«ENTONCES SALIMOS A LAS 4:15».', "dialogue"],
  ["meet_day", "Competition checklist:|Leo. Hair. Grips. Food. Water.|*PANIC.", "Lista para competir:|Leotardo. Peinado. Calleras. Comida. Agua.|*PÁNICO.", "definition"],
  ["gym_moms", "The meet is two hours away.|Why are we leaving|*YESTERDAY?", "La competencia queda a dos horas.|¿Por qué salimos|*AYER?"],
  ["meet_day", "Gymnastics meets are mostly waiting|with occasional|*LIFE-OR-DEATH ACROBATICS.", "Las competencias son casi toda espera|con momentos de|*ACROBACIA DE VIDA O MUERTE."],
  ["competition", "Warm-up: best routine of my life.|Competition:|*A DIFFERENT GYMNAST ARRIVED.", "Calentamiento: la mejor rutina de mi vida.|Competencia:|*LLEGÓ OTRA GIMNASTA."],
  ["warmups", "What happens in warm-ups stays there.|Unless someone’s mom|*RECORDED IT.", "Lo que pasa en calentamiento se queda allí.|A menos que alguna mamá|*LO HAYA GRABADO."],
  ["meet_day", "Meet goal: hit 4-for-4.|Goal after warm-ups:|*SURVIVE.", "Meta: acertar 4 de 4.|Meta después del calentamiento:|*SOBREVIVIR."],
  ["meet_day", "There are two kinds of meet bathrooms:|BUSY|and|*IMPOSSIBLE.", "Hay dos tipos de baños en competencia:|OCUPADO|e|*IMPOSIBLE."],
  ["team", 'Nothing bonds a team like saying “DID YOU SEE THAT?”|*AT EXACTLY THE SAME TIME.', 'Nada une más a un equipo que decir «¿VISTE ESO?»|*AL MISMO TIEMPO.'],
  ["teammates", 'Teammate: “You’ve got this!”|Me:|*“SAY IT WITH MORE EVIDENCE.”', 'Compañera: «¡Tú puedes!»|Yo:|*«DILO CON MÁS EVIDENCIA».', "dialogue"],
  ["teammates", "Real friendship is lending tape|knowing|*YOU MAY NEVER SEE IT AGAIN.", "Amistad real es prestar cinta|sabiendo que|*QUIZÁS NUNCA REGRESE."],
  ["team", "Teammates know your routines, fears and snacks.|And which skill|*WE DO NOT DISCUSS TODAY.", "Tus compañeras conocen tus rutinas, miedos y snacks.|Y qué elemento|*NO MENCIONAMOS HOY."],
  ["conditioning", 'Nothing unites a team faster than a coach saying:|*“CONDITIONING.”', 'Nada une más rápido a un equipo que escuchar:|*«ACONDICIONAMIENTO».'],
  ["team", 'Team meeting: “Any questions?” Everyone: no.|Locker room later:|*47 QUESTIONS.', 'Reunión: «¿Preguntas?» Todas: no.|Cinco minutos después:|*47 PREGUNTAS.'],
  ["teammates", 'Teammate: “You almost had it!”|That word “almost”|*IS DOING A LOT OF WORK.', 'Compañera: «¡Casi lo tenías!»|La palabra «casi»|*ESTÁ TRABAJANDO DEMASIADO.'],
  ["teammates", 'A true teammate screams “STICK!”|as if volume|*CONTROLS YOUR LANDING.', 'Una compañera de verdad grita «¡CLÁVALO!»|como si el volumen|*CONTROLARA EL ATERRIZAJE.'],
  ["teammates", "Gym friendship: support dreams, cheer routines,|and laugh when you trip|*WALKING TO VAULT.", "Amistad del gym: apoyar sueños, animar rutinas|y reír si tropiezas|*CAMINANDO HACIA SALTO."],
  ["teammates", 'We don’t laugh when teammates fall.|We wait for “I’m fine.”|*THEN WE LAUGH.', 'No reímos cuando una compañera cae.|Esperamos el «Estoy bien».|*LUEGO REÍMOS.'],
  ["gym_life", "Elite gymnast trips over a mat.|Skills: impossible.|*WALKING: UNDER REVIEW.", "Gimnasta élite tropieza con una colchoneta.|Elementos: imposibles.|*CAMINAR: EN REVISIÓN."],
  ["gym_life", "Gymnasts flip on four inches.|Then walk directly|*INTO A DOORFRAME.", "Las gimnastas giran sobre diez centímetros.|Luego chocan directamente|*CON EL MARCO DE UNA PUERTA."],
  ["general", "I can do a back handspring.|Please do not ask me|*TO CATCH ANYTHING.", "Puedo hacer un flic-flac.|Por favor no me pidas|*ATRAPAR NADA."],
  ["general", 'People: “Gymnasts are so graceful!”|Gymnast outside the gym:|*TRIPS OVER AIR.', 'Gente: «¡Qué elegantes son las gimnastas!»|Gimnasta fuera del gym:|*TROPIEZA CON EL AIRE.', "dialogue"],
  ["gymnast_brain", "My body can twist in the air.|But cannot remember|*WHERE I LEFT MY WATER BOTTLE.", "Mi cuerpo puede girar en el aire.|Pero no recuerda|*DÓNDE DEJÓ LA BOTELLA."],
  ["general", "Gymnastics gave me great balance.|Except when putting on socks|*STANDING UP.", "La gimnasia me dio gran equilibrio.|Excepto al ponerme medias|*DE PIE."],
  ["general", "Why was the gymnast late?|She got caught in|*A SPLIT DECISION.", "¿Por qué llegó tarde la gimnasta?|Quedó atrapada en|*UNA DECISIÓN ABIERTA.", "question"],
  ["general", "A gymnast’s favorite tea?|*CONSISTEN-TEA.", "¿El té favorito de una gimnasta?|*CONSISTEN-TÉ.", "question"],
  ["beam", "Why not play hide-and-seek on beam?|There’s|*NOWHERE TO HIDE.", "¿Por qué no jugar escondidas en la viga?|Porque no hay|*DÓNDE ESCONDERSE.", "question"],
  ["bars", "Why did the gymnast bring a ladder?|Her coach said|*HER BARS NEEDED TO BE HIGHER.", "¿Por qué llevó una escalera?|Su entrenadora dijo que|*LAS BARRAS DEBÍAN ESTAR MÁS ALTAS.", "question"],
  ["chalk", "Why carry chalk everywhere?|She likes to leave|*A LITTLE EVIDENCE.", "¿Por qué lleva magnesia a todas partes?|Le gusta dejar|*UN POCO DE EVIDENCIA.", "question"],
  ["judges", "Why not argue with gravity?|Gravity always gets|*THE FINAL DEDUCTION.", "¿Por qué no discutir con la gravedad?|La gravedad siempre aplica|*LA DEDUCCIÓN FINAL.", "question"],
  ["beam", "Why did she talk to the beam?|She needed|*CLOSURE.", "¿Por qué habló con la viga?|Necesitaba|*CERRAR EL CICLO.", "question"],
  ["beam", "Least favorite relationship status?|IT’S COMPLICATED.|*SIGNED, BEAM.", "¿Estado sentimental menos favorito?|ES COMPLICADO.|*FIRMADO: LA VIGA.", "deadpan"],
  ["beam", "My toxic trait: thinking one more turn|will magically fix|*MY BEAM ROUTINE.", "Mi rasgo tóxico: creer que un turno más|arreglará mágicamente|*MI RUTINA DE VIGA."],
  ["general", 'Gymnastics is: “That looked terrifying.”|“Thanks!|*I’VE BEEN WORKING ON IT.”', 'La gimnasia es: «Eso se veía aterrador».|«¡Gracias!|*HE ESTADO PRACTICÁNDOLO».', "dialogue"],
  ["skills", "Normal people see a wall.|Gymnasts see:|*COULD I HANDSTAND ON THAT?", "La gente ve una pared.|Las gimnastas ven:|*¿PUEDO HACER PARADA DE MANOS AHÍ?"],
  ["skills", "Normal people enter a hotel room.|Gymnasts evaluate floor, ceiling and|*HANDSTAND POTENTIAL.", "La gente entra a un hotel.|Las gimnastas evalúan suelo, techo y|*POTENCIAL DE PARADA DE MANOS."],
  ["gym_life", 'Parents: “Stop doing gymnastics in the house.”|Me:|*“TECHNICALLY, THAT WAS ONLY A CARTWHEEL.”', 'Padres: «Deja de hacer gimnasia en casa».|Yo:|*«TÉCNICAMENTE SOLO FUE UNA RUEDA».', "dialogue"],
  ["gym_life", "Nothing says gymnast like stretching|during|*A COMPLETELY UNRELATED ACTIVITY.", "Nada dice gimnasta como estirarse|durante|*UNA ACTIVIDAD SIN RELACIÓN."],
  ["skills", 'Someone says “point your toes”|and your feet respond|*AUTOMATICALLY.', 'Alguien dice «estira las puntas»|y tus pies responden|*AUTOMÁTICAMENTE.'],
  ["skills", "Gymnastics builds confidence.|And the ability to say “Again”|*AFTER SOMETHING TERRIFYING.", "La gimnasia construye confianza.|Y la capacidad de decir «Otra vez»|*DESPUÉS DE ALGO ATERRADOR."],
  ["coaches", 'Coach: “What did we learn?”|Gymnast: “I need to do it again.”|*COACH: “EXACTLY.”', 'Entrenadora: «¿Qué aprendimos?»|Gimnasta: «Que debo repetirlo».|*ENTRENADORA: «EXACTO».', "dialogue"],
  ["gymnast_brain", 'Brain before routine: “You’ve done this a thousand times.”|Brain during routine:|*“HAVE WE?”', 'Cerebro antes: «Lo hiciste mil veces».|Cerebro durante:|*«¿SEGURO?»', "dialogue"],
  ["chalk", "Every day is a new chance|to discover another way|*TO GET CHALK ON MY FACE.", "Cada día es otra oportunidad|de descubrir una forma nueva|*DE LLENARME LA CARA DE MAGNESIA."],
  ["gym_life", "Gymnastics: make impossible look easy.|Then walk away pretending|*YOUR WHOLE BODY FEELS GREAT.", "Gimnasia: hacer que lo imposible parezca fácil.|Luego irte fingiendo que|*TODO TU CUERPO ESTÁ PERFECTO."],
  ["leo_hair", "Meet hair took forty minutes.|The routine takes ninety seconds.|*THE MATH IS GLAMOROUS.", "El peinado tomó cuarenta minutos.|La rutina dura noventa segundos.|*LA MATEMÁTICA ES GLAMOROSA."],
  ["leo_hair", "My bun has more structural support|than|*MY PRE-MEET CONFIDENCE.", "Mi moño tiene más soporte estructural|que|*MI CONFIANZA PRECOMPETENCIA."],
  ["conditioning", 'Coach: “Last set.”|The clock:|*THAT WAS A LIE.', 'Entrenadora: «Última serie».|El reloj:|*ESO ERA MENTIRA.', "dialogue"],
  ["conditioning", "Conditioning is just a team meeting|where everyone’s agenda is|*SURVIVAL.", "El acondicionamiento es una reunión de equipo|donde la agenda de todas es|*SOBREVIVIR."],
  ["warmups", "My warm-up turn was perfect.|Naturally, I have used|*TODAY’S ENTIRE SUPPLY.", "Mi turno de calentamiento fue perfecto.|Naturalmente, ya usé|*TODA LA PERFECCIÓN DE HOY."],
  ["competition", "I packed everything for the meet.|Except apparently|*THE ROUTINE I PRACTICED.", "Empaqué todo para competir.|Excepto, al parecer,|*LA RUTINA QUE PRACTIQUÉ."],
  ["team", "Team group chat at 9 PM: quiet.|At 5 AM meet day:|*87 MESSAGES.", "Chat del equipo a las 9 PM: silencio.|A las 5 AM el día del meet:|*87 MENSAJES."],
  ["grips", "My grips requested legal counsel.|The charge:|*EXTREME WORKING CONDITIONS.", "Mis calleras pidieron abogado.|El cargo:|*CONDICIONES LABORALES EXTREMAS."],
  ["gymnast_brain", "I said I wouldn’t overthink today.|That was thought number|*ONE OF 48.", "Dije que hoy no pensaría demasiado.|Ese fue el pensamiento|*UNO DE 48."],
  ["general", "Practice was character-building.|I would like to unsubscribe|*FROM THE CHARACTER.", "La práctica formó carácter.|Quisiera cancelar mi suscripción|*AL CARÁCTER."],
  ["team", "The group chat said “casual.”|Everyone arrived|*IN FULL COMPETITION HAIR.", "El chat dijo «casual».|Todas llegaron|*CON PEINADO DE COMPETENCIA."],
  ["floor", "My music says drama.|My lungs say|*THIS IS A DOCUMENTARY.", "Mi música dice drama.|Mis pulmones dicen|*ESTO ES UN DOCUMENTAL."],
  ["bars", "I released the bar with confidence.|The confidence and I|*LANDED SEPARATELY.", "Solté la barra con confianza.|La confianza y yo|*ATERRIZAMOS POR SEPARADO."],
  ["meet_day", "Salute: elegant.|Walk off the podium:|*IMMEDIATE CHAOS.", "Saludo: elegante.|Salir del podio:|*CAOS INMEDIATO."],
  ["gym_moms", "Gym mom bag inventory:|snacks, tape, hairspray, wisdom,|*ANOTHER BAG.", "Bolso de mamá del gym:|snacks, cinta, laca, sabiduría|*Y OTRO BOLSO."],
  ["general", "Gymnastics teaches patience.|Mostly while waiting for|*THE SCORE TO EXIST.", "La gimnasia enseña paciencia.|Sobre todo esperando que|*APAREZCA LA NOTA."],
  ["coaches", 'Coach: “Relax.”|Every muscle in my body:|*NO.', 'Entrenadora: «Relájate».|Cada músculo de mi cuerpo:|*NO.', "dialogue"]
];

export const GYM_LOL_JOKES = rawJokes.slice(0, 100).map((joke, index) => make(index, ...joke));

export const GYM_LOL_PALETTE = [
  { id: "cherry", background: "#d62d35", foreground: "#fffdf8" },
  { id: "lemon", background: "#f4e43b", foreground: "#171512" },
  { id: "rouge", background: "#e82779", foreground: "#fffdf8" },
  { id: "pink", background: "#e8a4b7", foreground: "#171512" },
  { id: "green", background: "#5fbd70", foreground: "#102018" },
  { id: "blue", background: "#1769e8", foreground: "#fffdf8" },
  { id: "mint", background: "#b8e6d2", foreground: "#14201b" },
  { id: "butter", background: "#f2d98c", foreground: "#1d1910" }
];

export const GYM_LOL_REACTIONS = [
  { label: { en: "TOO REAL?", es: "¿MUY REAL?" }, options: [{ en: "THAT’S ME", es: "SOY YO" }, { en: "TOO REAL", es: "MUY REAL" }, { en: "SEND THIS", es: "LO ENVÍO" }] },
  { label: { en: "RATE THE DAMAGE", es: "CALIFICA EL DAÑO" }, options: [{ en: "CUTE", es: "LINDO" }, { en: "TOO REAL", es: "MUY REAL" }, { en: "PERSONAL ATTACK", es: "ATAQUE PERSONAL" }] },
  { label: { en: "WHO IS THIS ABOUT?", es: "¿DE QUIÉN HABLAMOS?" }, options: [{ en: "ME", es: "YO" }, { en: "MY COACH", es: "MI ENTRENADORA" }, { en: "MY WHOLE TEAM", es: "TODO MI EQUIPO" }] },
  { label: { en: "BE HONEST", es: "SÉ HONESTA" }, options: [{ en: "THIS HURT", es: "ESO DOLIÓ" }, { en: "THIS IS TRUE", es: "ES VERDAD" }, { en: "I’M SENDING THIS", es: "LO VOY A ENVIAR" }] }
];

export const GYM_LOL_MICRO_REACTIONS = {
  en: ["We knew that one would hurt.", "No names were mentioned.", "Your coach did not approve this message.", "The beam would like to respond.", "We’re just reporting the facts.", "Too specific?", "Gymnasts know.", "This stays between us.", "No chalk was harmed in this joke.", "The judges deducted 0.1 for laughing.", "Your teammate already screenshotted this.", "That one felt personal.", "Respectfully… accurate.", "Please don’t show your coach.", "The Gymternet agrees.", "We said what we said.", "The group chat is going to love this.", "Apparently this needed to be said.", "The beam denies everything.", "Your grips have requested legal counsel."],
  es: ["Sabíamos que esa iba a doler.", "No mencionamos nombres.", "Tu entrenadora no aprobó este mensaje.", "La viga quisiera responder.", "Solo reportamos los hechos.", "¿Demasiado específico?", "Las gimnastas saben.", "Esto queda entre nosotras.", "Ninguna magnesia sufrió daños.", "Los jueces descontaron 0.1 por reír.", "Tu compañera ya tomó captura.", "Eso se sintió personal.", "Con respeto… exacto.", "Por favor no se lo enseñes a tu entrenadora.", "La Gymternet está de acuerdo.", "Dijimos lo que dijimos.", "Al chat del equipo le encantará.", "Al parecer había que decirlo.", "La viga lo niega todo.", "Tus calleras solicitaron asesoría legal."]
};

export function chooseNextJoke({ currentId, recentIds = [], currentCategory, random = Math.random }) {
  const blocked = new Set([currentId, ...recentIds.slice(-5)]);
  const preferred = GYM_LOL_JOKES.filter(joke => !blocked.has(joke.id) && joke.category !== currentCategory);
  const pool = preferred.length ? preferred : GYM_LOL_JOKES.filter(joke => joke.id !== currentId);
  return pool[Math.floor(random() * pool.length)] || GYM_LOL_JOKES[0];
}
