import {imagotypeMarkup} from '../Play/exportArtwork.js';
import {prepareSvg} from '../BowDesigner/BowPreview.jsx';
import {CARD_FORMATS,wrapText} from './bowracleCardSvg.js';

const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const text=(value,x,y,size,extra='')=>`<text x="${x}" y="${y}" fill="#28172e" ${extra.includes('font-family=')?'':'font-family="Arial,sans-serif" '}font-size="${size}" ${extra}>${esc(value)}</text>`;
const lines=(value,x,y,size,width,extra='')=>wrapText(value,size,width).map((line,index)=>text(line,x,y+index*size*1.3,size,extra)).join('');
const frame=height=>`<defs><linearGradient id="veil" x2="0" y2="1"><stop stop-color="#fffaf0" stop-opacity=".9"/><stop offset=".48" stop-color="#fff8f1" stop-opacity=".78"/><stop offset="1" stop-color="#e9f8f4" stop-opacity=".88"/></linearGradient><filter id="glow"><feGaussianBlur stdDeviation="12"/></filter></defs><rect width="1080" height="${height}" fill="#1a0a31"/><image href="/assets/bowracle/mystic-pop/house-collectible-v1.webp" x="0" y="0" width="1080" height="${height}" preserveAspectRatio="xMidYMid slice"/><rect x="42" y="42" width="996" height="${height-84}" rx="84" fill="url(#veil)" stroke="#d8a8ff" stroke-width="5"/><rect x="66" y="66" width="948" height="${height-132}" rx="66" fill="none" stroke="#55d9d0" stroke-width="2"/><circle cx="930" cy="180" r="130" fill="#f9b5ff" opacity=".18" filter="url(#glow)"/>`;
const gymnastSeal=(x,y)=>`<g transform="translate(${x} ${y})" fill="none" stroke="#a45784" stroke-linecap="round" stroke-linejoin="round"><circle cx="30" cy="18" r="10" fill="#a45784" stroke="none"/><path d="M28 31C18 51 15 74 29 91M29 45C49 47 61 38 73 25M30 57C14 62 4 76 0 91M29 90C47 96 61 112 70 133M29 90C20 109 19 125 22 139" stroke-width="9"/><path d="M0 91L-20 104M73 25L91 8" stroke-width="7"/></g>`;

export function createSecretLetterSvg({result,name,letter,locale,date},_t,format='story'){
 const {height}=CARD_FORMATS[format],body=letter.body[locale]||letter.body.es,title=letter.title[locale]||letter.title.es,signoff=letter.signoff[locale]||letter.signoff.es;
 const excerpts=[body[0],body[Math.floor(body.length/2)],body.at(-1)].filter(Boolean),font=format==='feed'?23:29,width=800;
 let y=format==='feed'?340:400,copy='';
 for(const paragraph of excerpts){copy+=lines(paragraph,540,y,font,width,'text-anchor="middle" font-family="Georgia,serif"');y+=wrapText(paragraph,font,width).length*font*1.3+34;}
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${height}" viewBox="0 0 1080 ${height}">${frame(height)}${imagotypeMarkup(80,76,100,88)}${text('PRFCT10 PLAY · MASHUKI LETTERS · V1',540,112,18,'text-anchor="middle" letter-spacing="2"')}${text(locale==='es'?'UNA CARTA PARA':'A LETTER FOR',540,180,18,'text-anchor="middle" letter-spacing="4"')}${text(name,540,250,56,'text-anchor="middle" font-family="Georgia,serif" font-style="italic"')}${lines(title,540,310,26,780,'text-anchor="middle" font-weight="700" letter-spacing="1"')}${copy}${lines(`${signoff} Mashuki`,540,Math.min(y+20,height-210),27,760,'text-anchor="middle" font-family="Georgia,serif" font-style="italic"')}${text(date,540,height-126,18,'text-anchor="middle" letter-spacing="1.5"')}${text(`${result.messageId} · ${result.code}`,540,height-88,16,'text-anchor="middle" font-family="monospace"')}${gymnastSeal(900,height-285)}</svg>`;
}

export function createSecretHouseSvg({result,name,house,letter,locale,date},_t,format='story'){
 const {height}=CARD_FORMATS[format],bowY=format==='feed'?410:560,bowHeight=format==='feed'?220:290;
 const bow=prepareSvg({prefix:'house-bow',...result.design}).replace('viewBox="0 0 900 650"','viewBox="70 65 760 505"').replace('<svg ',`<svg x="220" y="${bowY}" width="640" height="${bowHeight}" `);
 return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="${height}" viewBox="0 0 1080 ${height}">${frame(height)}${imagotypeMarkup(80,76,100,88)}${text('PRFCT10 PLAY · SECRET BOW HOUSES · V1',540,112,18,'text-anchor="middle" letter-spacing="2"')}${text(locale==='es'?'TU LAZO PERTENECE A':'YOUR BOW BELONGS TO',540,195,18,'text-anchor="middle" letter-spacing="4"')}${lines(house.name,540,285,58,820,'text-anchor="middle" font-family="Georgia,serif" font-style="italic"')}${lines(house.words,540,365,19,840,'text-anchor="middle" letter-spacing="2"')}${bow}${text(house.symbol,185,bowY+80,18,'letter-spacing="2"')}${text(house.gem,895,bowY+80,18,'text-anchor="end" letter-spacing="2"')}${lines(`“${house.motto}”`,540,bowY+bowHeight+70,31,760,'text-anchor="middle" font-family="Georgia,serif" font-style="italic"')}${lines(house.description,540,bowY+bowHeight+145,format==='feed'?21:25,790,'text-anchor="middle"')}${text(name,540,height-165,22,'text-anchor="middle" font-weight="700"')}${text(`${date} · ${result.bowCollection||result.edition||'MASHUKI LETTERS V1'}`,540,height-126,17,'text-anchor="middle" letter-spacing="1"')}${text(`${result.bowName||letter.title.es} · ${result.code}`,540,height-88,15,'text-anchor="middle" font-family="monospace"')}${gymnastSeal(900,height-295)}</svg>`;
}
