export const SECRET_MESSAGE_UI={
 en:{entryEyebrow:'THE SECRET BOW GARDEN',entryTitle:'Your bow found you first.',entryCopy:'Some bows are chosen. Some bows choose back.',entryBody:'Enter the garden to open the message your bow has been keeping for you.',entryCta:'Enter the garden',formEyebrow:'THE ENCHANTED REGISTRY',formTitle:'The garden knows why you came.',formCopy:'Three small details open the letter that has been waiting for you.',formMicro:'Mashuki is the keeper of the bow messages. She writes what the bow has been waiting to tell you.',registry:'THE SECRET BOW REGISTRY',registryIntro:'Write gently. Nothing entered here changes the message assigned to your bow.',nameLabel:'Your name',nameHint:'Tell the garden what to call you.',namePlaceholder:'First name',dateLabel:'The day you found each other',dateHint:'Mark the day your message arrived.',codeLabel:'Secret bow code',codeHint:'Every bow carries a private key.',formCta:'Open my message',invalid:'The garden could not find that code.',invalidHelp:'Check each letter and number, then try once more.',network:'The garden is resting for a moment. Please try again.',transition:['Your bow recognizes you.','Opening your message.','The garden remembers your light.','Gathering the words that belong to you.'],letterTitle:'A letter for',opened:'Opened {date}',from:'From your bow, kept by Mashuki',purpose:'This letter is not a prediction and it does not define you. It is a keepsake written for the bow connected to this code—a gentle place to return when you need encouragement, perspective, or a reminder that becoming takes time. Let the words meet you where you are today, and keep only what helps you move with greater kindness toward yourself.',continueHouse:'Reveal my bow’s house',belongs:'Your bow belongs to',houseCopy:'Every bow carries one of four energies. This one was woven into yours from the beginning.',continueKeepsake:'Create my keepsakes',keepsakeTitle:'Two pieces of the garden are yours.',keepsakeCopy:'Save the letter that found you and the House card that belongs to your bow.',letterCollectible:'Your enchanted letter',houseCollectible:'Your bow’s House card',saveLetter:'Save my letter',shareLetter:'Share my letter',downloadHouse:'Download my House card',shareHouse:'Share my House card',seeBow:'See my bow',return:'Return to the garden',signature:'Mashuki',traveler:'you'},
 es:{entryEyebrow:'EL JARDÍN SECRETO DE LOS LAZOS',entryTitle:'Tu lazo te encontró primero.',entryCopy:'Algunos lazos se eligen. Otros también te eligen.',entryBody:'Entra al jardín para abrir el mensaje que tu lazo ha estado guardando para ti.',entryCta:'Entrar al jardín',formEyebrow:'EL REGISTRO ENCANTADO',formTitle:'El jardín sabe por qué llegaste.',formCopy:'Tres pequeños detalles abren la carta que te estaba esperando.',formMicro:'Mashuki es la guardiana de los mensajes de los lazos. Ella escribe lo que tu lazo ha estado esperando decirte.',registry:'EL REGISTRO SECRETO DEL LAZO',registryIntro:'Escribe con calma. Nada de lo que ingreses cambia el mensaje asignado a tu lazo.',nameLabel:'Tu nombre',nameHint:'Dile al jardín cómo llamarte.',namePlaceholder:'Nombre',dateLabel:'El día en que se encontraron',dateHint:'Marca el día en que llegó tu mensaje.',codeLabel:'Código secreto del lazo',codeHint:'Cada lazo lleva una llave privada.',formCta:'Abrir mi mensaje',invalid:'El jardín no pudo encontrar ese código.',invalidHelp:'Revisa cada letra y número e inténtalo una vez más.',network:'El jardín descansa por un momento. Inténtalo de nuevo.',transition:['Tu lazo te reconoce.','Abriendo tu mensaje.','El jardín recuerda tu luz.','Reuniendo las palabras que te pertenecen.'],letterTitle:'Una carta para',opened:'Abierta el {date}',from:'De tu lazo, resguardada por Mashuki',purpose:'Esta carta no es una predicción y no te define. Es un recuerdo escrito para el lazo conectado a este código: un lugar amable al que regresar cuando necesites aliento, perspectiva o recordar que transformarte toma tiempo. Permite que sus palabras te encuentren donde estás hoy y conserva aquello que te ayude a caminar con más bondad hacia ti misma.',continueHouse:'Revelar la Casa de mi lazo',belongs:'Tu lazo pertenece a',houseCopy:'Cada lazo lleva una de cuatro energías. Esta vive en el tuyo desde el principio.',continueKeepsake:'Crear mis recuerdos',keepsakeTitle:'Dos piezas del jardín son tuyas.',keepsakeCopy:'Guarda la carta que te encontró y la tarjeta de la Casa que pertenece a tu lazo.',letterCollectible:'Tu carta encantada',houseCollectible:'La tarjeta de la Casa de tu lazo',saveLetter:'Guardar mi carta',shareLetter:'Compartir mi carta',downloadHouse:'Descargar mi tarjeta de Casa',shareHouse:'Compartir mi tarjeta de Casa',seeBow:'Ver mi lazo',return:'Volver al jardín',signature:'Mashuki',traveler:'ti'}
};
export const ENCHANTED_HOUSES={
 POISE:{symbol:'BUTTERFLY',gem:'OPAL',colors:['#ead9f2','#f8e7ec'],en:{name:'House of Poise',words:'POISE · INTENTION · QUIET STRENGTH',motto:'Soft does not mean uncertain.',description:'Bows of Poise carry an elegant steadiness. Their beauty lives in thoughtful preparation, calm attention and the strength to begin again without turning hard. They remind us that grace is not perfection; it is the way care returns to every movement. This House belongs to bows made to accompany patient growth, clear choices and the kind of courage that can remain gentle.'},es:{name:'Casa del Equilibrio',words:'SERENIDAD · INTENCIÓN · FUERZA TRANQUILA',motto:'Suave no significa incierta.',description:'Los lazos del Equilibrio llevan una firmeza elegante. Su belleza vive en la preparación consciente, la atención tranquila y la fuerza de comenzar otra vez sin endurecerse. Recuerdan que la gracia no es perfección, sino la forma en que el cuidado regresa a cada movimiento. Esta Casa pertenece a los lazos creados para acompañar el crecimiento paciente, las decisiones claras y un coraje que puede seguir siendo dulce.'}},
 VELOCITY:{symbol:'DRAGONFLY',gem:'AQUAMARINE',colors:['#b7e9ee','#9bbcff'],en:{name:'House of Velocity',words:'VELOCITY · MOMENTUM · BRAVE MOTION',motto:'Trust the step that starts the story.',description:'Bows of Velocity hold the energy of a threshold: the breath before movement, the first brave step and the momentum that follows. They do not ask for haste. They celebrate direction, curiosity and the courage to move while the whole path is not yet visible. This House belongs to bows that recognize a readiness already built through practice, return and honest effort.'},es:{name:'Casa de la Velocidad',words:'VELOCIDAD · IMPULSO · MOVIMIENTO VALIENTE',motto:'Confía en el paso que inicia la historia.',description:'Los lazos de la Velocidad guardan la energía de un umbral: el aliento antes del movimiento, el primer paso valiente y el impulso que le sigue. No piden prisa. Celebran la dirección, la curiosidad y el coraje de avanzar aunque el camino completo todavía no se vea. Esta Casa pertenece a los lazos que reconocen una preparación construida con práctica, regreso y esfuerzo sincero.'}},
 POWER:{symbol:'FIREFLY',gem:'CITRINE',colors:['#f8e593','#ef9abf'],en:{name:'House of Power',words:'POWER · DEVOTION · RESILIENCE',motto:'What you practice in quiet becomes light.',description:'Bows of Power know that real strength is often built away from applause. They carry devotion, resilience and the warm fire of work repeated with care. Their power is not loud or severe; it is reliable. This House belongs to bows that remember every attempt, every return and every ordinary day that quietly becomes part of something extraordinary.'},es:{name:'Casa de la Fuerza',words:'PODER · DEVOCIÓN · RESILIENCIA',motto:'Lo que practicas en silencio se convierte en luz.',description:'Los lazos de la Fuerza saben que la fuerza verdadera suele construirse lejos del aplauso. Llevan devoción, resiliencia y el fuego cálido del trabajo repetido con cuidado. Su poder no es ruidoso ni severo; es confiable. Esta Casa pertenece a los lazos que recuerdan cada intento, cada regreso y cada día común que, silenciosamente, se vuelve parte de algo extraordinario.'}},
 FLIGHT:{symbol:'SWALLOWTAIL',gem:'MOONSTONE',colors:['#d2c7ff','#c8f0dc'],en:{name:'House of Flight',words:'FLIGHT · TRUST · POSSIBILITY',motto:'The space ahead knows your wings.',description:'Bows of Flight carry possibility. They belong to the space between takeoff and landing, where trust grows before certainty arrives. Their light is curious, hopeful and free without losing its roots. This House belongs to bows that accompany becoming: reminders that timing can be personal, confidence can return and an unfolding story does not need to rush in order to rise.'},es:{name:'Casa del Vuelo',words:'VUELO · CONFIANZA · POSIBILIDAD',motto:'El espacio que viene conoce tus alas.',description:'Los lazos del Vuelo llevan posibilidad. Pertenecen al espacio entre el despegue y la llegada, donde la confianza crece antes de que exista certeza. Su luz es curiosa, esperanzada y libre sin perder sus raíces. Esta Casa pertenece a los lazos que acompañan la transformación: recuerdan que el tiempo puede ser personal, la confianza puede regresar y una historia no necesita apresurarse para elevarse.'}}
};

export const SECRET_LETTERS=[
 {id:'remember',en:[
  'There are encounters that seem small to the world and still carry an immense tenderness within them. That is what happened between you and this bow. You may have held it without knowing it carried a quiet promise: to remind you who you are whenever tiredness, doubt or silence tries to make you forget your own light.',
  'This bow found you because it recognizes something precious in you: a serene strength that does not need to announce itself to be real. There is discipline, tenderness and courage in the way you continue, even on days when the road feels longer.',
  'You are not made only of results, perfect routines or easy moments. You are also made of perseverance, brave attempts and the silent decision to begin again as many times as necessary. That is a noble kind of greatness.',
  'Keep this message like a pressed flower inside a beloved book. Return when you need to hear with complete clarity that you are capable, you are growing, and you will travel farther than you can imagine today.',
  'This bow came to accompany you and remind you that your story is not stopping. It is only beginning to open its wings.'
 ],es:[
  'Hay encuentros que parecen pequeños a los ojos del mundo y, sin embargo, guardan una delicadeza inmensa. Así ha sucedido contigo y con este lazo. Tal vez lo sostuviste sin imaginar que también traía una promesa silenciosa: recordarte quién eres cuando el cansancio, la duda o el silencio intenten hacerte olvidar tu propia luz.',
  'Este lazo te encontró porque reconoce en ti algo precioso: una fuerza serena que no necesita anunciarse para ser verdadera. Hay disciplina, ternura y coraje en tu forma de continuar, incluso en los días en que el camino parece más largo.',
  'No estás hecha solamente de resultados, rutinas perfectas o momentos fáciles. También estás hecha de perseverancia, intentos valientes y la decisión silenciosa de volver a empezar cuantas veces sea necesario. Esa es una forma muy noble de grandeza.',
  'Conserva este mensaje como quien guarda una flor prensada entre las páginas de un libro amado. Regresa cuando necesites escuchar con absoluta claridad que eres capaz, que estás creciendo y que llegarás más lejos de lo que hoy imaginas.',
  'Este lazo llegó para acompañarte y recordarte que tu historia no se está deteniendo. Apenas está desplegando sus alas.'
 ],signoff:{en:'With love,',es:'Con cariño,'}},
 {id:'soft-day',en:[
  'If your heart feels more fragile than usual today, receive these words slowly, like a letter written by candlelight in a silent garden. This bow wanted to find you precisely for days like this—days when you need to hear again what you should never have had to doubt.',
  'Do not let one difficult moment convince you of the wrong story about yourself. A heavy day does not mean a small life. A mistake does not define you. A pause does not cancel what is meant for you.',
  'There is an extraordinary ability in you to rise again. You may do it with fear, with tears or with a courage so quiet that only you can see it. You still do it, and that matters more than you know.',
  'This bow chose you because it sees the seed of something luminous. Not because everything is already solved, but because everything you need to bloom is already beginning inside you.',
  'Keep these words where you can find them. When doubt returns, read them slowly until your spirit stands upright again. There is still so much to discover in you, and all signs say it will be beautiful.'
 ],es:[
  'Si hoy tu corazón se siente un poco más frágil de lo habitual, recibe estas palabras con calma, como una carta escrita a la luz de una vela en medio de un jardín silencioso. Este lazo quiso encontrarte precisamente para estos días, cuando necesitas volver a escuchar aquello que jamás debiste poner en duda.',
  'No permitas que un momento difícil te convenza de una historia equivocada sobre ti. Un día pesado no significa una vida pequeña. Un error no te define. Una pausa no cancela lo que está destinado para ti.',
  'Hay en ti una capacidad extraordinaria para volver a levantarte. Quizás lo haces con miedo, con lágrimas o con una valentía tan silenciosa que apenas tú la percibes. Aun así lo haces, y eso importa más de lo que imaginas.',
  'Este lazo te eligió porque ve en ti la semilla de algo luminoso. No porque todo esté resuelto, sino porque dentro de ti ya existe lo necesario para florecer.',
  'Guarda estas palabras donde puedas encontrarlas. Cuando regrese la duda, léelas despacio hasta que vuelvan a enderezarte el alma. Todavía hay mucho por descubrir en ti, y todo indica que será hermoso.'
 ],signoff:{en:'With tenderness,',es:'Con ternura,'}},
 {id:'threshold',en:[
  'There is a particular elegance in the moments before a great step. The air, the room and the heart seem to hold their breath. This bow came to meet you at that threshold, when what comes next asks for courage, presence and trust.',
  'You do not need to become someone else to be ready. You do not have to turn into an impossible version of yourself. Enter as you are: the girl who has worked, learned, insisted and returned again and again to what she loves.',
  'Readiness is not the absence of fear. It is carrying everything you have built with you, even while a little nervousness still lives in your chest. Your hours, devotion and constancy do not vanish when nerves arrive.',
  'Step forward with your head high and kindness toward yourself. Do not demand perfection before allowing yourself to enjoy your own radiance. Your presence is valuable before the very first move.',
  'This bow chose you to say something simple and powerful: what you have cultivated within yourself is real. When the moment arrives, it will know how to accompany you.'
 ],es:[
  'Hay una elegancia particular en los momentos que preceden a un gran paso. El aire, el cuarto y el corazón parecen contener la respiración. Este lazo llegó para encontrarte en ese umbral, cuando lo que viene pide valor, presencia y confianza.',
  'No necesitas volverte otra persona para estar lista. No tienes que convertirte en una versión imposible de ti misma. Entra siendo tú: la niña que ha trabajado, aprendido, insistido y vuelto una y otra vez a lo que ama.',
  'Estar lista no significa no sentir miedo. Significa llevar contigo todo lo que has construido, incluso si aún late un poco de nervio en tu pecho. Tus horas, tu entrega y tu constancia no desaparecen cuando llegan los nervios.',
  'Avanza con la frente en alto y con bondad hacia ti misma. No te exijas perfección para permitirte disfrutar tu propio brillo. Tu presencia ya es valiosa antes del primer movimiento.',
  'Este lazo te eligió para decirte algo sencillo y poderoso: lo que has cultivado dentro de ti es real. Cuando llegue el momento, sabrá acompañarte.'
 ],signoff:{en:'Always beside you,',es:'Siempre a tu lado,'}},
 {id:'discipline',en:[
  'Not every beautiful thing reveals itself immediately. Some need time, repetition, patience and a quiet faith in what is still taking shape. This bow came because it recognizes that quality in you.',
  'Discipline has a severe reputation, but it can be a form of love: love translated into constancy, the love that returns, repeats and does not abandon a vision because it has not fully bloomed yet.',
  'Never underestimate your quiet habits. The days when progress seems small also count. They are the discreet days that eventually hold the most beautiful transformations together.',
  'You are meant not only for big moments, but also for depth and for the maturity of someone learning to believe before seeing the whole picture. That serene faith is a rare jewel.',
  'What you are planting is not in vain. Your constancy has a destination. The flower is never ashamed to open slowly. You should not be either.'
 ],es:[
  'No todas las bellezas se revelan de inmediato. Algunas necesitan tiempo, repetición, paciencia y una fe tranquila en lo que todavía se está formando. Este lazo llegó porque reconoce esa cualidad en ti.',
  'La disciplina tiene una reputación severa, pero puede ser una forma de amor: amor convertido en constancia, el amor que regresa, repite y no abandona una visión porque todavía no ha florecido por completo.',
  'Nunca subestimes tus hábitos silenciosos. Los días en que pareces avanzar poco también cuentan. Son esos días discretos los que terminan sosteniendo las transformaciones más bellas.',
  'No estás destinada solamente a los instantes grandes, sino también a la profundidad y a la madurez de quien aprende a creer antes de ver el cuadro completo. Esa fe serena es una joya rara.',
  'Lo que estás sembrando no es en vano. Tu constancia tiene destino. La flor no se avergüenza por abrirse poco a poco. Tú tampoco deberías.'
 ],signoff:{en:'With admiration,',es:'Con admiración,'}},
 {id:'confidence',en:[
  'Sometimes confidence hides like a shy firefly among the trees. It has not disappeared; it is simply harder to see. This bow found you to bring light to exactly that kind of moment.',
  'Do not wait to feel enormous before believing in yourself. Begin with what is already true: you can learn, grow, endure difficult days and gather yourself again when an experience unsettles your heart.',
  'The confidence that lasts is not always born from applause. It grows when you remember how many times you returned, when you decide not to abandon yourself, and when you look at yourself with more justice and less severity.',
  'Your light has not diminished. It may need rest, tenderness or time, but it is still there. It will keep growing if you treat it with love.',
  'Come back to this letter like returning to an open window. Breathe. Lift your spirit. You do not have to prove that you deserve your own radiance. You were born carrying it.'
 ],es:[
  'A veces la confianza se esconde como una luciérnaga tímida entre los árboles. No ha desaparecido; simplemente cuesta verla. Este lazo te encontró para alumbrarte precisamente en esa clase de instante.',
  'No esperes sentirte inmensa para empezar a creer en ti. Comienza por lo que ya es cierto: puedes aprender, crecer, sostener días difíciles y volver a reunir tus pedacitos cuando algo desordena tu corazón.',
  'La confianza que permanece no siempre nace del aplauso. Crece cuando recuerdas cuántas veces has regresado, cuando decides no abandonarte y cuando te miras con más justicia y menos dureza.',
  'Tu luz no ha disminuido. Tal vez necesite reposo, ternura o tiempo, pero sigue allí. Continuará creciendo si la tratas con amor.',
  'Vuelve a esta carta como quien regresa a una ventana abierta. Respira. Endereza el alma. No tienes que demostrar que mereces tu propio brillo. Ya naciste con él.'
 ],signoff:{en:'With gentleness and faith in you,',es:'Con suavidad y fe en ti,'}},
 {id:'own-time',en:[
  'The heart sometimes becomes restless when others seem to move faster, more clearly or more easily. This bow came to return you to the sacred rhythm of your own path.',
  'You are not late for your life. You are not behind your destiny. Comparison tells an incomplete and unkind story: it shows someone else’s shine while hiding their pauses, doubts and invisible work.',
  'There is growth in slowness and beauty in what refuses to rush merely to look finished. Your way of learning, persisting and blooming does not need to resemble anyone else’s to be real.',
  'This bow sees a promise in you, not a race you have lost. It sees a story still unfolding, not an opportunity that has passed.',
  'Continue not as someone desperately chasing a place, but as someone who knows the place meant for her is also waiting. What is yours will know how to recognize you.'
 ],es:[
  'A veces el corazón se inquieta cuando otras parecen avanzar con más rapidez, claridad o facilidad. Este lazo llegó para devolverte al ritmo sagrado de tu propio camino.',
  'No estás tarde para tu vida. No vas detrás de tu destino. La comparación cuenta una historia incompleta y cruel: muestra el brillo ajeno mientras esconde sus pausas, dudas y trabajo invisible.',
  'Hay crecimiento en lo lento y belleza en aquello que no se apresura solo para parecer terminado. Tu forma de aprender, insistir y florecer no necesita parecerse a la de nadie para ser verdadera.',
  'Este lazo ve una promesa en ti, no una carrera perdida. Ve una historia que sigue desplegándose, no una oportunidad que pasó.',
  'Continúa no como quien persigue desesperadamente un lugar, sino como quien sabe que el lugar que le pertenece también la espera. Lo tuyo sabrá reconocerte.'
 ],signoff:{en:'With serenity,',es:'Con serenidad,'}}
];

