import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import BowracleShare from './BowracleShare.jsx';
import {cleanFirstName} from './tarot/readingEngine.js';
import {SECRET_MESSAGE_UI,ENCHANTED_HOUSES} from './secretMessageContent.js';
import {MASHUKI_LETTERS_BY_ID} from './mashukiLettersV1.js';
import {MASHUKI_LETTERS_EN_V1} from './mashukiLettersEnglishV1.js';
import {createSecretHouseSvg,createSecretLetterSvg} from './secretKeepsakeSvg.js';

const fill=(value,vars={})=>String(value).replace(/\{(\w+)\}/g,(_,key)=>vars[key]??`{${key}}`);
const spanishGardenCopy=value=>String(value).replaceAll('House of Poise','Casa del Equilibrio').replaceAll('House of Velocity','Casa de la Velocidad').replaceAll('House of Power','Casa de la Fuerza').replaceAll('House of Flight','Casa del Vuelo').replaceAll('bows','lazos').replaceAll('bow','lazo').replaceAll('Catch the rhythm.','Encuentra el ritmo.').replaceAll('Trust the motion.','Confía en el movimiento.').replaceAll('Trust the rise.','Confía en el impulso.').replaceAll('Leave room for wonder.','Deja espacio para el asombro.');
const asset=name=>`/assets/bowracle/secret-garden/bowracle-secret-${name==='letter'?'letter-v2':name}.webp`;
function AtmosphericImage({name}){return <div className="bem-scene-art" aria-hidden="true">{name==='garden-desktop'?<picture><source media="(max-width:760px)" srcSet={asset('garden-mobile')}/><img src={asset(name)} alt=""/></picture>:<img src={asset(name)} alt=""/>}<span className="bem-scene-mist"/><span className="bem-scene-prism"/><span className="bem-particles">{Array.from({length:18},(_,index)=><i key={index} style={{'--particle-index':index,'--particle-x':`${(index*37+11)%96}%`,'--particle-y':`${(index*53+7)%91}%`,'--particle-size':`${2+(index%4)}px`}}/>)}</span></div>;}

export function SecretMessageEntry({locale,onEnter}){const ui=SECRET_MESSAGE_UI[locale];return <section className="bem-entry" aria-labelledby="bem-entry-title"><AtmosphericImage name="garden-desktop"/><div className="bem-entry-copy"><p className="br-kicker">{ui.entryEyebrow}</p><h1 id="bem-entry-title">{ui.entryTitle}</h1><p className="bem-entry-lede">{ui.entryCopy}</p><p>{ui.entryBody}</p><button className="br-button bem-primary" type="button" onClick={onEnter}>{ui.entryCta}<span aria-hidden="true">→</span></button><small>PRFCT10 PLAY · THE ENCHANTED BOW MESSAGE</small></div></section>;}
export function SecretRecognition({locale}){const ui=SECRET_MESSAGE_UI[locale];return <section className="bem-recognition" role="status"><AtmosphericImage name="recognition"/><div className="bem-recognition-copy"><p>{ui.transition[0]}</p><h1>{ui.transition[1]}</h1><p>{ui.transition[2]}</p><small>{ui.transition[3]}</small></div></section>;}

export default function SecretMessageExperience({result,firstName,locale,t,onRestart,onHandoff}){
 const [phase,setPhase]=useState('letter'),[letterFormat,setLetterFormat]=useState('story'),[houseFormat,setHouseFormat]=useState('story');
 const heading=useRef(null),ui=SECRET_MESSAGE_UI[locale],name=cleanFirstName(firstName)||ui.traveler;
 const canonicalLetter=MASHUKI_LETTERS_BY_ID.get(result.messageId),english=MASHUKI_LETTERS_EN_V1[result.messageId],letter=canonicalLetter&&english?{...canonicalLetter,title:{...canonicalLetter.title,en:english.title},body:{...canonicalLetter.body,en:english.body},signoff:{...canonicalLetter.signoff,en:english.signoff}}:canonicalLetter,house=ENCHANTED_HOUSES[result.secretHouse]?.[locale];
 const paragraphs=(letter?.body?.[locale]||letter?.body?.es||[]).map(text=>locale==='es'?spanishGardenCopy(text):text);
 const date=useMemo(()=>{const raw=result.secretDate||new Date().toISOString().slice(0,10);try{return new Intl.DateTimeFormat(locale==='es'?'es-US':'en-US',{dateStyle:'long',timeZone:'UTC'}).format(new Date(raw+'T00:00:00Z'));}catch{return raw;}},[locale,result.secretDate]);
 useEffect(()=>{heading.current?.closest('section')?.scrollIntoView({block:'start',behavior:'auto'});heading.current?.focus({preventScroll:true});},[phase]);
 const letterRenderer=useCallback((r,translate,format)=>createSecretLetterSvg({result:r,name,house,letter,locale,date},translate,format),[name,house,letter,locale,date]);
 const houseRenderer=useCallback((r,translate,format)=>createSecretHouseSvg({result:r,name,house,letter,locale,date},translate,format),[name,house,letter,locale,date]);
 if(!letter||!house)return <section className="bem-letter"><article className="bem-letter-paper"><h1>{ui.invalid}</h1><p>{ui.invalidHelp}</p><button className="br-button" type="button" onClick={onRestart}>{ui.return}</button></article></section>;
 if(phase==='letter')return <section className="bem-letter" aria-labelledby="bem-letter-title"><AtmosphericImage name="letter"/><article className="bem-letter-paper"><p className="br-kicker">{ui.letterTitle}</p><h1 id="bem-letter-title" ref={heading} tabIndex={-1}>{name}</h1><div className="bem-letter-meta"><span>{fill(ui.opened,{date})}</span><span>{ui.from}</span></div><h2>{letter.title[locale]||letter.title.es}</h2><div className="bem-letter-body"><p className="bem-dear">{locale==='es'?`Querida ${name}:`:`Dear ${name}:`}</p>{paragraphs.map((text,index)=><p key={index}>{fill(text,{FIRST_NAME:name})}</p>)}<p className="bem-signature">{letter.signoff[locale]||letter.signoff.es}<strong>Mashuki</strong></p></div><button className="br-button bem-primary" type="button" onClick={()=>setPhase('house')}>{ui.continueHouse}<span aria-hidden="true">→</span></button></article></section>;
 if(phase==='house')return <section className="bem-house" aria-labelledby="bem-house-title"><AtmosphericImage name="house"/><div className="bem-house-copy"><p className="br-kicker">{ui.houseCopy}</p><h1 id="bem-house-title" ref={heading} tabIndex={-1}>{ui.belongs}<em>{house.name}</em></h1><p className="bem-house-words">{house.words}</p><blockquote>{house.motto}</blockquote><p>{house.description}</p><div className="br-actions"><button className="br-button bem-primary" type="button" onClick={()=>setPhase('keepsake')}>{ui.continueKeepsake}<span aria-hidden="true">→</span></button><button className="br-link" type="button" onClick={()=>setPhase('letter')}>{locale==='es'?'Leer de nuevo':'Read again'}</button></div></div></section>;
 return <section className="bem-keepsake" aria-labelledby="bem-keepsake-title"><AtmosphericImage name="keepsake"/><div className="bem-keepsake-actions"><p className="br-kicker">THE ENCHANTED BOW MESSAGE</p><h1 id="bem-keepsake-title" ref={heading} tabIndex={-1}>{ui.keepsakeTitle}</h1><p>{ui.keepsakeCopy}</p><div className="bem-collectibles"><article className="bem-collectible"><span>01</span><h2>{ui.letterCollectible}</h2><blockquote>{paragraphs[0]}</blockquote><BowracleShare result={result} t={t} format={letterFormat} onFormat={setLetterFormat} renderSvg={letterRenderer} cardKind="mashuki-letter" labels={{download:ui.saveLetter,share:ui.shareLetter,aria:ui.letterCollectible,filename:'PRFCT10-MASHUKI-LETTER'}}/></article><article className="bem-collectible bem-collectible--house"><span>02</span><h2>{ui.houseCollectible}</h2><strong>{house.name}</strong><p>{house.words}</p><BowracleShare result={result} t={t} format={houseFormat} onFormat={setHouseFormat} renderSvg={houseRenderer} cardKind="bow-house" labels={{download:ui.downloadHouse,share:ui.shareHouse,aria:ui.houseCollectible,filename:'PRFCT10-BOW-HOUSE'}}/></article></div><div className="br-actions">{onHandoff&&<button className="br-button bem-primary" type="button" onClick={()=>onHandoff(result)}>{ui.seeBow} →</button>}<button className="br-link" type="button" onClick={()=>setPhase('letter')}>{locale==='es'?'Leer de nuevo':'Read again'}</button><button className="br-link" type="button" onClick={onRestart}>← {ui.return}</button></div></div></section>;
}
