import { GYMNAST_DATA_VERSION } from "./gymnastEngine.js";

const accessedAt = "2026-09-02";
const masterRoster = [
  ["Simone Biles","USA"],["Rebeca Andrade","BRA"],["Kaylia Nemour","ALG"],["Zhou Yaqin","CHN"],["Alexa Moreno","MEX"],["Jade Carey","USA"],["Flávia Saraiva","BRA"],["Sabrina Maneca-Voinea","ROU"],["Aliya Mustafina","RUS"],["Aly Raisman","USA"],
  ["Sanne Wevers","NED"],["Cătălina Ponor","ROU"],["McKayla Maroney","USA"],["Nina Derwael","BEL"],["Mai Murakami","JPN"],["Angelina Melnikova","RUS"],["Gabby Douglas","USA"],["Vanessa Ferrari","ITA"],["Oksana Chusovitina","UZB"],["Nadia Comăneci","ROU"],
  ["Daiane dos Santos","BRA"],["Cheng Fei","CHN"],["Beth Tweddle","GBR"],["Jessica López","VEN"],["Elena Gómez","ESP"],["Yelena Produnova","RUS"],["Lilia Podkopayeva","UKR"],["Elvire Teza","FRA"],["Sunisa Lee","USA"],["Yeo Seo-jeong","KOR"],
  ["Morgan Hurd","USA"],["Claire Pease","USA"],["Charleigh Bullock","USA"],["Hezly Rivera","USA"],["Aleah Finnegan","PHI"],["Emma Malabuyo","PHI"],["Levi Jung-Ruivivar","PHI"],["Luisa Blanco","COL"],["Lynnzee Brown","HAI"],["Manila Esposito","ITA"],
  ["Alice D’Amato","ITA"],["Angela Andreoli","ITA"],["Giulia Perotti","ITA"],["Giorgia Campana","ITA"],["Elena Colas","FRA"],["Mélanie de Jesus dos Santos","FRA"],["Coline Devillard","FRA"],["Morgane Osyssek-Reimer","FRA"],["Ana Sofía Gómez Porras","GUA"],["Hillary Heron","PAN"],
  ["Karla Navas","PAN"],["Marcia Videaux","CUB"],["Mía Mainardi","ARG"],["Ruby Pass","AUS"],["Georgia Godwin","AUS"],["Ellie Black","CAN"],["Aurélie Tran","CAN"],["Ava Stewart","CAN"],["Qiu Qiyuan","CHN"],["Helen Kevric","GER"],
  ["Ágnes Keleti","HUN"],["Larisa Latynina","URS"],["Věra Čáslavská","TCH"],["Ludmilla Tourischeva","URS"],["Olga Korbut","URS"],["Nellie Kim","URS"],["Maxi Gnauck","GDR"],["Ma Yanhong","CHN"],["Natalia Yurchenko","URS"],["Ecaterina Szabo","ROU"],
  ["Elena Shushunova","URS"],["Daniela Silivaș","ROU"],["Svetlana Boginskaya","BLR"],["Henrietta Ónodi","HUN"],["Shannon Miller","USA"],["Dominique Dawes","USA"],["Dianne Durham","USA"],["Svetlana Khorkina","RUS"],["Simona Amânar","ROU"],["Yang Bo","CHN"],
  ["Ou Yushan","CHN"],["Zhang Qingying","CHN"],["Tang Xijing","CHN"],["Fan Yilin","CHN"],["Guan Chenchen","CHN"],["Shoko Miyata","JPN"],["Urara Ashikawa","JPN"],["Mana Okamura","JPN"],["Hazuki Watanabe","JPN"],["Dipa Karmakar","IND"],
  ["Phan Thị Hà Thanh","VIE"],["Ting Hua-tien","TPE"],["An Chang-ok","PRK"],["Viktoriia Listunova","RUS"],["Vladislava Urazova","RUS"],["Maria Paseka","RUS"],["Ksenia Afanasyeva","RUS"],["Ana Bărbosu","ROU"],["Larisa Iordache","ROU"],["Sandra Izbașa","ROU"]
];

const countryNames = { USA:["United States","Estados Unidos"],BRA:["Brazil","Brasil"],ALG:["Algeria","Argelia"],CHN:["China","China"],MEX:["Mexico","México"],ROU:["Romania","Rumania"],RUS:["Russia","Rusia"],NED:["Netherlands","Países Bajos"],BEL:["Belgium","Bélgica"],JPN:["Japan","Japón"],ITA:["Italy","Italia"],UZB:["Uzbekistan","Uzbekistán"] };
const noElement = { relation:"NO_DOCUMENTED_RELATION", officialName:null, apparatus:null, figCodeCycle:null, figElementNumber:null, officialDescription:null, relationExplanation:{ en:"This file celebrates a documented sporting moment and makes no named-element claim.", es:"Este expediente celebra un momento deportivo documentado y no afirma una relación con un elemento epónimo." } };
const clearedAsset = { silhouettePath:null, photoPath:null, sourceAssetUrl:null, creatorOrOwner:"PRFCT10 design team", licenseType:"Original non-identifying code-rendered composition", licenseEvidencePath:"/images/play/GYMNAST_OF_DAY_ORIGINALITY.md", attributionText:"Original PRFCT10 abstract artwork", transformedFromPhoto:false, alt:{ en:"Abstract gymnast figure surrounded by stars and geometric lines", es:"Figura abstracta de una gimnasta rodeada de estrellas y líneas geométricas" }, rightsStatus:"CLEARED" };
const figSource = (url,title,supports) => ({ url,title,publisher:"International Gymnastics Federation (FIG) / World Gymnastics",accessedAt,sourceType:"FIG",supports });
const pair = (en,es) => ({en,es});

function stagingRecord(index, name, nation) {
  const id = `GYM-${String(index + 1).padStart(3,"0")}`;
  const nextId = offset => `GYM-${String(((index + offset) % 100) + 1).padStart(3,"0")}`;
  return {
    id,
    identity:{visibleName:name,fullName:name,aliases:[],currentNation:nation,representedDelegations:[nation]},
    classification:{category:index >= 60 ? "HISTORICAL_LEGEND" : "FAN_FAVORITE",careerStatus:"UNKNOWN",profileType:"MIXED",featuredEvents:[],eraTags:[]},
    game:{difficulty:"COMPETITIVE",clues:{en:["Editorial verification pending.","Editorial verification pending.","Editorial verification pending."],es:["Verificación editorial pendiente.","Verificación editorial pendiente.","Verificación editorial pendiente."]},answerGymnastId:id,distractorGymnastIds:[nextId(1),nextId(2),nextId(3)],revealTitle:pair("File pending","Expediente pendiente"),revealStory:pair("This file is not cleared for publication.","Este expediente no está autorizado para publicación."),power:{key:"pending",label:pair("Pending","Pendiente"),message:pair("Editorial review comes first.","La revisión editorial es lo primero.")}},
    featuredMoment:{year:null,competition:pair("Pending verification","Verificación pendiente"),apparatus:null,representedDelegation:nation,verifiedResult:pair("Pending verification","Verificación pendiente")},
    element:noElement,sources:[],assets:{...clearedAsset,rightsStatus:"PENDING"},
    review:{factualStatus:"UNVERIFIED",technicalStatus:"UNVERIFIED",translationStatus:"INCOMPLETE",rightsStatus:"PENDING",reviewedBy:null,reviewedAt:null,publishable:false,notes:["Staging record; research not started."]}
  };
}

const details = {
  "GYM-001": {category:"CURRENT",careerStatus:"ACTIVE",profileType:"ALL_AROUND",events:["VT","UB","BB","FX"],apparatus:"AA",year:2024,nation:"USA",competition:pair("Paris 2024 Olympic Games","Juegos Olímpicos de París 2024"),result:pair("Olympic all-around, team and vault champion; floor silver medallist","Campeona olímpica de concurso completo, equipos y salto; medallista de plata en suelo"),clues:{en:["I represent the United States and returned to the Olympic stage in 2024.","I won gold in the all-around, team and vault finals in Paris.","My Olympic all-around titles came eight years apart."],es:["Represento a Estados Unidos y regresé al escenario olímpico en 2024.","Gané oro en concurso completo, equipos y salto en París.","Mis títulos olímpicos del concurso completo llegaron con ocho años de diferencia."]},title:pair("A return to the all-around summit","Un regreso a la cima del concurso completo"),story:pair("Eight years after winning the Olympic all-around in Rio, Simone Biles won it again in Paris. She also earned team and vault gold plus floor silver, bringing her Olympic medal total to eleven.","Ocho años después de ganar el concurso completo olímpico en Río, Simone Biles volvió a conquistarlo en París. También ganó oro por equipos y salto, además de plata en suelo, para llegar a once medallas olímpicas."),power:["comeback",pair("COMEBACK MAGIC","MAGIA DEL REGRESO"),pair("A return can become a rise.","Un regreso puede convertirse en un ascenso.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4245542","Simone Biles, Oka Shinnosuke set the standard among gymnasts at Paris 2024",["identity.currentNation","featuredMoment","game.clues","game.revealStory"])},
  "GYM-002": {category:"CURRENT",careerStatus:"ACTIVE",profileType:"ALL_AROUND",events:["VT","UB","BB","FX"],apparatus:"FX",year:2024,nation:"BRA",competition:pair("Paris 2024 Olympic Games","Juegos Olímpicos de París 2024"),result:pair("Olympic floor champion, all-around and vault silver medallist, team bronze medallist","Campeona olímpica de suelo, plata en concurso completo y salto, y bronce por equipos"),clues:{en:["I represent Brazil and earned four medals in Paris.","My Paris medals included all-around and vault silver.","I closed the Games as the Olympic floor champion."],es:["Represento a Brasil y gané cuatro medallas en París.","Mis medallas en París incluyeron plata en concurso completo y salto.","Cerré los Juegos como campeona olímpica de suelo."]},title:pair("Brazilian history on the floor","Historia brasileña sobre el suelo"),story:pair("Rebeca Andrade won Paris floor gold, all-around and vault silver, and Brazil’s first women’s team bronze. FIG reported that the six Olympic medals across her career made her Brazil’s most successful Olympic athlete.","Rebeca Andrade ganó oro en suelo, plata en concurso completo y salto, y el primer bronce femenino por equipos de Brasil. La FIG informó que sus seis medallas olímpicas la convirtieron en la atleta olímpica más exitosa del país."),power:["spotlight",pair("SPOTLIGHT ENERGY","ENERGÍA DE SPOTLIGHT"),pair("Take the floor and make the moment yours.","Toma el escenario y haz tuyo el momento.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4245542","Simone Biles, Oka Shinnosuke set the standard among gymnasts at Paris 2024",["identity.currentNation","featuredMoment","game.clues","game.revealStory"])},
  "GYM-003": {category:"CURRENT",careerStatus:"ACTIVE",profileType:"SPECIALIST",events:["UB"],apparatus:"UB",year:2024,nation:"ALG",competition:pair("Paris 2024 Olympic Games","Juegos Olímpicos de París 2024"),result:pair("Olympic uneven bars champion with 15.700","Campeona olímpica de barras asimétricas con 15.700"),clues:{en:["I represented an African nation at the Paris Games.","My biggest stage is the uneven bars.","My 15.700 won Africa’s first Olympic gymnastics medal — a gold."],es:["Representé a una nación africana en los Juegos de París.","Mi gran escenario son las barras asimétricas.","Mi 15.700 ganó la primera medalla olímpica africana en gimnasia: un oro."]},title:pair("A continental first","Una primera vez para un continente"),story:pair("Kaylia Nemour delivered a 15.700 uneven bars routine in Paris to win Algeria’s first Olympic gymnastics medal and the first Olympic gymnastics medal for an African nation. She finished ahead of 2023 World champion Qiu Qiyuan.","Kaylia Nemour logró 15.700 en barras asimétricas en París para ganar la primera medalla olímpica de gimnasia de Argelia y de una nación africana. Terminó por delante de la campeona mundial de 2023, Qiu Qiyuan."),power:["flow",pair("FEARLESS FLOW","FLUIDEZ VALIENTE"),pair("Let preparation meet the moment.","Deja que la preparación encuentre su momento.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4242582","Golden Kaylia Nemour gives Africa an unforgettable Olympic title",["identity.currentNation","featuredMoment","game.clues","game.revealStory"])},
  "GYM-004": {category:"NEW_GENERATION",careerStatus:"ACTIVE",profileType:"SPECIALIST",events:["BB"],apparatus:"BB",year:2024,nation:"CHN",competition:pair("Paris 2024 Olympic Games","Juegos Olímpicos de París 2024"),result:pair("Olympic balance beam silver medallist","Medallista olímpica de plata en viga"),clues:{en:["I represent China and belong to a new Olympic generation.","Balance beam brought me a World medal before Paris.","I won Olympic beam silver in Paris at age eighteen."],es:["Represento a China y pertenezco a una nueva generación olímpica.","La viga me dio una medalla mundial antes de París.","Gané la plata olímpica en viga en París a los dieciocho años."]},title:pair("Silver on the narrowest stage","Plata en el escenario más estrecho"),story:pair("Zhou Yaqin arrived in Paris already a World balance beam medallist and earned Olympic silver on the apparatus. Her Paris result is kept separate from her 2023 World Championship achievement in this file.","Zhou Yaqin llegó a París como medallista mundial de viga y ganó la plata olímpica en ese aparato. Este expediente mantiene separado su resultado en París de su logro en el Mundial de 2023."),power:["balance",pair("STEADY LINE","LÍNEA FIRME"),pair("Small adjustments can hold a big dream.","Pequeños ajustes pueden sostener un gran sueño.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4281814","Faces of the Games: from daring to caring, Zhou Yaqin finds fame in Paris",["identity.currentNation","featuredMoment","game.clues","game.revealStory"])},
  "GYM-005": {category:"FAN_FAVORITE",careerStatus:"ACTIVE",profileType:"SPECIALIST",events:["VT"],apparatus:"VT",year:2018,nation:"MEX",competition:pair("2018 World Championships in Doha","Mundial de 2018 en Doha"),result:pair("World vault bronze medallist; first Mexican woman to win a World artistic gymnastics medal","Bronce mundial en salto; primera mexicana en ganar una medalla mundial de gimnasia artística"),clues:{en:["I represent Mexico and competed at three Olympic Games through Paris 2024.","Vault is my featured event.","My 2018 World bronze was a first for Mexican women’s artistic gymnastics."],es:["Represento a México y competí en tres Juegos Olímpicos hasta París 2024.","El salto es mi aparato destacado.","Mi bronce mundial de 2018 fue el primero para la gimnasia artística femenina mexicana."]},title:pair("Mexico’s World podium first","El primer podio mundial de México"),story:pair("Alexa Moreno won vault bronze at the 2018 World Championships in Doha. The FIG athlete profile records the result as the first World Championship medal won by a woman representing Mexico in artistic gymnastics.","Alexa Moreno ganó bronce en salto en el Mundial de 2018 en Doha. El perfil de la FIG registra el resultado como la primera medalla mundial de gimnasia artística ganada por una mujer que representó a México."),power:["takeoff",pair("BRAVE TAKEOFF","DESPEGUE VALIENTE"),pair("Commit to the runway in front of you.","Comprométete con la pista que tienes delante.")],source:figSource("https://www.gymnastics.sport/site/athletes/bio_detail.php?id=27755&lang=en","MORENO Alexa — FIG Athlete Profile",["identity","classification.featuredEvents","featuredMoment","game.clues","game.revealStory"])},
  "GYM-006": {category:"CURRENT",careerStatus:"ACTIVE",profileType:"SPECIALIST",events:["VT","FX"],apparatus:"FX",year:2021,nation:"USA",competition:pair("Tokyo 2020 Olympic Games","Juegos Olímpicos de Tokio 2020"),result:pair("Olympic floor champion","Campeona olímpica de suelo"),clues:{en:["I represent the United States and am known for powerful vault and floor work.","I reached the Tokyo floor final through qualification.","I won Olympic floor gold in Tokyo."],es:["Represento a Estados Unidos y soy reconocida por mi potencia en salto y suelo.","Llegué a la final de suelo de Tokio por la clasificación.","Gané el oro olímpico de suelo en Tokio."]},title:pair("The next day can be golden","El día siguiente puede ser dorado"),story:pair("After a difficult vault final, Jade Carey returned the next day and won the Tokyo Olympic floor title. Her place in the floor final came through her own qualification result, not as a replacement.","Después de una difícil final de salto, Jade Carey regresó al día siguiente y ganó el título olímpico de suelo en Tokio. Su lugar en la final llegó por su propio resultado clasificatorio, no como reemplazo."),power:["reset",pair("NEXT-DAY RESET","REINICIO DEL DÍA SIGUIENTE"),pair("One hard turn does not write the ending.","Un momento difícil no escribe el final.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=3401613","Courageous acts, historic results defined Women’s Artistic Gymnastics in 2021",["featuredMoment","game.clues","game.revealStory"])},
  "GYM-007": {category:"CURRENT",careerStatus:"ACTIVE",profileType:"MIXED",events:["BB","FX"],apparatus:"TEAM",year:2024,nation:"BRA",competition:pair("Paris 2024 Olympic Games","Juegos Olímpicos de París 2024"),result:pair("Olympic team bronze medallist in Brazil’s first women’s team medal","Bronce olímpico por equipos en la primera medalla femenina por equipos de Brasil"),clues:{en:["I represent Brazil and first reached an Olympic stage as a Youth Olympian.","Beam and floor are featured parts of my international career.","I helped Brazil win its first Olympic women’s team medal in Paris."],es:["Represento a Brasil y llegué por primera vez a un escenario olímpico en los Juegos de la Juventud.","La viga y el suelo son aparatos destacados de mi carrera internacional.","Ayudé a Brasil a ganar su primera medalla olímpica femenina por equipos en París."]},title:pair("A team first for Brazil","Una primera vez por equipos para Brasil"),story:pair("Flávia Saraiva was part of the Brazilian team that won bronze in Paris, the country’s first Olympic women’s artistic gymnastics team medal. The achievement followed her three-medal Youth Olympic performance in 2014.","Flávia Saraiva integró el equipo brasileño que ganó bronce en París, la primera medalla olímpica por equipos de gimnasia artística femenina del país. El logro llegó después de sus tres medallas en los Juegos Olímpicos de la Juventud de 2014."),power:["team",pair("TEAM GLOW","BRILLO DE EQUIPO"),pair("History can be made together.","La historia también se construye juntas.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4359668","Fame, fashion, and fun: inside Rebeca Andrade’s post-Paris world",["featuredMoment","game.clues","game.revealStory"])},
  "GYM-008": {category:"NEW_GENERATION",careerStatus:"ACTIVE",profileType:"MIXED",events:["BB","FX"],apparatus:"FX",year:2023,nation:"ROU",competition:pair("2023 FIG World Cup season","Temporada 2023 de Copas del Mundo FIG"),result:pair("Won two World Cup gold medals in her first senior season","Ganó dos oros de Copa del Mundo en su primera temporada sénior"),clues:{en:["I represent Romania and entered the senior ranks in 2023.","Beam and floor were my medal events during my first senior season.","I won two FIG World Cup gold medals as a first-year senior."],es:["Represento a Rumania y entré a la categoría sénior en 2023.","La viga y el suelo fueron mis aparatos de medalla en mi primera temporada sénior.","Gané dos oros de Copa del Mundo FIG en mi primer año como sénior."]},title:pair("A fast senior arrival","Una llegada sénior veloz"),story:pair("Sabrina Maneca-Voinea made an immediate impact in her first senior season, earning FIG World Cup medals on balance beam and floor. This file focuses on those documented results and excludes controversy and unverified element claims.","Sabrina Maneca-Voinea causó impacto en su primera temporada sénior al ganar medallas de Copa del Mundo FIG en viga y suelo. Este expediente se concentra en esos resultados documentados y excluye controversias y elementos no verificados."),power:["arrival",pair("READY ARRIVAL","LLEGADA LISTA"),pair("You can belong on a new stage.","Puedes pertenecer a un escenario nuevo.")],source:figSource("https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4091814","Athlete inspiration: Believe in your dreams! says Sabrina Maneca-Voinea",["identity.currentNation","classification","featuredMoment","game.clues","game.revealStory"])},
  "GYM-009": {category:"HISTORICAL_LEGEND",careerStatus:"RETIRED",profileType:"ALL_AROUND",events:["VT","UB","BB","FX"],apparatus:"UB",year:2016,nation:"RUS",competition:pair("Rio 2016 Olympic Games","Juegos Olímpicos de Río 2016"),result:pair("Retained the Olympic uneven bars title","Revalidó el título olímpico de barras asimétricas"),clues:{en:["I represented Russia and became World all-around champion in 2010.","I earned four medals at the London Games.","I retained my Olympic uneven bars title in Rio."],es:["Representé a Rusia y fui campeona mundial del concurso completo en 2010.","Gané cuatro medallas en los Juegos de Londres.","Revalidé mi título olímpico de barras asimétricas en Río."]},title:pair("Back-to-back bars gold","Dos oros consecutivos en barras"),story:pair("Aliya Mustafina won Olympic uneven bars gold in London and retained the title four years later in Rio. FIG’s All Time Greats profile also records her 2010 World all-around title and seven Olympic medals across the two Games.","Aliya Mustafina ganó el oro olímpico de barras asimétricas en Londres y revalidó el título cuatro años después en Río. El perfil histórico de la FIG también registra su título mundial del concurso completo de 2010 y siete medallas olímpicas en ambos Juegos."),power:["repeat",pair("REPEAT POWER","PODER DE REPETIR"),pair("One title is a moment; defending it is another challenge.","Un título es un momento; defenderlo es otro desafío.")],source:figSource("https://www.gymnastics.sport/site/athletes/atg_view.php","World Gymnastics — All Time Greats",["identity","classification","featuredMoment","game.clues","game.revealStory"])},
  "GYM-010": {category:"HISTORICAL_LEGEND",careerStatus:"RETIRED",profileType:"ALL_AROUND",events:["VT","UB","BB","FX"],apparatus:"FX",year:2012,nation:"USA",competition:pair("London 2012 Olympic Games","Juegos Olímpicos de Londres 2012"),result:pair("Olympic team and floor champion; balance beam bronze medallist","Campeona olímpica por equipos y suelo; bronce en viga"),clues:{en:["I represented the United States at two Olympic Games.","I won team gold in both London and Rio.","I became the London 2012 Olympic floor champion."],es:["Representé a Estados Unidos en dos Juegos Olímpicos.","Gané oro por equipos tanto en Londres como en Río.","Fui campeona olímpica de suelo en Londres 2012."]},title:pair("The final floor title in London","El último título de suelo en Londres"),story:pair("Aly Raisman won team and floor gold plus beam bronze at London 2012. She returned in Rio to earn another team gold and silver medals in the all-around and floor finals.","Aly Raisman ganó oro por equipos y suelo, además de bronce en viga, en Londres 2012. Regresó en Río para ganar otro oro por equipos y platas en las finales de concurso completo y suelo."),power:["lead",pair("STEADY LEAD","LIDERAZGO FIRME"),pair("Consistency can carry a whole team.","La constancia puede sostener a todo un equipo.")],source:figSource("https://www.gymnastics.sport/site/athletes/bio_detail.php?id=29954","RAISMAN Alexandra — FIG Athlete Profile",["identity","classification","featuredMoment","game.clues","game.revealStory"])}
};

// Editorial pass 2026-09-02: clue order is intentionally competition-first.
// Country and identity signals are reserved for the reveal, never clue one.
const editorialUpgrades = {
  "GYM-001": {difficulty:"ACCESSIBLE",distractors:["GYM-002","GYM-004","GYM-009"],clues:{en:["At the 2023 World beam final, my 6.5 difficulty matched the gymnast who finished one tenth behind me.","In Paris qualification, I became the first woman to land a Yurchenko double pike in Olympic competition.","My Paris haul was team, all-around and vault gold, plus floor silver."],es:["En la final mundial de viga de 2023, mi dificultad de 6.5 igualó la de la gimnasta que terminó una décima detrás de mí.","En la clasificación de París, fui la primera mujer en aterrizar un Yurchenko doble mortal carpado en una competición olímpica.","Mi cosecha en París fue oro por equipos, concurso completo y salto, más plata en suelo."]},clueSources:["https://www.gymnastics.sport/site/news/displaynews.php?urlNews=399669","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4220677","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4245542"],rationale:"Andrade shares the Paris all-around stage; Zhou shares the 2023 World beam final; Mustafina is an Olympic all-around champion from an adjacent era."},
  "GYM-002": {difficulty:"COMPETITIVE",distractors:["GYM-001","GYM-007","GYM-006"],clues:{en:["I ranked second in Paris all-around qualification with 57.700.","My Paris podiums included all-around and vault silver, plus a historic team bronze.","I ended the Games with floor gold and six career Olympic medals, a national record."],es:["Terminé segunda en la clasificación del concurso completo de París con 57.700.","Mis podios en París incluyeron plata en concurso completo y salto, además de un bronce histórico por equipos.","Cerré los Juegos con oro en suelo y seis medallas olímpicas en mi carrera, un récord nacional."]},clueSources:["https://www.gymnastics.sport/asset.php?id=fidb_16652","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4245542","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4245542"],rationale:"Biles shares the Paris all-around and vault podiums; Saraiva shares the historic team bronze; Carey is a contemporary Olympic floor champion."},
  "GYM-003": {difficulty:"COMPETITIVE",distractors:["GYM-009","GYM-008","GYM-004"],clues:{en:["A 2023 World uneven-bars silver set up my Olympic rematch with that event’s World champion.","I scored 15.700 in the Paris uneven-bars final.","That routine delivered the first Olympic gymnastics medal for an African nation — and it was gold."],es:["Una plata mundial de barras asimétricas en 2023 preparó mi revancha olímpica con la campeona mundial de ese aparato.","Obtuve 15.700 en la final de barras asimétricas de París.","Esa rutina produjo la primera medalla olímpica de gimnasia para una nación africana, y fue de oro."]},clueSources:["https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4242582","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4242582","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4242582"],rationale:"Mustafina is an Olympic bars champion; Maneca-Voinea and Zhou are same-generation apparatus specialists with major 2023–24 results."},
  "GYM-004": {difficulty:"EXPERT",distractors:["GYM-008","GYM-007","GYM-001"],clues:{en:["At my senior World debut, I matched the beam champion’s 6.5 difficulty and finished only 0.1 behind.","Months later in Cottbus, I won both beam and floor with 14.900 and 13.733.","At eighteen, I added Olympic balance-beam silver in Paris."],es:["En mi debut mundial sénior, igualé la dificultad de 6.5 de la campeona de viga y terminé solo 0.1 detrás.","Meses después, en Cottbus, gané viga y suelo con 14.900 y 13.733.","A los dieciocho años, añadí una plata olímpica en viga en París."]},clueSources:["https://www.gymnastics.sport/site/news/displaynews.php?urlNews=399669","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4281814","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4281814"],rationale:"Maneca-Voinea is a same-generation beam/floor World Cup winner; Saraiva is a current beam/floor finalist; Biles shared the cited World beam final."},
  "GYM-005": {difficulty:"COMPETITIVE",distractors:["GYM-001","GYM-002","GYM-006"],clues:{en:["In Doha 2018, my two-vault average of 14.466 qualified me fourth to the World final.","A 14.508 average in that final moved me onto the bronze-medal step.","The medal was the first World artistic-gymnastics medal won by a woman representing Mexico."],es:["En Doha 2018, mi promedio de 14.466 en dos saltos me clasificó cuarta para la final mundial.","Un promedio de 14.508 en esa final me llevó al escalón de bronce.","La medalla fue la primera mundial de gimnasia artística ganada por una mujer que representaba a México."]},clueSources:["https://www.gymnastics.sport/asset.php?id=fidb_7803","https://www.gymnastics.sport/site/athletes/bio_detail.php?id=27755&lang=en","https://www.gymnastics.sport/site/athletes/bio_detail.php?id=27755&lang=en"],rationale:"Biles shared the 2018 vault final; Andrade and Carey are contemporary Olympic vault finalists and medal contenders."},
  "GYM-006": {difficulty:"COMPETITIVE",distractors:["GYM-002","GYM-010","GYM-001"],clues:{en:["I entered the Tokyo floor final as the third-ranked qualifier, then scored 14.366.","My win extended one nation’s Olympic floor streak after the 2012 and 2016 champions.","The title came one day after I tripped on the vault runway and finished outside the medals."],es:["Entré a la final de suelo de Tokio como la tercera clasificada y luego marqué 14.366.","Mi victoria extendió la racha olímpica de suelo de una nación después de las campeonas de 2012 y 2016.","El título llegó un día después de que tropezara en la pista de salto y quedara fuera de las medallas."]},clueSources:["https://www.gymnastics.sport/asset.php?id=fidb_11177","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=3266302","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=3266302"],rationale:"Andrade shared the Tokyo floor final; Raisman and Biles are the two preceding Olympic floor champions named by FIG."},
  "GYM-007": {difficulty:"EXPERT",distractors:["GYM-002","GYM-004","GYM-010"],clues:{en:["At Nanjing 2014, I collected Youth Olympic gold on floor and silver in both all-around and beam.","Before the Paris team final, a warm-up fall cut my eyebrow and I reduced my floor difficulty.","I still competed as my team earned its country’s first Olympic women’s team medal."],es:["En Nankín 2014, gané oro olímpico juvenil en suelo y plata tanto en concurso completo como en viga.","Antes de la final por equipos de París, una caída en el calentamiento me abrió la ceja y reduje la dificultad de mi suelo.","Aun así competí mientras mi equipo lograba la primera medalla olímpica femenina por equipos de su país."]},clueSources:["https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4209488","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=4231363","https://www.gymnastics.sport/asset.php?id=fidb_16652"],rationale:"Andrade shared the Paris team medal; Zhou overlaps on beam/floor and generation; Raisman is an Olympic team and floor medallist."},
  "GYM-008": {difficulty:"EXPERT",distractors:["GYM-004","GYM-003","GYM-007"],clues:{en:["My first senior World Cup beam routine linked three separate multi-skill acrobatic sequences.","At fifteen, I swept beam and floor gold on my World Cup debut in Doha.","My coach is also my mother, a 1988 Olympic team medallist."],es:["Mi primera rutina sénior de Copa del Mundo en viga enlazó tres secuencias acrobáticas de varios elementos.","A los quince años, gané oro en viga y suelo en mi debut de Copa del Mundo en Doha.","Mi entrenadora también es mi madre, medallista olímpica por equipos en 1988."]},clueSources:["https://www.gymnastics.sport/site/news/displaynews.php?urlNews=377685","https://www.gymnastics.sport/site/news/displaynews.php?urlNews=377685","https://www.gymnastics.sport/site/athletes/bio_detail.php?id=79916"],rationale:"Zhou also swept beam/floor at a 2024 World Cup; Nemour and Saraiva are contemporary beam/floor specialists with international medals."},
  "GYM-009": {difficulty:"COMPETITIVE",distractors:["GYM-003","GYM-010","GYM-001"],clues:{en:["A World all-around title in 2010 preceded a four-medal Olympic campaign in London.","I won uneven-bars gold in London, then defended that apparatus title four years later.","Across London and Rio, I collected seven Olympic medals."],es:["Un título mundial del concurso completo en 2010 precedió una campaña olímpica de cuatro medallas en Londres.","Gané oro en barras asimétricas en Londres y defendí ese título cuatro años después.","Entre Londres y Río, reuní siete medallas olímpicas."]},clueSources:["https://www.gymnastics.sport/site/athletes/atg_view.php","https://www.gymnastics.sport/site/athletes/atg_view.php","https://www.gymnastics.sport/site/athletes/atg_view.php"],rationale:"Nemour is an Olympic bars champion; Raisman and Biles are Olympic all-around-era multi-medallists with London/Rio overlap."},
  "GYM-010": {difficulty:"COMPETITIVE",distractors:["GYM-006","GYM-009","GYM-002"],clues:{en:["My London medal set covered team, balance beam and floor.","Four years later, I added team gold plus all-around and floor silver.","In the first of those Games, I became Olympic floor champion."],es:["Mi colección de medallas en Londres abarcó equipos, viga y suelo.","Cuatro años después, añadí oro por equipos y plata en concurso completo y suelo.","En el primero de esos Juegos, me convertí en campeona olímpica de suelo."]},clueSources:["https://www.gymnastics.sport/site/athletes/bio_detail.php?id=29954","https://www.gymnastics.sport/site/athletes/bio_detail.php?id=29954","https://www.gymnastics.sport/site/athletes/bio_detail.php?id=29954"],rationale:"Carey and Andrade are Olympic floor champions; Mustafina shares the London/Rio multi-medal arc."}
};

function completeRecord(base, detail) {
  const upgrade = editorialUpgrades[base.id] || {};
  const names = countryNames[detail.nation] || [detail.nation,detail.nation];
  const sourceMap = new Map([detail.source,...(upgrade.clueSources||[]).map((url,index)=>figSource(url,`Official FIG evidence for clue ${index+1}`,[`game.clues.en.${index}`,`game.clues.es.${index}`]))].map(source=>[source.url,source]));
  const difficulty = base.id === "GYM-002" ? "ACCESSIBLE" : (upgrade.difficulty||"COMPETITIVE");
  return {...base,
    identity:{...base.identity,currentNation:detail.nation,representedDelegations:[detail.nation]},
    classification:{category:detail.category,careerStatus:detail.careerStatus,profileType:detail.profileType,featuredEvents:detail.events,eraTags:[String(detail.year)]},
    game:{difficulty,clues:upgrade.clues||detail.clues,answerGymnastId:base.id,distractorGymnastIds:upgrade.distractors||base.game.distractorGymnastIds,distractorRationale:upgrade.rationale||"Pending editorial rationale.",clueSourceUrls:upgrade.clueSources||[],revealTitle:detail.title,revealStory:detail.story,power:{key:detail.power[0],label:detail.power[1],message:detail.power[2]}},
    featuredMoment:{year:detail.year,competition:detail.competition,apparatus:detail.apparatus,representedDelegation:detail.nation,verifiedResult:detail.result},
    element:noElement,sources:[...sourceMap.values()],assets:{...clearedAsset,alt:{en:"Partially hidden abstract silhouette of the mystery athlete",es:"Silueta abstracta parcialmente oculta de la atleta misteriosa"}},
    review:{factualStatus:"VERIFIED",technicalStatus:"NOT_APPLICABLE",translationStatus:"COMPLETE",rightsStatus:"CLEARED",reviewedBy:"PRFCT10 editorial implementation",reviewedAt:accessedAt,publishable:true,notes:[`Country label: ${names[0]} / ${names[1]}`,"No athlete photograph or identifying silhouette is used."]}
  };
}

export const gymnastRecords = masterRoster.map(([name,nation],index) => { const base=stagingRecord(index,name,nation); return details[base.id] ? completeRecord(base,details[base.id]) : base; });
export const gymnastEditorialRegistry = {version:GYMNAST_DATA_VERSION,records:gymnastRecords};
export const gymnastById = Object.fromEntries(gymnastRecords.map(record => [record.id,record]));
