export const POWER_CARD_DIMENSIONS = Object.freeze({ width: 1080, height: 1920 });
export const POWER_CHECK_BASE_ASSET = "/assets/prfct10-power-check-y2k-base.svg";
const XMUD = Object.freeze({ purple: "#7B2DFF", slime: "#C8FF00", aqua: "#35D6FF", pink: "#FF4FC3", orange: "#FF6B35", lemon: "#F4FF32" });

function esc(value) { return String(value ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function textLines(text, x, y, width, size, color, max = 3, weight = 800) {
  const words = String(text || "").split(/\s+/); const lines = []; let line = "";
  words.forEach((word) => { const candidate = line ? `${line} ${word}` : word; if (candidate.length < Math.max(12, width / (size * .52)) || !line) line = candidate; else { lines.push(line); line = word; } });
  if (line) lines.push(line);
  return `<text x="${x}" y="${y}" fill="${color}" font-family="Nunito Sans,Arial,sans-serif" font-size="${size}px" font-weight="${weight}" letter-spacing="${size > 30 ? -1 : 2}px">${lines.slice(0, max).map((lineValue, i) => `<tspan x="${x}" dy="${i ? size * 1.12 : 0}">${esc(lineValue)}</tspan>`).join("")}</text>`;
}
function bow(primary, secondary, x, y, scale = 1, opacity = .92) {
  return `<g transform="translate(${x} ${y}) scale(${scale})" opacity="${opacity}" stroke="${primary}" stroke-width="5" stroke-linejoin="round"><defs><linearGradient id="bow-${x}-${y}" x1="0" x2="1"><stop stop-color="${primary}"/><stop offset="1" stop-color="${secondary}"/></linearGradient></defs><path fill="url(#bow-${x}-${y})" d="M0 50C-80-5-120-5-155 28c20 66 72 78 155 44zM0 50C80-5 120-5 155 28c-20 66-72 78-155 44zM-5 69l-72 115 70-48 45 48zM5 69l72 115-70-48-45 48z"/><ellipse cx="0" cy="50" rx="31" ry="28" fill="${secondary}"/><circle cx="-68" cy="23" r="5" fill="#fff" stroke="none"/><circle cx="76" cy="22" r="5" fill="#fff" stroke="none"/></g>`;
}
function styleFor(colors) {
  const [a, b] = colors; const key = `${a.id}-${b.id}`;
  const map = { "fuchsia-xmudSlime": ["#E6007E", XMUD.slime, "POP POWER"], "lilac-xmudPurple": ["#A77BE8", XMUD.purple, "HOLOGRAPHIC DREAM"], "blue-xmudAqua": ["#8FD6F2", XMUD.aqua, "AIRWAVE"], "yellow-xmudOrange": ["#F9D94C", XMUD.orange, "HEAT FLASH"], "mint-xmudSlime": ["#00CFA6", XMUD.slime, "FRESH RESET"], "pink-xmudAqua": ["#F58BB2", XMUD.aqua, "CANDY FLIGHT"], "charcoal-fuchsia": ["#1C1C1C", "#E6007E", "NIGHT COMPETITION"], "white-lilac": ["#FFFFFF", "#A77BE8", "SOFT PRECISION"], "fuchsia-mint": ["#E6007E", XMUD.slime, "POP POWER"], "fuchsia-charcoal": ["#E6007E", XMUD.slime, "NIGHT COMPETITION"], "lilac-charcoal": ["#A77BE8", XMUD.purple, "HOLOGRAPHIC DREAM"], "blue-lilac": ["#8FD6F2", XMUD.purple, "AIRWAVE"], "yellow-fuchsia": ["#F9D94C", XMUD.orange, "HEAT FLASH"], "mint-fuchsia": ["#00CFA6", XMUD.slime, "FRESH RESET"], "pink-blue": ["#F58BB2", XMUD.aqua, "CANDY FLIGHT"] };
  const preset = map[key] || map[`${b.id}-${a.id}`] || [a.value, b.value, "PRFCT10 POWER MODE"];
  return { primary: preset[0], accent: preset[1], mode: preset[2], secondary: b.value };
}
function svgShell(body, background, foreground, defs = "") { return `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920" viewBox="0 0 1080 1920" data-template="${POWER_CHECK_BASE_ASSET}"><defs>${defs}</defs><rect width="1080" height="1920" fill="${background}"/>${body}</svg>`; }
function logo(foreground) { return `<g transform="translate(90 150)"><circle cx="34" cy="34" r="33" fill="${foreground}"/><path d="M14 14l40 40M54 14L14 54" stroke="#fff" stroke-width="10"/><circle cx="66" cy="2" r="8" fill="${foreground}"/><text x="85" y="47" fill="${foreground}" font-family="Nunito Sans,Arial,sans-serif" font-size="34" font-weight="900">PRFCT10</text></g>`; }
function storyOne(s) {
  const { primary, accent, secondary } = styleFor(s.colors); const fg = "#FFFFFF";
  const defs = `<linearGradient id="g1" x1="0" y1="0" x2="1" y2="1"><stop stop-color="#11101A"/><stop offset=".52" stop-color="#2E164C"/><stop offset="1" stop-color="${primary}"/></linearGradient><pattern id="check1" width="44" height="44" patternUnits="userSpaceOnUse"><rect width="44" height="44" fill="none" stroke="#fff" stroke-opacity=".14" stroke-width="2"/><path d="M0 0h22v22H0zM22 22h22v22H22z" fill="${accent}" opacity=".32"/></pattern><pattern id="dots1" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="5" cy="5" r="3" fill="${accent}" opacity=".42"/></pattern><filter id="offset1"><feDropShadow dx="12" dy="14" stdDeviation="0" flood-color="${accent}" flood-opacity=".8"/></filter>`;
  const apparatusLine = `<path d="M160 910C260 850 340 850 455 910s205 60 310 0" fill="none" stroke="${secondary}" stroke-width="7" opacity=".9"/><path d="M455 910l45-45m-45 45l45 45" stroke="#fff" stroke-width="7"/>`;
  return svgShell(`<rect width="1080" height="1920" fill="url(#g1)"/><path d="M-100 1040c300-210 500-120 710-320 190-180 390-120 530-250v1450H-100z" fill="${primary}" opacity=".42"/><rect width="1080" height="1920" fill="url(#dots1)" opacity=".45"/><rect x="40" y="40" width="1000" height="1840" rx="28" fill="url(#check1)" opacity=".55"/>${logo(fg)}<text x="90" y="395" fill="${fg}" font-family="Nunito Sans,Arial,sans-serif" font-size="27" font-weight="900" letter-spacing="6">${esc(s.label).toUpperCase()}</text>${textLines(s.mode, 90, 515, 820, 36, accent, 1, 900)}<g filter="url(#offset1)">${textLines(s.profile, 90, 650, 790, 112, fg, 2, 900)}</g><text x="90" y="895" fill="${fg}" font-family="Nunito Sans,Arial,sans-serif" font-size="34" font-weight="900" letter-spacing="4">${esc(s.apparatus).toUpperCase()}</text>${apparatusLine}<circle cx="850" cy="390" r="270" fill="none" stroke="#fff" stroke-width="5" opacity=".38"/><circle cx="850" cy="390" r="205" fill="none" stroke="${accent}" stroke-width="5" opacity=".85"/>${bow(primary, secondary, 820, 470, 1.35)}<rect x="68" y="1040" width="944" height="470" rx="58" fill="#fff" opacity=".94" stroke="#fff" stroke-width="4"/><text x="140" y="1140" fill="#1C1C1C" font-family="Nunito Sans,Arial,sans-serif" font-size="26" font-weight="900" letter-spacing="5">POWER QUOTE</text>${textLines(`“${s.quote}”`, 140, 1260, 790, 54, "#1C1C1C", 4, 900)}<path d="M90 1590h360M720 1590h270" stroke="${accent}" stroke-width="8"/><text x="90" y="1770" fill="${fg}" opacity=".82" font-family="Nunito Sans,Arial,sans-serif" font-size="22" font-weight="800" letter-spacing="4">YOUR GYMNASTICS. YOUR ENERGY. YOUR WORLD.</text>`, "#11101A", fg, defs);
}
function storyTwo(s) {
  const { primary, accent } = styleFor(s.colors); const defs = `<linearGradient id="g2" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${primary}"/><stop offset="1" stop-color="${accent}"/></linearGradient>`;
  const panels = s.colors.map((c, i) => { const fg = ["#FFFFFF", "#F9D94C", "#8FD6F2"].includes(c.value) ? "#1C1C1C" : "#FFFFFF"; return `<rect x="90" y="${650 + i * 450}" width="900" height="370" rx="38" fill="${c.value}"/><text x="140" y="${750 + i * 450}" fill="${fg}" font-family="Nunito Sans,Arial,sans-serif" font-size="51" font-weight="900">${esc(c.name).toUpperCase()}</text><text x="140" y="${810 + i * 450}" fill="${fg}" font-family="Nunito Sans,Arial,sans-serif" font-size="25" font-weight="900" letter-spacing="4">${esc(c.energy).toUpperCase()}</text>${textLines(c.description, 140, 890 + i * 450, 780, 31, fg, 3, 700)}${bow(c.value, accent, 865, 900 + i * 450, .38, .78)}`; }).join("");
  return svgShell(`${logo("#FFFFFF")}<rect width="1080" height="1920" fill="url(#g2)" opacity=".2"/><circle cx="900" cy="330" r="250" fill="none" stroke="${accent}" stroke-width="6" opacity=".55"/><text x="90" y="395" fill="${accent}" font-family="Nunito Sans,Arial,sans-serif" font-size="27" font-weight="900" letter-spacing="6">${esc(s.label).toUpperCase()}</text>${textLines(s.mixLabel, 90, 510, 850, 70, "#FFFFFF", 1, 900)}<text x="90" y="580" fill="#FFFFFF" font-family="Nunito Sans,Arial,sans-serif" font-size="31" font-weight="900" letter-spacing="2">${esc(s.mix).toUpperCase()}</text>${panels}<text x="90" y="1770" fill="#FFFFFF" opacity=".82" font-family="Nunito Sans,Arial,sans-serif" font-size="22" font-weight="800" letter-spacing="4">YOUR GYMNASTICS. YOUR ENERGY. YOUR WORLD.</text>`, "#11101A", "#FFFFFF", defs);
}
function storyThree(s) {
  const [primary, secondary] = s.colors || [{ value: "#E6007E" }, { value: "#8FD6F2" }];
  return svgShell(`${logo("#1C1C1C")}<path d="M0 1130L1080 680v500L0 1600z" fill="${primary.value}" opacity=".2"/><circle cx="900" cy="370" r="250" fill="none" stroke="${secondary.value}" stroke-width="6" opacity=".55"/>${bow(primary.value, secondary.value, 855, 470, .95, .72)}<text x="90" y="395" fill="${primary.value}" font-family="Nunito Sans,Arial,sans-serif" font-size="27" font-weight="900" letter-spacing="6">${esc(s.label).toUpperCase()}</text>${textLines(s.gymnastName, 90, 535, 820, 88, "#1C1C1C", 2, 900)}<text x="90" y="740" fill="#1C1C1C" font-family="Nunito Sans,Arial,sans-serif" font-size="30" font-weight="900" letter-spacing="4">${esc(s.countryCode)} · ${esc(s.apparatus).toUpperCase()}</text><rect x="90" y="830" width="900" height="430" rx="40" fill="#fff" stroke="${secondary.value}" stroke-width="5"/><text x="140" y="920" fill="${primary.value}" font-family="Nunito Sans,Arial,sans-serif" font-size="24" font-weight="900" letter-spacing="5">${esc(s.elementLabel).toUpperCase()}</text>${textLines(s.elementName, 140, 1010, 760, 53, "#1C1C1C", 2, 900)}${textLines(s.elementDescription, 140, 1135, 780, 28, "#1C1C1C", 3, 700)}<text x="140" y="1210" fill="${primary.value}" font-family="Nunito Sans,Arial,sans-serif" font-size="29" font-weight="900">${esc(s.worthLabel).toUpperCase()}: ${esc(s.worth)}</text><text x="90" y="1390" fill="#1C1C1C" font-family="Nunito Sans,Arial,sans-serif" font-size="24" font-weight="900" letter-spacing="5">${esc(s.factLabel).toUpperCase()}</text>${textLines(s.funFact, 90, 1470, 870, 34, "#1C1C1C", 4, 800)}${textLines(s.source, 90, 1680, 850, 21, "#1C1C1C", 2, 700)}<text x="90" y="1770" fill="#1C1C1C" opacity=".72" font-family="Nunito Sans,Arial,sans-serif" font-size="22" font-weight="800" letter-spacing="4">YOUR GYMNASTICS. YOUR ENERGY. YOUR WORLD.</text>`, "#F5F0FF", "#1C1C1C");
}
export function createPowerPackSvgs({ pack }) { return [storyOne(pack.storyOne), storyTwo(pack.storyTwo), storyThree(pack.storyThree)]; }
async function svgToBlob(svg) {
  const source = new Blob([svg], { type: "image/svg+xml;charset=utf-8" }); const url = URL.createObjectURL(source); const image = new Image(); image.src = url; await image.decode(); URL.revokeObjectURL(url);
  const canvas = document.createElement("canvas"); canvas.width = POWER_CARD_DIMENSIONS.width; canvas.height = POWER_CARD_DIMENSIONS.height; canvas.getContext("2d").drawImage(image, 0, 0, 1080, 1920); return new Promise((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("Unable to create PNG")), "image/png", 1));
}
export async function createPowerPackBlobs({ pack }) { await document.fonts?.ready; return Promise.all(createPowerPackSvgs({ pack }).map(svgToBlob)); }
function download(blob, filename, type = "image/png") { const url = URL.createObjectURL(blob instanceof Blob ? blob : new Blob([blob], { type })); const link = document.createElement("a"); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); window.setTimeout(() => URL.revokeObjectURL(url), 1500); }
export function downloadPowerStory(blob, storyNumber) { download(blob, `prfct10-power-pack-story-${storyNumber}.png`); }
export function downloadPowerPack(blobs) { blobs.forEach((blob, index) => window.setTimeout(() => downloadPowerStory(blob, index + 1), index * 180)); }
export function downloadPowerStorySvg(svg, storyNumber) { download(svg, `prfct10-power-pack-story-${storyNumber}.svg`, "image/svg+xml"); }
